using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.Configuration;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Audit;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Entities.AccountingAudit;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.ValueObjects;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Services;
using FactuTrust.Infrastructure.Services.AccountingAudit;
using FactuTrust.Infrastructure.Services.AccountingAudit.Rules;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.AccountingAudit;

/// <summary>
/// Famille « Comptable » du réviseur. Chaque règle est éprouvée sur le cas sain (silence attendu)
/// ET sur le cas dégradé : une règle qui ne se tait pas sur un dossier propre est aussitôt
/// désactivée par l'utilisateur, et une règle muette ne sert à rien.
/// </summary>
public sealed class AccountingFamilyRulesTests
{
    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;

        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(_databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private const int Year = 2026;

    private static TestTenantDbContextFactory NewFactory(string label) => new($"{label}_{Guid.NewGuid()}");

    private static AuditEvaluationContextImpl Context(TenantDbContext db) => new(
        db,
        new AccountingSettings(),
        Year,
        new DateOnly(Year, 1, 1),
        new DateOnly(Year, 12, 31),
        Array.Empty<AccountingControlRuleSetting>(),
        moduleCodesFilter: null);

    private static async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        TestTenantDbContextFactory factory, IAccountingAuditRule rule)
    {
        await using var db = factory.CreateContext();
        return await rule.EvaluateAsync(Context(db), CancellationToken.None);
    }

    private static JournalEntry Entry(
        int number,
        DateTime date,
        string? sourceType,
        Guid? sourceId,
        params JournalLineInput[] lines)
    {
        var entry = JournalEntry.Create(
            number, "JV", date, $"Écriture {number}", Guid.NewGuid(),
            isAutoGenerated: sourceType is not null,
            sourceEntityType: sourceType,
            sourceEntityId: sourceId,
            lines,
            initialStatus: JournalEntryStatus.Validee).Value;
        entry.SetAuditInfo("test", false);
        return entry;
    }

    // ── TVA comptabilisée vs document ─────────────────────────────────────────────────────

    /// <summary>Facture dont la TVA comptabilisée correspond : la règle doit rester muette.</summary>
    [Fact]
    public async Task Vat_versus_document_is_silent_when_amounts_match()
    {
        var factory = NewFactory("VatMatch");
        var invoice = NewValidatedInvoice();

        await using (var db = factory.CreateContext())
        {
            db.Invoices.Add(invoice);
            db.JournalEntries.Add(BookInvoice(1, invoice, bookedVat: invoice.TotalVat.Amount));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new VatVersusDocumentAuditRule()));
    }

    [Fact]
    public async Task Vat_versus_document_flags_a_divergence_and_reports_the_gap()
    {
        var factory = NewFactory("VatGap");
        var invoice = NewValidatedInvoice();
        var documentVat = invoice.TotalVat.Amount;
        var bookedVat = documentVat - 6m;

        await using (var db = factory.CreateContext())
        {
            db.Invoices.Add(invoice);
            db.JournalEntries.Add(BookInvoice(1, invoice, bookedVat));
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new VatVersusDocumentAuditRule()));
        Assert.Equal(6m, anomaly.Amount);
    }

    /// <summary>
    /// Un écart d'un millime relève de l'arrondi, pas de l'anomalie : le signaler noierait le
    /// réviseur sous des faux positifs sur chaque facture à taux mêlés.
    /// </summary>
    [Fact]
    public async Task Vat_versus_document_tolerates_a_millime_rounding_gap()
    {
        var factory = NewFactory("VatRounding");
        var invoice = NewValidatedInvoice();

        await using (var db = factory.CreateContext())
        {
            db.Invoices.Add(invoice);
            db.JournalEntries.Add(BookInvoice(1, invoice, invoice.TotalVat.Amount + 0.001m));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new VatVersusDocumentAuditRule()));
    }

    /// <summary>Deux écritures en écart doivent produire deux anomalies distinctes, pas une qui écrase l'autre.</summary>
    [Fact]
    public async Task Vat_versus_document_produces_distinct_fingerprints_per_entry()
    {
        var factory = NewFactory("VatFingerprints");
        var first = NewValidatedInvoice();
        var second = NewValidatedInvoice();

        await using (var db = factory.CreateContext())
        {
            db.Invoices.AddRange(first, second);
            db.JournalEntries.Add(BookInvoice(1, first, first.TotalVat.Amount - 6m));
            db.JournalEntries.Add(BookInvoice(2, second, second.TotalVat.Amount - 6m));
            await db.SaveChangesAsync();
        }

        var found = await EvaluateAsync(factory, new VatVersusDocumentAuditRule());

        Assert.Equal(2, found.Count);
        Assert.Equal(2, found.Select(f => f.Fingerprint).Distinct().Count());
    }

    // ── Tiers vs compte collectif ─────────────────────────────────────────────────────────

    [Fact]
    public async Task Third_party_mismatch_is_silent_on_well_formed_entries()
    {
        var factory = NewFactory("ThirdPartyOk");
        var clientId = Guid.NewGuid();

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 5, 2), null, null,
                new JournalLineInput("4111", "Client", 100m, 0m, clientId, ThirdPartyKind.Client),
                new JournalLineInput("707", "Vente", 0m, 100m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new ThirdPartyAccountMismatchAuditRule()));
    }

    [Fact]
    public async Task Third_party_mismatch_separates_the_three_kinds_of_breakage()
    {
        var factory = NewFactory("ThirdPartyKinds");

        await using (var db = factory.CreateContext())
        {
            // Client sur un 607 : mauvaise classe.
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 5, 2), null, null,
                new JournalLineInput("607", "Achat", 100m, 0m, Guid.NewGuid(), ThirdPartyKind.Client),
                new JournalLineInput("532", "Banque", 0m, 100m, null, ThirdPartyKind.None)));
            // Fournisseur sur un 411 : sens inversé.
            db.JournalEntries.Add(Entry(2, new DateTime(Year, 5, 3), null, null,
                new JournalLineInput("4111", "Client", 0m, 50m, Guid.NewGuid(), ThirdPartyKind.Supplier),
                new JournalLineInput("532", "Banque", 50m, 0m, null, ThirdPartyKind.None)));
            // Compte collectif sans tiers : balance auxiliaire incomplète.
            db.JournalEntries.Add(Entry(3, new DateTime(Year, 5, 4), null, null,
                new JournalLineInput("4011", "Fournisseur", 0m, 70m, null, ThirdPartyKind.None),
                new JournalLineInput("607", "Achat", 70m, 0m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        var found = await EvaluateAsync(factory, new ThirdPartyAccountMismatchAuditRule());

        Assert.Equal(3, found.Count);
        Assert.Equal(3, found.Select(f => f.Fingerprint).Distinct().Count());
    }

    // ── Lettrage orphelin ─────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Lettering_orphan_is_silent_on_a_balanced_single_account_group()
    {
        var factory = NewFactory("LetteringOk");
        await SeedLetteringAsync(factory, sameAccount: true, balanced: true, dropOneMember: false);

        Assert.Empty(await EvaluateAsync(factory, new LetteringOrphanAuditRule()));
    }

    [Fact]
    public async Task Lettering_orphan_flags_a_group_spanning_two_accounts()
    {
        var factory = NewFactory("LetteringAccounts");
        await SeedLetteringAsync(factory, sameAccount: false, balanced: true, dropOneMember: false);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new LetteringOrphanAuditRule()));
        Assert.Contains("comptes", anomaly.Description);
    }

    [Fact]
    public async Task Lettering_orphan_flags_a_member_pointing_to_a_vanished_line()
    {
        var factory = NewFactory("LetteringMissing");
        await SeedLetteringAsync(factory, sameAccount: true, balanced: true, dropOneMember: true);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new LetteringOrphanAuditRule()));
        Assert.Contains("introuvable", anomaly.Description);
    }

    [Fact]
    public async Task Lettering_orphan_flags_an_unbalanced_non_partial_group()
    {
        var factory = NewFactory("LetteringUnbalanced");
        await SeedLetteringAsync(factory, sameAccount: true, balanced: false, dropOneMember: false);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new LetteringOrphanAuditRule()));
        Assert.Contains("déséquilibré", anomaly.Description);
    }

    // ── Extourne manquante ────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Reversal_missing_flags_an_entry_marked_reversed_without_counterpart()
    {
        var factory = NewFactory("ReversalFlagged");

        await using (var db = factory.CreateContext())
        {
            var entry = Entry(1, new DateTime(Year, 6, 1), null, null,
                new JournalLineInput("607", "Achat", 100m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("532", "Banque", 0m, 100m, null, ThirdPartyKind.None));
            // Marque d'extourne pointant une écriture qui n'existe pas.
            entry.MarkReversedBy(Guid.NewGuid());
            db.JournalEntries.Add(entry);
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new ReversalMissingAuditRule()));
        Assert.Contains("contre-passation", anomaly.Description);
        Assert.Equal((int)PreClosingSeverity.Blocking, anomaly.Severity);
    }

    [Fact]
    public async Task Reversal_missing_flags_a_cancelled_invoice_never_reversed()
    {
        var factory = NewFactory("ReversalCancelled");
        var invoice = NewValidatedInvoice();
        Assert.True(invoice.Cancel("annulation de test").IsSuccess);

        await using (var db = factory.CreateContext())
        {
            db.Invoices.Add(invoice);
            db.JournalEntries.Add(BookInvoice(1, invoice, invoice.TotalVat.Amount));
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new ReversalMissingAuditRule()));
        Assert.Contains("annulée", anomaly.Description);
        Assert.Equal(invoice.TotalAmount.Amount, anomaly.Amount);
    }

    [Fact]
    public async Task Reversal_missing_is_silent_when_the_counter_entry_exists()
    {
        var factory = NewFactory("ReversalOk");
        var invoice = NewValidatedInvoice();
        Assert.True(invoice.Cancel("annulation de test").IsSuccess);

        await using (var db = factory.CreateContext())
        {
            db.Invoices.Add(invoice);

            var source = BookInvoice(1, invoice, invoice.TotalVat.Amount);
            db.JournalEntries.Add(source);

            var ht = invoice.SubTotal.Amount;
            var vat = invoice.TotalVat.Amount;
            var counter = JournalEntry.Create(
                2, "JV", new DateTime(Year, 6, 2), "Extourne", Guid.NewGuid(),
                isAutoGenerated: true,
                sourceEntityType: AccountingService.SourceInvoiceCancelled,
                sourceEntityId: invoice.Id,
                [
                    new JournalLineInput("707", "Vente", ht, 0m, null, ThirdPartyKind.None),
                    new JournalLineInput("436711", "TVA collectée", vat, 0m, null, ThirdPartyKind.None),
                    new JournalLineInput("4111", "Client", 0m, ht + vat, null, ThirdPartyKind.None)
                ],
                reversesEntryId: source.Id,
                initialStatus: JournalEntryStatus.Validee).Value;
            counter.SetAuditInfo("test", false);
            db.JournalEntries.Add(counter);

            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new ReversalMissingAuditRule()));
    }

    // ── Fixtures ──────────────────────────────────────────────────────────────────────────

    private static int _invoiceSequence = 1;

    /// <summary>
    /// Facture validée d'une ligne à 100 HT en TVA 19 %. Les totaux sont calculés par le domaine :
    /// les tests lisent <c>TotalVat</c> plutôt que de coder en dur une valeur qui dériverait au
    /// moindre changement de règle de calcul (timbre, FODEC).
    /// </summary>
    private static Invoice NewValidatedInvoice()
    {
        var invoice = Invoice.Create(
            InvoiceNumber.Create("FAC", Year, _invoiceSequence++),
            NewClient(),
            new DateTime(Year, 4, 10)).Value;

        Assert.True(invoice
            .AddCustomLine("Article", null, 1m, "Unité", Money.Create(100m), VatRate.Standard)
            .IsSuccess);
        Assert.True(invoice.Validate().IsSuccess);
        invoice.SetAuditInfo("test", false);
        return invoice;
    }

    private static Client NewClient() =>
        Client.Create(
            "Client test", ClientType.Business,
            Address.Create("Rue 1", "Tunis", "Tunis").Value,
            Email.Create("client@test.tn").Value,
            NIF.Create("1234567/A/B/C/000").Value).Value;

    /// <summary>
    /// Écriture de vente rattachée à la facture, avec un montant de TVA imposé — c'est le levier
    /// des tests : faire diverger le comptabilisé du document.
    /// </summary>
    private static JournalEntry BookInvoice(int number, Invoice invoice, decimal bookedVat)
    {
        var ht = invoice.SubTotal.Amount;
        return Entry(number, invoice.IssueDate, AccountingService.SourceInvoice, invoice.Id,
            new JournalLineInput("4111", "Client", ht + bookedVat, 0m, null, ThirdPartyKind.None),
            new JournalLineInput("707", "Vente", 0m, ht, null, ThirdPartyKind.None),
            new JournalLineInput("436711", "TVA collectée", 0m, bookedVat, null, ThirdPartyKind.None));
    }

    private static async Task SeedLetteringAsync(
        TestTenantDbContextFactory factory, bool sameAccount, bool balanced, bool dropOneMember)
    {
        await using var db = factory.CreateContext();

        var secondAccount = sameAccount ? "4111" : "4011";
        var creditAmount = balanced ? 100m : 60m;

        var entry = Entry(1, new DateTime(Year, 7, 1), null, null,
            new JournalLineInput("4111", "Facture", 100m, 0m, null, ThirdPartyKind.None),
            new JournalLineInput(secondAccount, "Règlement", 0m, creditAmount, null, ThirdPartyKind.None),
            new JournalLineInput("532", "Banque", creditAmount, 0m, null, ThirdPartyKind.None),
            new JournalLineInput("707", "Vente", 0m, 100m, null, ThirdPartyKind.None));
        db.JournalEntries.Add(entry);
        await db.SaveChangesAsync();

        var lines = entry.Lines.Take(2).Select(l => l.Id).ToList();
        // Un membre pointant un identifiant inexistant simule la ligne disparue.
        var memberIds = dropOneMember ? new List<Guid> { lines[0], Guid.NewGuid() } : lines;

        var group = LetteringGroup.Create(
            "AA0001", "4111", Money.Create(100m), memberIds, isPartial: false).Value;
        group.SetAuditInfo("test", false);
        db.LetteringGroups.Add(group);
        await db.SaveChangesAsync();
    }
}
