using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.Configuration;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Audit;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Entities.AccountingAudit;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.ValueObjects;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Services.AccountingAudit;
using FactuTrust.Infrastructure.Services.AccountingAudit.Rules;
using Microsoft.EntityFrameworkCore;
using Xunit;
using FactuTrust.Application.Common;

namespace FactuTrust.Infrastructure.Tests.AccountingAudit;

/// <summary>
/// Famille « Documentaire » du réviseur : justification, doublons et écarts de prix sur les achats.
/// </summary>
public sealed class DocumentaryFamilyRulesTests
{
    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;

        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(_databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private const int Year = 2026;

    private static TestTenantDbContextFactory NewFactory(string label) => new($"{label}_{Guid.NewGuid()}");

    private static async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        TestTenantDbContextFactory factory,
        IAccountingAuditRule rule,
        params AccountingControlRuleSetting[] settings)
    {
        await using var db = factory.CreateContext();
        var ctx = new AuditEvaluationContextImpl(
            db, new AccountingSettings(), Year,
            new DateOnly(Year, 1, 1), new DateOnly(Year, 12, 31),
            settings, moduleCodesFilter: null);
        return await rule.EvaluateAsync(ctx, CancellationToken.None);
    }

    // ── Normalisation des numéros ─────────────────────────────────────────────────────────

    [Theory]
    [InlineData("FA-00123", "FA123")]
    [InlineData("fa 123", "FA123")]
    [InlineData("FA000123", "FA123")]
    [InlineData("  FA/123  ", "FA123")]
    [InlineData("123", "123")]
    [InlineData("000", "0")]
    [InlineData("", "")]
    [InlineData(null, "")]
    [InlineData("---", "")]
    public void Invoice_number_normalization_collapses_common_variants(string? raw, string expected)
    {
        Assert.Equal(expected, SupplierInvoiceNumberNormalizer.Normalize(raw));
    }

    [Fact]
    public void Invoice_number_normalization_keeps_genuinely_different_numbers_apart()
    {
        Assert.NotEqual(
            SupplierInvoiceNumberNormalizer.Normalize("FA-123"),
            SupplierInvoiceNumberNormalizer.Normalize("FB-123"));
    }

    // ── Facture sans pièce ────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Missing_proof_flags_an_invoice_with_no_attachment_anywhere()
    {
        var factory = NewFactory("ProofMissing");

        await using (var db = factory.CreateContext())
        {
            NewPurchaseCycle(NewSupplier(), "FA-001", new DateTime(Year, 3, 5), 500m).PersistTo(db);
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new SupplierInvoiceWithoutProofAuditRule()));
        Assert.Equal((int)PreClosingSeverity.Blocking, anomaly.Severity);
        Assert.Single(anomaly.Lines);
    }

    /// <summary>
    /// Une pièce attachée à l'écriture comptable justifie la facture : la signaler quand même
    /// ferait perdre confiance dans tout le contrôle.
    /// </summary>
    [Fact]
    public async Task Missing_proof_accepts_an_attachment_carried_by_the_journal_entry()
    {
        var factory = NewFactory("ProofOnEntry");

        await using (var db = factory.CreateContext())
        {
            var cycle = NewPurchaseCycle(NewSupplier(), "FA-002", new DateTime(Year, 3, 5), 500m);
            cycle.PersistTo(db);

            var entry = JournalEntry.Create(
                1, "JA", new DateTime(Year, 3, 5), "Achat", Guid.NewGuid(),
                isAutoGenerated: true,
                sourceEntityType: FactuTrust.Infrastructure.Services.AccountingService.SourceSupplierInvoice,
                sourceEntityId: cycle.Invoice.Id,
                [
                    new JournalLineInput("607", "Achat", 500m, 0m, null, ThirdPartyKind.None),
                    new JournalLineInput("4011", "Fournisseur", 0m, 500m, null, ThirdPartyKind.None)
                ],
                initialStatus: JournalEntryStatus.Validee).Value;
            entry.SetAuditInfo("test", false);
            db.JournalEntries.Add(entry);

            db.JournalEntryAttachments.Add(JournalEntryAttachment.Create(
                entry.Id, "facture.pdf", "storage/facture.pdf", "application/pdf", 1024).Value);

            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new SupplierInvoiceWithoutProofAuditRule()));
    }

    [Fact]
    public async Task Missing_proof_ignores_cancelled_invoices()
    {
        var factory = NewFactory("ProofCancelled");

        await using (var db = factory.CreateContext())
        {
            var cycle = NewPurchaseCycle(NewSupplier(), "FA-003", new DateTime(Year, 3, 5), 500m);
            Assert.True(cycle.Invoice.Cancel("annulée").IsSuccess);
            cycle.PersistTo(db);
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new SupplierInvoiceWithoutProofAuditRule()));
    }

    // ── Doublons ──────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Deux factures du même fournisseur, chacune avec son cycle d'achat. <paramref name="sameSupplier"/>
    /// à faux sépare les fournisseurs, ce qui doit suffire à écarter la détection.
    /// </summary>
    private static async Task SeedTwoInvoicesAsync(
        TestTenantDbContextFactory factory,
        string firstNumber, DateTime firstDate, decimal firstPrice,
        string secondNumber, DateTime secondDate, decimal secondPrice,
        bool sameSupplier = true)
    {
        await using var db = factory.CreateContext();

        var supplier = NewSupplier("Fournisseur A");
        NewPurchaseCycle(supplier, firstNumber, firstDate, firstPrice).PersistTo(db);

        var secondSupplier = sameSupplier ? supplier : NewSupplier("Fournisseur B");
        var second = NewPurchaseCycle(secondSupplier, secondNumber, secondDate, secondPrice);
        if (!sameSupplier) db.Suppliers.Add(secondSupplier);
        second.PersistTo(db);

        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task Duplicate_detects_the_same_number_written_differently()
    {
        var factory = NewFactory("DupStrict");
        await SeedTwoInvoicesAsync(factory,
            "FA-00123", new DateTime(Year, 3, 5), 500m,
            "fa 123", new DateTime(Year, 6, 20), 500m);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new SupplierInvoiceDuplicateAuditRule()));
        Assert.Equal((int)PreClosingSeverity.Blocking, anomaly.Severity);
        Assert.Equal(2, anomaly.Lines.Count);
    }

    [Fact]
    public async Task Duplicate_does_not_confuse_two_suppliers_sharing_a_number()
    {
        var factory = NewFactory("DupSuppliers");
        await SeedTwoInvoicesAsync(factory,
            "FA-001", new DateTime(Year, 3, 5), 500m,
            "FA-001", new DateTime(Year, 3, 5), 500m,
            sameSupplier: false);

        Assert.Empty(await EvaluateAsync(factory, new SupplierInvoiceDuplicateAuditRule()));
    }

    [Fact]
    public async Task Duplicate_flags_a_near_match_as_a_warning_not_a_blocker()
    {
        var factory = NewFactory("DupNear");
        await SeedTwoInvoicesAsync(factory,
            "FA-001", new DateTime(Year, 3, 5), 500m,
            "FA-999", new DateTime(Year, 3, 8), 500m);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new SupplierInvoiceDuplicateAuditRule()));
        Assert.Equal((int)PreClosingSeverity.Warning, anomaly.Severity);
        Assert.Equal(2, anomaly.Lines.Count);
    }

    [Fact]
    public async Task Duplicate_ignores_a_near_match_outside_the_time_window()
    {
        var factory = NewFactory("DupWindow");
        // 6 jours d'écart : hors fenêtre de 5 jours.
        await SeedTwoInvoicesAsync(factory,
            "FA-001", new DateTime(Year, 3, 5), 500m,
            "FA-999", new DateTime(Year, 3, 11), 500m);

        Assert.Empty(await EvaluateAsync(factory, new SupplierInvoiceDuplicateAuditRule()));
    }

    [Fact]
    public async Task Duplicate_ignores_a_near_match_with_a_different_amount()
    {
        var factory = NewFactory("DupAmount");
        await SeedTwoInvoicesAsync(factory,
            "FA-001", new DateTime(Year, 3, 5), 500m,
            "FA-999", new DateTime(Year, 3, 6), 501m);

        Assert.Empty(await EvaluateAsync(factory, new SupplierInvoiceDuplicateAuditRule()));
    }

    /// <summary>Un doublon strict ne doit pas être re-signalé une seconde fois en doublon approché.</summary>
    [Fact]
    public async Task Duplicate_does_not_report_a_strict_match_twice()
    {
        var factory = NewFactory("DupNoDoubleReport");
        await SeedTwoInvoicesAsync(factory,
            "FA-00123", new DateTime(Year, 3, 5), 500m,
            "FA-123", new DateTime(Year, 3, 6), 500m);

        var found = await EvaluateAsync(factory, new SupplierInvoiceDuplicateAuditRule());

        Assert.Single(found);
        Assert.Equal((int)PreClosingSeverity.Blocking, found[0].Severity);
    }

    // ── Écart de prix ─────────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Price_drift_is_silent_within_the_threshold()
    {
        var factory = NewFactory("DriftOk");
        await SeedPurchaseAsync(factory, orderedPrice: 100m, invoicedPrice: 105m);

        Assert.Empty(await EvaluateAsync(factory, new PurchasePriceDriftAuditRule()));
    }

    [Fact]
    public async Task Price_drift_flags_an_invoice_above_the_threshold()
    {
        var factory = NewFactory("DriftFlag");
        await SeedPurchaseAsync(factory, orderedPrice: 100m, invoicedPrice: 130m);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new PurchasePriceDriftAuditRule()));
        Assert.Equal(30m, anomaly.Amount);
    }

    /// <summary>Le seuil est réglable par dossier : un tenant tolérant ne doit pas voir l'anomalie.</summary>
    [Fact]
    public async Task Price_drift_honours_the_tenant_threshold_override()
    {
        var factory = NewFactory("DriftThreshold");
        await SeedPurchaseAsync(factory, orderedPrice: 100m, invoicedPrice: 130m);

        var relaxed = new AccountingControlRuleSetting
        {
            RuleCode = "purchase-price-drift",
            IsEnabled = true,
            DecimalThreshold = 50m
        };

        Assert.Empty(await EvaluateAsync(factory, new PurchasePriceDriftAuditRule(), relaxed));
    }

    /// <summary>Sans commande de référence, comparer à quoi que ce soit serait arbitraire.</summary>
    [Fact]
    public async Task Price_drift_abstains_when_no_purchase_order_exists()
    {
        var factory = NewFactory("DriftNoOrder");

        await using (var db = factory.CreateContext())
        {
            // La facture est enregistrée SANS sa commande : plus aucun prix de référence.
            NewPurchaseCycle(NewSupplier(), "FA-001", new DateTime(Year, 4, 1), 900m)
                .PersistTo(db, includeOrder: false);
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new PurchasePriceDriftAuditRule()));
    }

    // ── Fixtures ──────────────────────────────────────────────────────────────────────────

    private static int _sequence = 1;

    private static Supplier NewSupplier(string name = "Fournisseur test") =>
        Supplier.Create(
            name,
            SupplierType.Business,
            Address.Create("Rue 1", "Tunis", "Tunis").Value,
            Email.Create($"f{_sequence++}@test.tn").Value,
            nif: NIF.Create("1234567/A/B/C/000").Value).Value;

    /// <summary>
    /// Un cycle d'achat complet et cohérent. La facture est produite par la vraie chaîne du domaine
    /// (commande → confirmation → réception → facturation) : totaux et rattachement des lignes à la
    /// commande sont ceux de la production, pas d'une fabrique de test.
    ///
    /// <para><see cref="PersistTo"/> ajoute <b>tout</b> l'agrégat. Persister la seule facture
    /// échouerait : le produit atteint par le graphe porte un owned type <c>Money</c>, qu'EF refuse
    /// d'enregistrer sans son propriétaire.</para>
    /// </summary>
    private sealed record PurchaseCycle(
        Supplier Supplier,
        ProductCategory Category,
        Product Product,
        PurchaseOrder Order,
        SupplierInvoice Invoice)
    {
        public void PersistTo(TenantDbContext db, bool includeOrder = true)
        {
            db.Suppliers.Add(Supplier);
            db.ProductCategories.Add(Category);
            db.Products.Add(Product);
            if (includeOrder) db.PurchaseOrders.Add(Order);
            db.SupplierInvoices.Add(Invoice);
        }
    }

    private static PurchaseCycle NewPurchaseCycle(
        Supplier supplier, string number, DateTime date, decimal unitPriceHt)
    {
        var category = ProductCategory.Create("GEN", "Général").Value;
        // Chaque propriété « owned » doit recevoir SA PROPRE instance de Money : partager le même
        // objet entre deux navigations owned casse le suivi EF à la persistance.
        var product = Product.Create(
            $"PR-{_sequence++}", "Article test", ProductType.Product,
            Money.Create(unitPriceHt), VatRate.Standard, category.Id,
            purchasePrice: Money.Create(unitPriceHt)).Value;

        var order = PurchaseOrder.Create(
            PurchaseOrderNumber.Create("BC", Year, _sequence++),
            supplier,
            date.AddDays(-10)).Value;

        Assert.True(order.AddLine(product, 1m).IsSuccess);
        Assert.True(order.Confirm().IsSuccess);
        Assert.True(order.ReceiveGoods([(order.Lines.First().Id, 1m)]).IsSuccess);

        var selections = order.Lines
            .Where(l => l.ReceivedNotInvoicedQuantity > 0)
            .Select(l => (l.Id, l.ReceivedNotInvoicedQuantity))
            .ToList();

        var invoice = SupplierInvoice.CreateFromPurchaseOrder(order, number, date, selections).Value;
        invoice.SetAuditInfo("test", false);

        return new PurchaseCycle(supplier, category, product, order, invoice);
    }

    /// <summary>
    /// Commandé à un prix, reçu et facturé à un autre — le scénario métier exact de la dérive de
    /// prix. On passe par le bon de réception, qui accepte un prix unitaire explicite : aucune
    /// manipulation du suivi EF n'est nécessaire, le cycle reste celui de la production.
    /// </summary>
    private static async Task SeedPurchaseAsync(
        TestTenantDbContextFactory factory, decimal orderedPrice, decimal invoicedPrice)
    {
        var supplier = NewSupplier();
        var warehouse = Warehouse.Create("WH1", "Principal").Value;
        var category = ProductCategory.Create("GEN", "Général").Value;
        var product = Product.Create(
            $"PR-{_sequence++}", "Article test", ProductType.Product,
            Money.Create(orderedPrice), VatRate.Standard, category.Id,
            purchasePrice: Money.Create(orderedPrice)).Value;

        var order = PurchaseOrder.Create(
            PurchaseOrderNumber.Create("BC", Year, _sequence++), supplier, new DateTime(Year, 3, 1)).Value;
        Assert.True(order.AddLine(product, 1m).IsSuccess);
        Assert.True(order.Confirm().IsSuccess);
        var orderLineId = order.Lines.First().Id;
        Assert.True(order.ReceiveGoods([(orderLineId, 1m)]).IsSuccess);

        var receipt = PurchaseReceipt.Create(
            PurchaseReceiptNumber.Create("BR", Year, _sequence++),
            supplier, warehouse, new DateTime(Year, 3, 20), purchaseOrderId: order.Id).Value;
        // Le prix RÉELLEMENT reçu, qui s'écarte du prix commandé.
        Assert.True(receipt.AddLine(
            product, 1m, Money.Create(invoicedPrice),
            orderedQuantity: 1m, purchaseOrderLineId: orderLineId).IsSuccess);
        Assert.True(receipt.MarkValidated().IsSuccess);

        var receiptLine = receipt.Lines.First();
        var invoice = SupplierInvoice.CreateFromPurchaseReceipt(
            receipt, order, "FA-001", new DateTime(Year, 4, 1),
            [(receiptLine.Id, receiptLine.ReceivedNotInvoicedQuantity)]).Value;
        invoice.SetAuditInfo("test", false);

        await using var db = factory.CreateContext();
        db.ProductCategories.Add(category);
        db.Products.Add(product);
        db.Suppliers.Add(supplier);
        db.Warehouses.Add(warehouse);
        db.PurchaseOrders.Add(order);
        db.PurchaseReceipts.Add(receipt);
        db.SupplierInvoices.Add(invoice);
        await db.SaveChangesAsync();
    }
}
