using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.Configuration;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Audit;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Entities.AccountingAudit;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.ValueObjects;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Services.AccountingAudit;
using FactuTrust.Infrastructure.Services.AccountingAudit.Rules;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.AccountingAudit;

/// <summary>
/// Famille « fraude douce ».
///
/// <para>Ces règles portent un risque particulier : celui de <b>désigner à tort</b>. Chaque test de
/// cas positif est donc doublé d'un test de cas légitime — l'écriture automatique, le fournisseur
/// réglé après délai normal, la facture isolée sous le seuil. Une règle qui accuse à tort est pire
/// qu'une règle absente.</para>
/// </summary>
public sealed class SoftFraudRulesTests
{
    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;

        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(_databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private const int Year = 2026;
    private const decimal Threshold = 1000m;
    private static int _sequence = 1;

    private static TestTenantDbContextFactory NewFactory(string label) => new($"{label}_{Guid.NewGuid()}");

    private static async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        TestTenantDbContextFactory factory,
        IAccountingAuditRule rule,
        params AccountingControlRuleSetting[] settings)
    {
        await using var db = factory.CreateContext();
        var ctx = new AuditEvaluationContextImpl(
            db, new AccountingSettings(), Year,
            new DateOnly(Year, 1, 1), new DateOnly(Year, 12, 31),
            settings, moduleCodesFilter: null);
        return await rule.EvaluateAsync(ctx, CancellationToken.None);
    }

    private static Supplier NewSupplier(string name = "Fournisseur test") =>
        Supplier.Create(
            name, SupplierType.Business,
            Address.Create("Rue 1", "Tunis", "Tunis").Value,
            Email.Create($"f{_sequence++}@test.tn").Value,
            nif: NIF.Create("1234567/A/B/C/000").Value).Value;

    /// <summary>
    /// Cycle d'achat complet : produit, commande confirmée et reçue, facture. C'est le seul chemin
    /// qui produit une facture fournisseur avec des totaux calculés par le domaine.
    /// </summary>
    private static SupplierInvoice NewInvoice(
        TenantDbContext db, Supplier supplier, string number, DateTime date, decimal unitPriceHt)
    {
        var category = ProductCategory.Create($"C{_sequence}", "Catégorie").Value;
        // Chaque propriété owned reçoit SA PROPRE instance de Money : partager l'objet casse le
        // suivi EF à la persistance.
        var product = Product.Create(
            $"PR-{_sequence++}", "Article", ProductType.Product,
            Money.Create(unitPriceHt), VatRate.Exempt, category.Id,
            purchasePrice: Money.Create(unitPriceHt)).Value;

        var order = PurchaseOrder.Create(
            PurchaseOrderNumber.Create("BC", Year, _sequence++), supplier, date.AddDays(-5)).Value;
        Assert.True(order.AddLine(product, 1m).IsSuccess);
        Assert.True(order.Confirm().IsSuccess);
        Assert.True(order.ReceiveGoods([(order.Lines.First().Id, 1m)]).IsSuccess);

        var selections = order.Lines
            .Where(l => l.ReceivedNotInvoicedQuantity > 0)
            .Select(l => (l.Id, l.ReceivedNotInvoicedQuantity))
            .ToList();

        var invoice = SupplierInvoice.CreateFromPurchaseOrder(order, number, date, selections).Value;
        invoice.SetAuditInfo("test", false);

        db.ProductCategories.Add(category);
        db.Products.Add(product);
        db.PurchaseOrders.Add(order);
        db.SupplierInvoices.Add(invoice);
        return invoice;
    }

    private static JournalEntry Entry(
        int number, DateTime entryDate, bool isAutoGenerated, string createdBy, string? validatedBy)
    {
        var entry = JournalEntry.Create(
            number, "JOD", entryDate, $"Écriture {number}", Guid.NewGuid(),
            isAutoGenerated,
            sourceEntityType: isAutoGenerated ? "Invoice" : null,
            sourceEntityId: isAutoGenerated ? Guid.NewGuid() : null,
            [
                new JournalLineInput("6132", "Charge", 100m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("532", "Banque", 0m, 100m, null, ThirdPartyKind.None)
            ],
            // TOUJOURS créée en brouillard : Validate() sort sans rien faire sur une écriture déjà
            // validée, et ValidatedBy resterait nul — la règle n'aurait alors rien à comparer.
            initialStatus: JournalEntryStatus.Brouillon).Value;

        entry.SetAuditInfo(createdBy, false);
        if (validatedBy is not null)
            Assert.True(entry.Validate(validatedBy).IsSuccess);
        return entry;
    }

    // ── Montants sous le seuil ────────────────────────────────────────────────────────────

    private static async Task SeedInBandInvoicesAsync(
        TestTenantDbContextFactory factory, int count, bool withThreshold = true, bool sameSupplier = true)
    {
        await using var db = factory.CreateContext();

        if (withThreshold)
            db.WithholdingFiscalYearParameters.Add(
                WithholdingFiscalYearParameter.Create(Year, Threshold));

        var shared = NewSupplier("Fournisseur A");
        db.Suppliers.Add(shared);

        for (var i = 0; i < count; i++)
        {
            var supplier = shared;
            if (!sameSupplier)
            {
                supplier = NewSupplier($"Fournisseur {i}");
                db.Suppliers.Add(supplier);
            }

            // 950 TND : dans la bande [900, 1000[.
            NewInvoice(db, supplier, $"FA-{i:D3}", new DateTime(Year, 3, 1 + i), 950m);
        }

        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task Structuring_flags_a_cluster_just_below_the_threshold()
    {
        var factory = NewFactory("Structuring");
        await SeedInBandInvoicesAsync(factory, count: 4);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new ThresholdStructuringAuditRule()));
        Assert.Equal(4, anomaly.Lines.Count);
    }

    /// <summary>Deux factures ne font pas un schéma : c'est la répétition qui interpelle.</summary>
    [Fact]
    public async Task Structuring_is_silent_below_the_occurrence_count()
    {
        var factory = NewFactory("StructuringFew");
        await SeedInBandInvoicesAsync(factory, count: 2);

        Assert.Empty(await EvaluateAsync(factory, new ThresholdStructuringAuditRule()));
    }

    /// <summary>Le schéma se lit par fournisseur : quatre fournisseurs différents ne le forment pas.</summary>
    [Fact]
    public async Task Structuring_does_not_aggregate_across_suppliers()
    {
        var factory = NewFactory("StructuringSpread");
        await SeedInBandInvoicesAsync(factory, count: 4, sameSupplier: false);

        Assert.Empty(await EvaluateAsync(factory, new ThresholdStructuringAuditRule()));
    }

    [Fact]
    public async Task Structuring_abstains_without_a_fiscal_year_threshold()
    {
        var factory = NewFactory("StructuringNoThreshold");
        await SeedInBandInvoicesAsync(factory, count: 4, withThreshold: false);

        Assert.Empty(await EvaluateAsync(factory, new ThresholdStructuringAuditRule()));
    }

    // ── Fournisseur créé puis réglé ───────────────────────────────────────────────────────

    private static async Task SeedSupplierPaymentAsync(TestTenantDbContextFactory factory, int delayDays)
    {
        await using var db = factory.CreateContext();

        // Tout le scénario est situé dans le passé : le domaine refuse un règlement daté du futur.
        var createdOn = DateTime.UtcNow.Date.AddDays(-90);

        var supplier = NewSupplier();
        supplier.SetAuditInfo("test", false);
        db.Suppliers.Add(supplier);

        // CreatedAt est posé par l'infrastructure et n'a pas de mutateur public : on l'ajuste par
        // le suivi de changements EF, seul moyen d'éprouver un délai réel de création à règlement.
        db.Entry(supplier).Property(nameof(FactuTrust.Domain.Common.Entity.CreatedAt)).CurrentValue = createdOn;

        var invoice = NewInvoice(db, supplier, "FA-001", createdOn, 500m);
        await db.SaveChangesAsync();

        var payment = SupplierPayment.Create(
            invoice, invoice.TotalAmount, createdOn.AddDays(delayDays),
            PaymentMethod.BankTransfer).Value;
        payment.SetAuditInfo("test", false);
        db.SupplierPayments.Add(payment);

        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task Supplier_paid_same_day_is_flagged()
    {
        var factory = NewFactory("SupplierSameDay");
        await SeedSupplierPaymentAsync(factory, delayDays: 0);

        var anomaly = Assert.Single(await EvaluateAsync(factory, new SupplierCreatedThenPaidAuditRule()));
        Assert.Contains("aussitôt", anomaly.Title);
    }

    [Fact]
    public async Task Supplier_paid_after_a_normal_delay_is_not_flagged()
    {
        var factory = NewFactory("SupplierDelayed");
        await SeedSupplierPaymentAsync(factory, delayDays: 30);

        Assert.Empty(await EvaluateAsync(factory, new SupplierCreatedThenPaidAuditRule()));
    }

    // ── Auto-validation ───────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Self_validation_flags_an_entry_validated_by_its_author()
    {
        var factory = NewFactory("SelfValidation");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1),
                isAutoGenerated: false, createdBy: "alice", validatedBy: "alice"));
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new SelfValidatedEntryAuditRule()));
        Assert.Contains("alice", anomaly.Lines[0].Label);
    }

    [Fact]
    public async Task Self_validation_is_silent_when_two_people_are_involved()
    {
        var factory = NewFactory("SelfValidationOk");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1),
                isAutoGenerated: false, createdBy: "alice", validatedBy: "bob"));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new SelfValidatedEntryAuditRule()));
    }

    /// <summary>
    /// Une écriture automatique est créée et validée par le système : la confusion y est
    /// structurelle. Ne pas l'exclure ferait remonter la quasi-totalité du journal.
    /// </summary>
    [Fact]
    public async Task Self_validation_ignores_system_generated_entries()
    {
        var factory = NewFactory("SelfValidationAuto");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1),
                isAutoGenerated: true, createdBy: "system", validatedBy: "system"));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new SelfValidatedEntryAuditRule()));
    }

    // ── Écriture antidatée ────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Backdated_flags_an_entry_recorded_long_after_the_operation()
    {
        var factory = NewFactory("Backdated");

        await using (var db = factory.CreateContext())
        {
            // Saisie aujourd'hui pour une opération de janvier : bien au-delà de 60 jours.
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 1, 5),
                isAutoGenerated: false, createdBy: "alice", validatedBy: "bob"));
            await db.SaveChangesAsync();
        }

        var found = await EvaluateAsync(factory, new BackdatedEntryAuditRule());

        // Le test ne vaut que si la date du jour est réellement postérieure de plus de 60 jours.
        if (DateTime.UtcNow.Date <= new DateTime(Year, 1, 5).AddDays(60)) return;

        var anomaly = Assert.Single(found);
        Assert.Contains("antidatées", anomaly.Title);
    }

    [Fact]
    public async Task Backdated_honours_the_tenant_threshold()
    {
        var factory = NewFactory("BackdatedThreshold");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 1, 5),
                isAutoGenerated: false, createdBy: "alice", validatedBy: "bob"));
            await db.SaveChangesAsync();
        }

        var tolerant = new AccountingControlRuleSetting
        {
            RuleCode = "backdated-entry",
            IsEnabled = true,
            IntThreshold = 100_000
        };

        Assert.Empty(await EvaluateAsync(factory, new BackdatedEntryAuditRule(), tolerant));
    }

    // ── Hors heures ouvrées ───────────────────────────────────────────────────────────────

    /// <summary>
    /// La règle lit <c>CreatedAt</c>, posé par l'infrastructure au moment de la sauvegarde : on ne
    /// peut pas le forcer depuis un test. On vérifie donc le comportement stable — la règle produit
    /// au plus une anomalie, de sévérité informative, et n'échoue jamais.
    /// </summary>
    [Fact]
    public async Task Off_hours_produces_at_most_one_informational_anomaly()
    {
        var factory = NewFactory("OffHours");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1),
                isAutoGenerated: false, createdBy: "alice", validatedBy: "bob"));
            await db.SaveChangesAsync();
        }

        var found = await EvaluateAsync(factory, new OffHoursEntryAuditRule());

        Assert.True(found.Count <= 1);
        foreach (var anomaly in found)
            Assert.Equal((int)PreClosingSeverity.Info, anomaly.Severity);
    }

    [Fact]
    public async Task Off_hours_ignores_system_generated_entries()
    {
        var factory = NewFactory("OffHoursAuto");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1),
                isAutoGenerated: true, createdBy: "system", validatedBy: "system"));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new OffHoursEntryAuditRule()));
    }
}
