using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.Configuration;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Audit;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Entities.AccountingAudit;
using FactuTrust.Domain.Enums;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Services;
using FactuTrust.Infrastructure.Services.AccountingAudit;
using FactuTrust.Infrastructure.Services.AccountingAudit.Rules;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.AccountingAudit;

/// <summary>
/// Famille « Trésorerie » du réviseur : caisse créditrice et encaissements sans justification.
/// </summary>
public sealed class TreasuryFamilyRulesTests
{
    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;

        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(_databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private const int Year = 2026;

    private static TestTenantDbContextFactory NewFactory(string label) => new($"{label}_{Guid.NewGuid()}");

    private static async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        TestTenantDbContextFactory factory, IAccountingAuditRule rule)
    {
        await using var db = factory.CreateContext();
        var ctx = new AuditEvaluationContextImpl(
            db, new AccountingSettings(), Year,
            new DateOnly(Year, 1, 1), new DateOnly(Year, 12, 31),
            Array.Empty<AccountingControlRuleSetting>(), moduleCodesFilter: null);
        return await rule.EvaluateAsync(ctx, CancellationToken.None);
    }

    private static JournalEntry Entry(
        int number, DateTime date, string? sourceType, params JournalLineInput[] lines)
    {
        var entry = JournalEntry.Create(
            number, "JB", date, $"Écriture {number}", Guid.NewGuid(),
            isAutoGenerated: sourceType is not null,
            sourceEntityType: sourceType,
            sourceEntityId: sourceType is null ? null : Guid.NewGuid(),
            lines,
            initialStatus: JournalEntryStatus.Validee).Value;
        entry.SetAuditInfo("test", false);
        return entry;
    }

    // ── Caisse créditrice ─────────────────────────────────────────────────────────────────

    [Fact]
    public async Task Cash_negative_is_silent_when_the_till_stays_positive()
    {
        var factory = NewFactory("CashOk");

        await using (var db = factory.CreateContext())
        {
            // Encaissement le 1er, sortie plus faible le 5 : la caisse ne passe jamais sous zéro.
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 3, 1), null,
                new JournalLineInput("5411", "Caisse", 500m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("707", "Vente", 0m, 500m, null, ThirdPartyKind.None)));
            db.JournalEntries.Add(Entry(2, new DateTime(Year, 3, 5), null,
                new JournalLineInput("607", "Achat", 200m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0m, 200m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashNegativeBalanceAuditRule()));
    }

    [Fact]
    public async Task Cash_negative_flags_a_till_going_below_zero()
    {
        var factory = NewFactory("CashNegative");

        await using (var db = factory.CreateContext())
        {
            // Sortie de 300 avant tout encaissement : la caisse est à découvert.
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 3, 1), null,
                new JournalLineInput("607", "Achat", 300m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0m, 300m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new CashNegativeBalanceAuditRule()));
        Assert.Equal((int)PreClosingSeverity.Blocking, anomaly.Severity);
        Assert.Equal(300m, anomaly.Amount);
        Assert.Equal("5411", anomaly.AccountRef);
    }

    /// <summary>
    /// Le contrôle porte sur le cumul chronologique, pas sur le solde de clôture : une caisse qui
    /// boucle au 31 décembre peut être passée en négatif dix fois dans l'année.
    /// </summary>
    [Fact]
    public async Task Cash_negative_detects_a_dip_even_when_the_year_end_balance_is_positive()
    {
        var factory = NewFactory("CashDip");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 3, 1), null,
                new JournalLineInput("607", "Achat", 300m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0m, 300m, null, ThirdPartyKind.None)));
            db.JournalEntries.Add(Entry(2, new DateTime(Year, 3, 10), null,
                new JournalLineInput("5411", "Caisse", 900m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("707", "Vente", 0m, 900m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Single(await EvaluateAsync(factory, new CashNegativeBalanceAuditRule()));
    }

    /// <summary>Le solde d'ouverture compte : sans lui, janvier paraîtrait à tort négatif.</summary>
    [Fact]
    public async Task Cash_negative_takes_the_opening_balance_into_account()
    {
        var factory = NewFactory("CashOpening");

        await using (var db = factory.CreateContext())
        {
            // Exercice précédent : la caisse est alimentée.
            db.JournalEntries.Add(Entry(1, new DateTime(Year - 1, 12, 20), null,
                new JournalLineInput("5411", "Caisse", 1000m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("707", "Vente", 0m, 1000m, null, ThirdPartyKind.None)));
            // Exercice courant : sortie couverte par le report.
            db.JournalEntries.Add(Entry(2, new DateTime(Year, 1, 5), null,
                new JournalLineInput("607", "Achat", 400m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0m, 400m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashNegativeBalanceAuditRule()));
    }

    /// <summary>Un compte bancaire peut être à découvert : la règle ne vise que la caisse.</summary>
    [Fact]
    public async Task Cash_negative_ignores_bank_accounts()
    {
        var factory = NewFactory("CashBank");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 3, 1), null,
                new JournalLineInput("607", "Achat", 300m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5321", "Banque", 0m, 300m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashNegativeBalanceAuditRule()));
    }

    [Fact]
    public async Task Cash_negative_separates_two_tills()
    {
        var factory = NewFactory("CashTwoTills");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 3, 1), null,
                new JournalLineInput("607", "Achat", 100m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse A", 0m, 100m, null, ThirdPartyKind.None)));
            db.JournalEntries.Add(Entry(2, new DateTime(Year, 3, 2), null,
                new JournalLineInput("607", "Achat", 200m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5412", "Caisse B", 0m, 200m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        var found = await EvaluateAsync(factory, new CashNegativeBalanceAuditRule());

        Assert.Equal(2, found.Count);
        Assert.Equal(2, found.Select(f => f.Fingerprint).Distinct().Count());
    }

    // ── Encaissement sans justification ───────────────────────────────────────────────────

    [Fact]
    public async Task Cash_in_without_document_flags_an_unexplained_receipt()
    {
        var factory = NewFactory("CashInOrphan");

        await using (var db = factory.CreateContext())
        {
            // Entrée en banque sans document source, sans tiers, sans lettrage.
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1), null,
                new JournalLineInput("5321", "Banque", 800m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("758", "Produit divers", 0m, 800m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        var anomaly = Assert.Single(await EvaluateAsync(factory, new CashInWithoutDocumentAuditRule()));
        Assert.Equal(800m, anomaly.Amount);
    }

    [Fact]
    public async Task Cash_in_without_document_accepts_an_entry_bound_to_a_payment()
    {
        var factory = NewFactory("CashInPayment");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1), AccountingService.SourcePayment,
                new JournalLineInput("5321", "Banque", 800m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("4111", "Client", 0m, 800m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashInWithoutDocumentAuditRule()));
    }

    [Fact]
    public async Task Cash_in_without_document_accepts_a_lettered_client_counterpart()
    {
        var factory = NewFactory("CashInLettered");

        await using (var db = factory.CreateContext())
        {
            var entry = Entry(1, new DateTime(Year, 4, 1), null,
                new JournalLineInput("5321", "Banque", 800m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("4111", "Client", 0m, 800m, null, ThirdPartyKind.None));
            db.JournalEntries.Add(entry);
            await db.SaveChangesAsync();

            var clientLine = entry.Lines.First(l => l.AccountNumber == "4111");
            clientLine.SetLetteringCode("AA0001");
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashInWithoutDocumentAuditRule()));
    }

    [Fact]
    public async Task Cash_in_without_document_accepts_an_entry_carrying_a_third_party()
    {
        var factory = NewFactory("CashInThirdParty");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1), null,
                new JournalLineInput("5321", "Banque", 800m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("4111", "Client", 0m, 800m, Guid.NewGuid(), ThirdPartyKind.Client)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashInWithoutDocumentAuditRule()));
    }

    /// <summary>Un virement interne 58x ne crée aucune richesse : il ne doit pas être signalé.</summary>
    [Fact]
    public async Task Cash_in_without_document_ignores_internal_transfers()
    {
        var factory = NewFactory("CashInTransfer");

        await using (var db = factory.CreateContext())
        {
            db.JournalEntries.Add(Entry(1, new DateTime(Year, 4, 1), null,
                new JournalLineInput("581", "Virement interne", 500m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0m, 500m, null, ThirdPartyKind.None)));
            await db.SaveChangesAsync();
        }

        Assert.Empty(await EvaluateAsync(factory, new CashInWithoutDocumentAuditRule()));
    }
}
