using FactuTrust.Domain.Common;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.ValueObjects;

namespace FactuTrust.Domain.Entities;

/// <param name="Debit">Montant au débit, TOUJOURS en devise de tenue.</param>
/// <param name="Credit">Montant au crédit, TOUJOURS en devise de tenue.</param>
/// <param name="DebitInCurrency">
/// Montant au débit dans la devise de transaction. Renseigné uniquement par le chemin multi-devises,
/// qui a déjà converti <paramref name="Debit"/>. Reste à 0 en mono-devise.
/// </param>
/// <param name="CreditInCurrency">Idem pour le crédit.</param>
public readonly record struct JournalLineInput(
    string AccountNumber,
    string Label,
    decimal Debit,
    decimal Credit,
    Guid? ThirdPartyId,
    ThirdPartyKind ThirdPartyKind,
    decimal DebitInCurrency = 0m,
    decimal CreditInCurrency = 0m);

/// <summary>
/// Accounting journal entry (piece) with balanced lines.
/// </summary>
public sealed class JournalEntry : AggregateRoot
{
    public int EntryNumber { get; private set; }
    public string JournalCode { get; private set; } = null!;
    public DateTime EntryDate { get; private set; }
    public string Label { get; private set; } = null!;
    public string? SourceEntityType { get; private set; }
    public Guid? SourceEntityId { get; private set; }
    public bool IsAutoGenerated { get; private set; }
    public Guid AccountingPeriodId { get; private set; }
    public AccountingPeriod? AccountingPeriod { get; private set; }
    public bool IsReversed { get; private set; }
    public Guid? ReversedByEntryId { get; private set; }
    public Guid? ReversesEntryId { get; private set; }

    /// <summary>Statut du cycle de vie (brouillard → validation → clôture). Cf. <see cref="JournalEntryStatus"/>.</summary>
    public JournalEntryStatus Status { get; private set; } = JournalEntryStatus.Validee;
    public DateTime? ValidatedAt { get; private set; }
    public string? ValidatedBy { get; private set; }

    /// <summary>Référence de la pièce externe justificative (n° facture fournisseur, chèque…). Facultative, ≤ 50 caractères.</summary>
    public string? PieceRef { get; private set; }

    /// <summary>Date de la pièce externe, distincte de la date comptable. Facultative.</summary>
    public DateTime? PieceDate { get; private set; }

    /// <summary>
    /// Devise dans laquelle l'opération a été traitée. Vaut la devise de tenue
    /// (<see cref="Money.DefaultCurrency"/>) pour toute écriture mono-devise, donc pour la totalité
    /// de l'existant. Les montants comptables restent quant à eux <b>toujours</b> exprimés en devise
    /// de tenue : voir le garde-fou de <see cref="BuildLines"/>.
    /// </summary>
    public string CurrencyCode { get; private set; } = Money.DefaultCurrency;

    /// <summary>
    /// Taux appliqué pour convertir les montants en devise de tenue : unités de devise de tenue pour
    /// UNE unité de devise de transaction. Vaut 1 pour une écriture en devise de tenue.
    /// </summary>
    public decimal ExchangeRate { get; private set; } = 1m;

    /// <summary>
    /// Vrai si le taux a été saisi manuellement au lieu d'être repris de la table des taux. La
    /// surcharge exige une permission dédiée et laisse une trace d'audit.
    /// </summary>
    public bool ExchangeRateOverridden { get; private set; }

    private readonly List<JournalEntryLine> _lines = new();
    public IReadOnlyCollection<JournalEntryLine> Lines => _lines.AsReadOnly();

    /// <summary>Vrai si l'écriture est un brouillon (donc modifiable / supprimable).</summary>
    public bool IsDraft => Status == JournalEntryStatus.Brouillon;

    private JournalEntry() { }

    public static Result<JournalEntry> Create(
        int entryNumber,
        string journalCode,
        DateTime entryDate,
        string label,
        Guid accountingPeriodId,
        bool isAutoGenerated,
        string? sourceEntityType,
        Guid? sourceEntityId,
        IReadOnlyList<JournalLineInput> lineInputs,
        string currency = Money.DefaultCurrency,
        Guid? reversesEntryId = null,
        JournalEntryStatus initialStatus = JournalEntryStatus.Validee,
        string? pieceRef = null,
        DateTime? pieceDate = null,
        decimal? exchangeRate = null,
        bool exchangeRateOverridden = false)
    {
        journalCode = journalCode?.Trim().ToUpperInvariant() ?? string.Empty;
        if (string.IsNullOrEmpty(journalCode))
            return Result.Failure<JournalEntry>(Error.Validation("JournalCode", "Le journal est obligatoire"));

        label = label?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(label))
            return Result.Failure<JournalEntry>(Error.Validation("Label", "Le libellé est obligatoire"));

        var pieceResult = NormalizePieceRef(pieceRef);
        if (pieceResult.IsFailure)
            return Result.Failure<JournalEntry>(pieceResult.Error);

        var linesResult = BuildLines(label, lineInputs, currency, exchangeRate);
        if (linesResult.IsFailure)
            return Result.Failure<JournalEntry>(linesResult.Error);

        var entry = new JournalEntry
        {
            EntryNumber = entryNumber,
            JournalCode = journalCode,
            EntryDate = entryDate.Date,
            Label = label,
            SourceEntityType = sourceEntityType,
            SourceEntityId = sourceEntityId,
            IsAutoGenerated = isAutoGenerated,
            AccountingPeriodId = accountingPeriodId,
            IsReversed = false,
            ReversesEntryId = reversesEntryId,
            Status = initialStatus,
            PieceRef = pieceResult.Value,
            PieceDate = pieceDate?.Date,
            CurrencyCode = NormalizeCurrency(currency),
            ExchangeRate = exchangeRate ?? 1m,
            ExchangeRateOverridden = exchangeRateOverridden
        };

        foreach (var line in linesResult.Value)
        {
            line.AttachToEntry(entry);
            entry._lines.Add(line);
        }

        return Result.Success(entry);
    }

    /// <summary>
    /// Construit et valide les lignes équilibrées d'une écriture (partagé entre la création et la
    /// mise à jour d'un brouillon).
    /// </summary>
    /// <summary>Normalise un code devise ; une valeur vide vaut la devise de tenue.</summary>
    private static string NormalizeCurrency(string? currency)
    {
        var normalized = currency?.Trim().ToUpperInvariant() ?? string.Empty;
        return normalized.Length == 0 ? Money.DefaultCurrency : normalized;
    }

    private static Result<List<JournalEntryLine>> BuildLines(
        string label,
        IReadOnlyList<JournalLineInput> lineInputs,
        string currency,
        decimal? exchangeRate)
    {
        if (lineInputs.Count < 2)
            return Result.Failure<List<JournalEntryLine>>(Error.Validation("Lines", "Au moins deux lignes sont requises"));

        // La comptabilité est tenue en devise fonctionnelle : DebitAmount / CreditAmount sont
        // TOUJOURS exprimés dans cette devise. Tous les agrégats de restitution (grand livre,
        // balance, bilan, compte de résultat, états NCT, balance âgée, FEC) somment .Amount SANS
        // convertir : accepter ici des montants en euros les ferait additionner à des dinars.
        //
        // Le taux est le témoin explicite que l'appelant a converti. Il n'est renseigné que par le
        // chemin multi-devises ; les quelque trente générations automatiques qui propagent la devise
        // du document source (AccountingService : `var currency = invoice.TotalAmount.Currency;`)
        // n'en passent aucun et restent donc refusées — c'est ce qui empêche une facture en euros
        // d'entrer en comptabilité comme si elle était en dinars.
        currency = NormalizeCurrency(currency);
        if (currency != Money.DefaultCurrency && exchangeRate is null)
        {
            return Result.Failure<List<JournalEntryLine>>(Error.Validation(
                "Currency",
                $"La comptabilité est tenue en {Money.DefaultCurrency}. Une pièce en {currency} ne peut pas être "
                + "comptabilisée sans taux de change."));
        }

        if (exchangeRate is not null and <= 0)
        {
            return Result.Failure<List<JournalEntryLine>>(Error.Validation(
                "ExchangeRate", "Le taux de change doit être strictement positif."));
        }

        decimal sumDebit = 0, sumCredit = 0;
        var lines = new List<JournalEntryLine>();
        var n = 1;
        foreach (var li in lineInputs)
        {
            var acc = li.AccountNumber?.Trim() ?? string.Empty;
            if (string.IsNullOrEmpty(acc))
                return Result.Failure<List<JournalEntryLine>>(Error.Validation("AccountNumber", "Compte obligatoire"));

            if (li.Debit < 0 || li.Credit < 0)
                return Result.Failure<List<JournalEntryLine>>(Error.Validation("Amount", "Les montants doivent être positifs ou nuls"));

            if (li.Debit > 0 && li.Credit > 0)
                return Result.Failure<List<JournalEntryLine>>(Error.Validation("Amount", "Une ligne ne peut pas avoir débit et crédit simultanément"));

            if (li.Debit == 0 && li.Credit == 0)
                return Result.Failure<List<JournalEntryLine>>(Error.Validation("Amount", "Chaque ligne doit avoir un débit ou un crédit"));

            var debit = Money.Create(li.Debit, currency);
            var credit = Money.Create(li.Credit, currency);
            sumDebit += li.Debit;
            sumCredit += li.Credit;

            if (li.DebitInCurrency < 0 || li.CreditInCurrency < 0)
                return Result.Failure<List<JournalEntryLine>>(Error.Validation("Amount", "Les montants en devise doivent être positifs ou nuls"));

            var lineLabel = string.IsNullOrWhiteSpace(li.Label) ? label : li.Label.Trim();
            lines.Add(JournalEntryLine.Create(n++, acc, lineLabel, debit, credit, li.ThirdPartyId, li.ThirdPartyKind,
                li.DebitInCurrency, li.CreditInCurrency));
        }

        // TND uses 3 decimal places (millimes). Round to 3 decimals before comparing
        // to avoid floating-point drift, then require exact equality.
        var roundedDebit = Math.Round(sumDebit, 3);
        var roundedCredit = Math.Round(sumCredit, 3);
        if (roundedDebit != roundedCredit)
            return Result.Failure<List<JournalEntryLine>>(Error.Validation("Balance", "L'écriture n'est pas équilibrée (débit ≠ crédit)"));

        return Result.Success(lines);
    }

    /// <summary>
    /// Valide un brouillon : l'écriture devient définitive et immuable. Idempotent si déjà validée ;
    /// refusé si l'écriture appartient à une période clôturée.
    /// </summary>
    public Result Validate(string validatedBy)
    {
        if (Status == JournalEntryStatus.Cloturee)
            return Result.Failure(Error.Validation("Status", "Une écriture clôturée ne peut pas être validée."));
        if (Status == JournalEntryStatus.Validee)
            return Result.Success();

        Status = JournalEntryStatus.Validee;
        ValidatedAt = DateTime.UtcNow;
        ValidatedBy = validatedBy;
        return Result.Success();
    }

    /// <summary>
    /// Remplace le libellé et les lignes d'un brouillon (revalide l'équilibre). Interdit si l'écriture
    /// n'est pas un brouillon.
    /// </summary>
    public Result UpdateDraftLines(
        string label,
        IReadOnlyList<JournalLineInput> lineInputs,
        string currency = Money.DefaultCurrency,
        string? pieceRef = null,
        DateTime? pieceDate = null,
        decimal? exchangeRate = null,
        bool exchangeRateOverridden = false)
    {
        if (Status != JournalEntryStatus.Brouillon)
            return Result.Failure(Error.Validation("Status", "Seule une écriture en brouillon peut être modifiée."));

        label = label?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(label))
            return Result.Failure(Error.Validation("Label", "Le libellé est obligatoire"));

        var pieceResult = NormalizePieceRef(pieceRef);
        if (pieceResult.IsFailure)
            return Result.Failure(pieceResult.Error);

        var linesResult = BuildLines(label, lineInputs, currency, exchangeRate);
        if (linesResult.IsFailure)
            return Result.Failure(linesResult.Error);

        Label = label;
        PieceRef = pieceResult.Value;
        PieceDate = pieceDate?.Date;
        CurrencyCode = NormalizeCurrency(currency);
        ExchangeRate = exchangeRate ?? 1m;
        ExchangeRateOverridden = exchangeRateOverridden;
        _lines.Clear();
        foreach (var line in linesResult.Value)
        {
            line.AttachToEntry(this);
            _lines.Add(line);
        }

        return Result.Success();
    }

    /// <summary>
    /// Change le code journal d'un BROUILLON (édition de masse post-import). Interdit hors brouillon.
    /// Ne valide pas l'existence du journal (responsabilité de la couche applicative / catalogue).
    /// </summary>
    public Result ChangeDraftJournal(string journalCode)
    {
        if (Status != JournalEntryStatus.Brouillon)
            return Result.Failure(Error.Validation("Status", "Seule une écriture en brouillon peut être modifiée."));

        journalCode = journalCode?.Trim().ToUpperInvariant() ?? string.Empty;
        if (string.IsNullOrEmpty(journalCode))
            return Result.Failure(Error.Validation("JournalCode", "Le journal est obligatoire"));

        JournalCode = journalCode;
        return Result.Success();
    }

    /// <summary>
    /// Change la date d'un BROUILLON et la rattache à la période fournie (à charge de l'appelant de
    /// fournir une période OUVERTE couvrant la nouvelle date). Interdit hors brouillon.
    /// </summary>
    public Result ChangeDraftDate(DateTime date, Guid accountingPeriodId)
    {
        if (Status != JournalEntryStatus.Brouillon)
            return Result.Failure(Error.Validation("Status", "Seule une écriture en brouillon peut être modifiée."));
        if (accountingPeriodId == Guid.Empty)
            return Result.Failure(Error.Validation("Period", "La période comptable est obligatoire."));

        EntryDate = date.Date;
        AccountingPeriodId = accountingPeriodId;
        return Result.Success();
    }

    /// <summary>Change le libellé d'un BROUILLON (n'affecte pas les lignes). Interdit hors brouillon.</summary>
    public Result ChangeDraftLabel(string label)
    {
        if (Status != JournalEntryStatus.Brouillon)
            return Result.Failure(Error.Validation("Status", "Seule une écriture en brouillon peut être modifiée."));

        label = label?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(label))
            return Result.Failure(Error.Validation("Label", "Le libellé est obligatoire"));

        Label = label;
        return Result.Success();
    }

    /// <summary>Normalise la référence de pièce (trim, vide → null, ≤ 50 caractères).</summary>
    private static Result<string?> NormalizePieceRef(string? pieceRef)
    {
        var trimmed = pieceRef?.Trim();
        if (string.IsNullOrEmpty(trimmed))
            return Result.Success<string?>(null);
        if (trimmed.Length > 50)
            return Result.Failure<string?>(Error.Validation("PieceRef", "La référence de pièce ne peut pas dépasser 50 caractères."));
        return Result.Success<string?>(trimmed);
    }

    /// <summary>
    /// Applique le statut initial (brouillard ou validé) à une écriture qui vient d'être créée, avant
    /// sa persistance. Utilisé par la génération automatique/manuelle selon le flag brouillard.
    /// Sans effet sur une écriture clôturée (garde défensive).
    /// </summary>
    public void MarkInitialStatus(JournalEntryStatus status)
    {
        if (Status == JournalEntryStatus.Cloturee)
            return;
        Status = status;
    }

    public void MarkReversedBy(Guid reversingEntryId)
    {
        IsReversed = true;
        ReversedByEntryId = reversingEntryId;
    }

    /// <summary>
    /// Annule le marquage d'extourne (C5) : quand le brouillon d'extourne est supprimé avant
    /// validation, l'écriture d'origine doit redevenir extournable — sinon elle resterait
    /// verrouillée avec un <see cref="ReversedByEntryId"/> orphelin.
    /// </summary>
    public void ClearReversalMark()
    {
        IsReversed = false;
        ReversedByEntryId = null;
    }

    /// <summary>
    /// Verrouille une écriture validée lors de la clôture de sa période (Validee → Cloturee).
    /// Sans effet sur un brouillon (la clôture est refusée tant qu'il en reste) ou une écriture
    /// déjà clôturée.
    /// </summary>
    public void MarkPeriodClosed()
    {
        if (Status == JournalEntryStatus.Validee)
            Status = JournalEntryStatus.Cloturee;
    }

    /// <summary>
    /// Déverrouille une écriture clôturée lors de la réouverture de sa période
    /// (Cloturee → Validee). Sans effet sur les autres statuts.
    /// </summary>
    public void MarkPeriodReopened()
    {
        if (Status == JournalEntryStatus.Cloturee)
            Status = JournalEntryStatus.Validee;
    }
}
