import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { DOCUMENT } from '@angular/common';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';
import { provideRouter } from '@angular/router';
import { signal } from '@angular/core';
import { of } from 'rxjs';
import { JournalComponent } from './journal.component';
import { AccountingService } from '../services/accounting.service';
import { AccountingMonitoringService } from '../shared/accounting-monitoring.service';
import { AuthService } from '@core/services/auth.service';
import { ConfirmationService } from '@core/services/confirmation.service';

function mockAccountingService(): AccountingService {
  return {
    getJournal: () =>
      of({
        success: true,
        data: [
          {
            id: 'entry-1',
            entryDate: '2026-01-15',
            journalCode: 'JV',
            entryNumber: 1,
            label: 'Test',
            status: 0,
            isDraft: true,
            isReversed: false,
            isAutoGenerated: false,
            reversesEntryId: null,
            pieceRef: null,
            attachmentCount: 0,
            lines: [{ id: 'line-1', lineNumber: 1, label: 'Ligne', accountNumber: '411', debit: 100, credit: 0, currency: 'TND' }]
          }
        ]
      }),
    exportJournal: () => of(new Blob()),
    validateJournalEntry: () => of({ success: true }),
    reverseJournalEntry: () => of({ success: true }),
    deleteDraftJournalEntry: () => of({ success: true }),
    // Catalogue de journaux : vide ici, le sélecteur retombe sur les journaux standards.
    getJournals: () => of({ success: true, data: [] }),
    getJournalEntryAttachments: () => of({ success: true, data: [] }),
    uploadJournalEntryAttachment: () => of({ success: true }),
    deleteJournalEntryAttachment: () => of({ success: true }),
    downloadJournalEntryAttachment: () => of(new Blob())
  } as unknown as AccountingService;
}

function mockAuthService(overrides: {
  hasPermission?: (p: string) => boolean;
  isFirmManager?: boolean;
  isFirmAccountant?: boolean;
  isAccountingFirm?: boolean;
  isDelegatedMode?: boolean;
} = {}): AuthService {
  return {
    hasAllPermissions: () => true,
    hasPermission: overrides.hasPermission ?? (() => true),
    isAccountingFirm: () => overrides.isAccountingFirm ?? true,
    isDelegatedMode: () => overrides.isDelegatedMode ?? true,
    isFirmManager: () => overrides.isFirmManager ?? true,
    isFirmAccountant: () => overrides.isFirmAccountant ?? false,
    user: signal(null)
  } as unknown as AuthService;
}

async function setupFixture(authOverrides: Parameters<typeof mockAuthService>[0] = {}) {
  const confirmationSpy = jasmine.createSpyObj<ConfirmationService>('ConfirmationService', ['confirm']);
  confirmationSpy.confirm.and.callFake((cfg: { accept?: () => void }) => cfg.accept?.());

  await TestBed.configureTestingModule({
    imports: [JournalComponent],
    providers: [
      provideNoopAnimations(),
      { provide: DOCUMENT, useValue: document },
      provideHttpClient(),
      provideHttpClientTesting(),
      provideRouter([]),
      { provide: AccountingService, useValue: mockAccountingService() },
      { provide: AccountingMonitoringService, useValue: { logError: jasmine.createSpy('logError') } },
      { provide: AuthService, useValue: mockAuthService(authOverrides) },
      { provide: ConfirmationService, useValue: confirmationSpy }
    ]
  }).compileComponents();
  const fixture = TestBed.createComponent(JournalComponent);
  fixture.detectChanges();
  return fixture;
}

describe('JournalComponent', () => {
  describe('with delegated firm manager', () => {
    let fixture: ComponentFixture<JournalComponent>;

    beforeEach(async () => {
      fixture = await setupFixture({ isFirmManager: true });
    });

    it('renders validate and attachment actions for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      expect(el.textContent).toContain('Valider');
      expect(el.querySelector('app-accounting-table-actions')).toBeTruthy();
      expect(el.querySelectorAll('app-button').length).toBeGreaterThan(2);
    });

    it('renders delete action for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let found = false;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Supprimer')) {
          found = true;
          break;
        }
      }
      expect(found).toBe(true);
    });

    it('renders edit action for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let found = false;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Modifier')) {
          found = true;
          break;
        }
      }
      expect(found).toBe(true);
    });

    it('calls deleteDraftJournalEntry when delete button is clicked', () => {
      const service = TestBed.inject(AccountingService) as jasmine.SpyObj<AccountingService>;
      const spy = spyOn(service, 'deleteDraftJournalEntry').and.returnValue(of({ success: true }));
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let deleteBtn: Element | null = null;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Supprimer')) {
          deleteBtn = btn;
          break;
        }
      }
      expect(deleteBtn).toBeTruthy();
      (deleteBtn as HTMLElement).click();
      expect(spy).toHaveBeenCalledWith('entry-1');
    });

    it('renders harmonized toolbar actions', () => {
      const el = fixture.nativeElement as HTMLElement;
      expect(el.textContent).toContain('Actualiser');
      expect(el.textContent).toContain('Exporter');
      expect(el.querySelector('app-accounting-toolbar-actions')).toBeTruthy();
    });
  });

  describe('with delegated firm manager lacking delete permission', () => {
    let fixture: ComponentFixture<JournalComponent>;

    beforeEach(async () => {
      fixture = await setupFixture({
        isFirmManager: true,
        hasPermission: (p: string) => p !== 'accounting:delete'
      });
    });

    it('hides delete action for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let found = false;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Supprimer')) {
          found = true;
          break;
        }
      }
      expect(found).toBe(false);
    });
  });

  describe('with delegated assigned accountant', () => {
    let fixture: ComponentFixture<JournalComponent>;

    beforeEach(async () => {
      fixture = await setupFixture({ isFirmManager: false, isFirmAccountant: true });
    });

    it('renders delete action for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let found = false;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Supprimer')) {
          found = true;
          break;
        }
      }
      expect(found).toBe(true);
    });
  });

  describe('with company user', () => {
    let fixture: ComponentFixture<JournalComponent>;

    beforeEach(async () => {
      fixture = await setupFixture({
        isAccountingFirm: false,
        isDelegatedMode: false,
        isFirmManager: false
      });
    });

    it('hides edit action for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let found = false;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Modifier')) {
          found = true;
          break;
        }
      }
      expect(found).toBe(false);
    });
  });

  describe('with delegated firm lacking create permission', () => {
    let fixture: ComponentFixture<JournalComponent>;

    beforeEach(async () => {
      fixture = await setupFixture({
        isFirmManager: true,
        hasPermission: (p: string) => p !== 'accounting:create'
      });
    });

    it('hides edit action for draft entries', () => {
      const el = fixture.nativeElement as HTMLElement;
      const buttons = el.querySelectorAll('app-button');
      let found = false;
      for (const btn of Array.from(buttons)) {
        if (btn.getAttribute('aria-label')?.includes('Modifier')) {
          found = true;
          break;
        }
      }
      expect(found).toBe(false);
    });
  });
});
