import { TestBed } from '@angular/core/testing';
import { EntryFormStore } from './entry-form.store';
import { createEmptyLine } from '../models/entry-form.model';
import { JournalEntryDto } from '../../services/accounting.service';

/** Le cas exact du ticket : 1 000 EUR au debit, 1 000 au credit, taux 3,29. */
function foreignEntry(overrides: Partial<JournalEntryDto> = {}): JournalEntryDto {
  return {
    id: 'e-1',
    entryNumber: 12,
    journalCode: 'JOD',
    entryDate: '2026-09-12T00:00:00',
    label: 'Ecriture EUR',
    isAutoGenerated: false,
    isReversed: false,
    status: 0,
    isDraft: true,
    attachmentCount: 0,
    currencyCode: 'EUR',
    exchangeRate: 3.29,
    exchangeRateOverridden: false,
    lines: [
      { id: 'l1', lineNumber: 1, accountNumber: '164', label: 'Emprunt', debit: 3290, credit: 0,
        currency: 'TND', debitInCurrency: 1000, creditInCurrency: 0 },
      { id: 'l2', lineNumber: 2, accountNumber: '452', label: 'Associes', debit: 0, credit: 3290,
        currency: 'TND', debitInCurrency: 0, creditInCurrency: 1000 }
    ],
    ...overrides
  };
}

/**
 * Multi-devises, lot 2 : état et payload côté saisie.
 *
 * Les montants saisis sont exprimés dans la devise de l'écriture. En devise de tenue, tout doit
 * rester rigoureusement identique au comportement d'avant le chantier — c'est ce que verrouille la
 * première série de tests.
 */
describe('EntryFormStore — multi-devises', () => {
  let store: EntryFormStore;

  beforeEach(() => {
    TestBed.configureTestingModule({ providers: [EntryFormStore] });
    store = TestBed.inject(EntryFormStore);
    store.entryLabel.set('Test');
    store.lines.set([
      { ...createEmptyLine(), accountNumber: '607', debit: 1000, credit: null },
      { ...createEmptyLine(), accountNumber: '4011', debit: null, credit: 1000 }
    ]);
  });

  describe('devise de tenue (comportement historique)', () => {
    it('démarre en TND, sans taux', () => {
      expect(store.currency()).toBe('TND');
      expect(store.isForeignCurrency()).toBeFalse();
      expect(store.exchangeRate()).toBeNull();
    });

    it('les totaux en devise de tenue sont les totaux saisis', () => {
      expect(store.localTotals()).toEqual(store.totals());
      expect(store.localBalance()).toBe(store.balance());
    });

    it('la contre-valeur est l’identité', () => {
      expect(store.toLocalAmount(1000)).toBe(1000);
    });

    it('le payload porte les montants en dinar et rien en devise', () => {
      const line = store.mapLineToRequest(store.lines()[0], 'Test');

      expect(line.debit).toBe(1000);
      expect(line.debitInCurrency).toBe(0);
      expect(line.creditInCurrency).toBe(0);
    });

    it('la requête n’envoie aucun taux', () => {
      expect(store.buildCreateRequest().request.exchangeRate).toBeNull();
      expect(store.buildCreateRequest().request.currencyCode).toBe('TND');
    });
  });

  describe('devise étrangère', () => {
    beforeEach(() => {
      store.currency.set('EUR');
      store.currencyDecimals.set(2);
      store.exchangeRate.set(3.3142);
    });

    it('bascule les colonnes en devise', () => {
      expect(store.isForeignCurrency()).toBeTrue();
    });

    it('l’équilibre s’apprécie sur les montants saisis', () => {
      // 1 000 EUR au débit et au crédit : équilibré, quel que soit le taux.
      expect(store.isBalanced()).toBeTrue();
      expect(store.balance()).toBe(0);
    });

    it('la contre-valeur multiplie par le taux', () => {
      // Le sens du taux est l'erreur classique : 1 000 EUR font 3 314,200 TND.
      expect(store.toLocalAmount(1000)).toBe(3314.2);
    });

    it('les totaux en dinar sont convertis', () => {
      expect(store.localTotals()).toEqual({ debit: 3314.2, credit: 3314.2 });
      expect(store.localBalance()).toBe(0);
    });

    it('sans taux résolu, aucune contre-valeur n’est affichée', () => {
      store.exchangeRate.set(null);

      expect(store.toLocalAmount(1000)).toBeNull();
      expect(store.localTotals()).toEqual({ debit: 0, credit: 0 });
    });

    it('le payload envoie les montants en devise et laisse le dinar au serveur', () => {
      const debitLine = store.mapLineToRequest(store.lines()[0], 'Test');
      const creditLine = store.mapLineToRequest(store.lines()[1], 'Test');

      expect(debitLine.debitInCurrency).toBe(1000);
      expect(debitLine.debit).toBe(0);
      expect(creditLine.creditInCurrency).toBe(1000);
      expect(creditLine.credit).toBe(0);
    });

    it('la requête porte la devise et le taux', () => {
      const request = store.buildCreateRequest().request;

      expect(request.currencyCode).toBe('EUR');
      expect(request.exchangeRate).toBe(3.3142);
    });

    it('la requête de modification porte aussi la devise et le taux', () => {
      const request = store.buildUpdateRequest().request;

      expect(request.currencyCode).toBe('EUR');
      expect(request.exchangeRate).toBe(3.3142);
    });
  });

  describe('format d’affichage', () => {
    it('est au millime en devise de tenue', () => {
      expect(store.amountFormat()).toBe('1.3-3');
    });

    it('suit les décimales de la devise étrangère', () => {
      store.currency.set('EUR');
      store.currencyDecimals.set(2);

      expect(store.amountFormat()).toBe('1.2-2');
    });
  });

  /**
   * Rouvrir une écriture en devise perdait sa devise, son taux et ses montants : la grille
   * recevait les montants en dinar comme s'ils avaient été saisis, et l'enregistrement reposait
   * l'écriture en dinar. Rien ne le signalait à l'écran.
   */
  describe('rechargement d’une écriture', () => {
    it('restaure la devise et le taux de l’écriture', () => {
      store.loadFromEntry(foreignEntry());

      expect(store.currency()).toBe('EUR');
      expect(store.exchangeRate()).toBe(3.29);
      expect(store.isForeignCurrency()).toBeTrue();
    });

    it('charge les montants EN DEVISE, jamais la contre-valeur en dinar', () => {
      store.loadFromEntry(foreignEntry());

      expect(store.lines()[0].debit).toBe(1000);
      expect(store.lines()[1].credit).toBe(1000);
      // 3 290 est la contre-valeur : la voir ici signifierait que le défaut est revenu.
      expect(store.totals()).toEqual({ debit: 1000, credit: 1000 });
      expect(store.isBalanced()).toBeTrue();
    });

    it('repose l’écriture dans sa devise, avec le taux enregistré', () => {
      store.loadFromEntry(foreignEntry());

      const { request } = store.buildUpdateRequest();

      expect(request.currencyCode).toBe('EUR');
      expect(request.exchangeRate).toBe(3.29);
      expect(request.lines[0].debitInCurrency).toBe(1000);
      // Le dinar est laissé au serveur, qui le recalcule depuis le taux qu'il résout.
      expect(request.lines[0].debit).toBe(0);
    });

    it('laisse une écriture en devise de tenue rigoureusement inchangée', () => {
      store.loadFromEntry(foreignEntry({
        currencyCode: undefined,
        exchangeRate: undefined,
        lines: [
          { id: 'l1', lineNumber: 1, accountNumber: '607', label: 'Achat', debit: 100, credit: 0, currency: 'TND' },
          { id: 'l2', lineNumber: 2, accountNumber: '4011', label: 'Fournisseur', debit: 0, credit: 100, currency: 'TND' }
        ]
      }));

      expect(store.currency()).toBe('TND');
      expect(store.exchangeRate()).toBeNull();
      expect(store.lines()[0].debit).toBe(100);
      expect(store.buildUpdateRequest().request.exchangeRate).toBeNull();
    });

    it('revient en devise de tenue quand l’écriture suivante n’est pas en devise', () => {
      store.loadFromEntry(foreignEntry());
      expect(store.currency()).toBe('EUR');

      store.loadFromEntry(foreignEntry({ currencyCode: 'TND', exchangeRate: undefined }));

      expect(store.currency()).toBe('TND');
      expect(store.exchangeRate()).toBeNull();
    });
  });
});
