import { Component, DestroyRef, HostListener, OnInit, computed, effect, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { CommonModule } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { TabsModule } from 'primeng/tabs';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';
import {
  AccountingService,
  CreateJournalEntryTemplateRequest,
  JournalEntryTemplateDto
} from '../services/accounting.service';
import { ToastService } from '@core/services/toast.service';
import { ConfirmationService } from '@core/services/confirmation.service';
import { AnalyzeWithAiButtonComponent } from '@features/ai-assistant/components/analyze-with-ai-button/analyze-with-ai-button.component';
import { wrapLegacyAnalyzePayload } from '@features/ai-assistant/utils/ai-screen-payload.factory';
import { DraftBannerComponent } from './components/draft-banner.component';
import { TemplatePickerModalComponent } from './components/template-picker-modal.component';
import { SaveTemplateModalComponent, SaveTemplatePayload } from './components/save-template-modal.component';
import { ManualEntryDraft, ManualEntryDraftService } from './services/manual-entry-draft.service';
import { EntryFormStore } from './services/entry-form.store';
import { EntryReferenceStore } from './services/entry-reference.store';
import { EntrySubmitService } from './services/entry-submit.service';
import { VatAssistService } from './services/vat-assist.service';
import { EntryToolbarComponent } from './components/entry-toolbar.component';
import { EntryHeaderFormComponent } from './components/entry-header-form.component';
import { EntryLinesGridComponent } from './components/entry-lines-grid.component';
import { EntrySummaryPanelComponent } from './components/entry-summary-panel.component';
import { EntryThirdPartyPanelComponent } from './components/entry-third-party-panel.component';
import { EntryShortcutsPanelComponent } from './components/entry-shortcuts-panel.component';
import { EntryBottomTabsComponent } from './components/entry-bottom-tabs.component';
import { GuidedEntryComponent } from './components/guided/guided-entry.component';
import { EntryTemplateTabComponent } from './components/entry-template-tab.component';
import { EntryRecurringTabComponent } from './components/entry-recurring-tab.component';
import { AccountingDocumentImportDialogComponent } from './components/import/accounting-document-import-dialog.component';
import { JournalEntryProposal } from './models/accounting-document-import.models';
import { EntryTabId } from './models/entry-form.model';
import { ErrorHandlerService } from '@core/services/error-handler.service';

@Component({
  selector: 'app-manual-entry',
  standalone: true,
  imports: [
    CommonModule,
    TabsModule,
    PageHeaderComponent,
    AnalyzeWithAiButtonComponent,
    DraftBannerComponent,
    TemplatePickerModalComponent,
    SaveTemplateModalComponent,
    EntryToolbarComponent,
    EntryHeaderFormComponent,
    EntryLinesGridComponent,
    EntrySummaryPanelComponent,
    EntryThirdPartyPanelComponent,
    EntryShortcutsPanelComponent,
    EntryBottomTabsComponent,
    GuidedEntryComponent,
    EntryTemplateTabComponent,
    EntryRecurringTabComponent,
    AccountingDocumentImportDialogComponent
  ],
  providers: [EntryFormStore, EntryReferenceStore, EntrySubmitService, VatAssistService],
  template: `
    <app-page-header [title]="pageTitle()"
                     [subtitle]="pageSubtitle()">
      <app-analyze-with-ai-button
        screenId="accounting-manual-entry"
        [payloadBuilder]="buildManualEntryAnalyzePayload"
        [disabled]="store.loading()" />
    </app-page-header>

    <app-draft-banner
      [visible]="pendingDraft() !== null && !store.editingLocked()"
      [savedAt]="pendingDraft()?.savedAt ?? null"
      (restore)="restoreDraft()"
      (discard)="discardDraft()" />

    @if (store.editingLocked() && store.isAutoGenerated()) {
      <p class="me-source-banner" role="status">
        Écriture générée depuis {{ sourceLabel() }}. La pièce source n'est pas modifiée.
      </p>
    }

    @if (store.editingLocked() && store.isReversal()) {
      <p class="me-warning-banner" role="alert">
        Cette écriture est une extourne : vos modifications rompent la symétrie miroir avec l'écriture d'origine.
      </p>
    }

    @if (store.editingLocked() && store.sourceEntityType() === 'CashOperation') {
      <p class="me-warning-banner" role="alert">
        Cette modification impacte le calcul de la TVA sur encaissements : elle sera prise en compte au prochain
        recalcul (enregistrement de la déclaration en brouillon, ou rectificative si la déclaration du mois est déjà
        soumise). Une déclaration déjà enregistrée n'est pas modifiée automatiquement. La ventilation par taux reste
        celle de l'opération de caisse d'origine.
      </p>
    }

    @if (refs.vatRatesFromFallback()) {
      <p class="me-vat-fallback-banner" role="status">
        Taux TVA par défaut utilisés (0 %, 7 %, 13 %, 19 %). La configuration personnalisée n'est pas accessible avec vos droits actuels.
      </p>
    }

    <app-entry-toolbar
      (save)="submit($event)"
      (loadTemplate)="openTemplatePicker()"
      (saveTemplate)="openSaveTemplate()"
      (reset)="resetWithConfirm()"
      (importDocument)="openDocumentImport()"
      (cancelEdit)="cancelEdit()" />

    <app-accounting-document-import-dialog
      [(visible)]="documentImportVisible"
      (applied)="onDocumentProposalApplied($event)" />

    <p-tabs class="ft-tabs entry-main-tabs"
            [value]="tabIndex()"
            (valueChange)="onTabChange($event)"
            [lazy]="true">
      <p-tablist>
        <p-tab [value]="0">Saisie standard</p-tab>
        @if (!store.editingLocked()) {
          <p-tab [value]="1">Saisie guidée</p-tab>
          <p-tab [value]="2">Saisie par modèle</p-tab>
          <p-tab [value]="3">Saisie récurrente</p-tab>
        }
      </p-tablist>
      <p-tabpanels>
      <p-tabpanel [value]="0">
        <div class="entry-layout">
          <div class="entry-layout__main">
            <app-entry-header-form />
            <app-entry-lines-grid>
              <app-analyze-with-ai-button entryAnalyzeAction
                screenId="accounting-manual-entry"
                [payloadBuilder]="buildManualEntryAnalyzePayload"
                [disabled]="store.loading()" />
            </app-entry-lines-grid>
            <app-entry-bottom-tabs
              [pendingFiles]="pendingFiles()"
              (pendingFilesChange)="pendingFiles.set($event)"
              [notes]="store.workNotes()"
              (notesChange)="store.workNotes.set($event)" />
          </div>
          <div class="entry-layout__footer">
            <app-entry-summary-panel />
            <app-entry-third-party-panel [thirdParty]="store.dominantThirdParty()" />
            <app-entry-shortcuts-panel />
          </div>
        </div>
      </p-tabpanel>

      @if (!store.editingLocked()) {
      <p-tabpanel [value]="1">
        <div class="entry-layout">
          <div class="entry-layout__main">
            <app-guided-entry (finish)="submit('navigate')" />
          </div>
          <div class="entry-layout__footer">
            <app-entry-shortcuts-panel />
          </div>
        </div>
      </p-tabpanel>

      <p-tabpanel [value]="2">
        <app-entry-template-tab (apply)="onTemplateSelected($event)" />
      </p-tabpanel>

      <p-tabpanel [value]="3">
        <app-entry-recurring-tab />
      </p-tabpanel>
      }
      </p-tabpanels>
    </p-tabs>

    @if (store.error()) {
      <p class="text-danger me-error" role="alert">{{ store.error() }}</p>
    }
    @if (store.successMsg()) {
      <p class="text-success me-error" role="status">{{ store.successMsg() }}</p>
    }
    @if (store.periodClosed()) {
      <p class="me-period-warning" role="alert">
        La période comptable de cette date est clôturée — modifiez la date pour enregistrer.
      </p>
    }

    <details class="me-shortcuts" aria-label="Liste des raccourcis clavier">
      <summary>⌨ Raccourcis clavier</summary>
      <ul class="me-shortcuts-list">
        <li><kbd>Ctrl</kbd>+<kbd>S</kbd> — Enregistrer l'écriture</li>
        <li><kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> — Enregistrer & nouveau</li>
        <li><kbd>Alt</kbd>+<kbd>L</kbd> — Ajouter une ligne</li>
        <li><kbd>Alt</kbd>+<kbd>B</kbd> — Équilibrer automatiquement</li>
        <li><kbd>Alt</kbd>+<kbd>M</kbd> — Charger un modèle</li>
        <li><kbd>Alt</kbd>+<kbd>N</kbd> — Réinitialiser le formulaire</li>
        <li><kbd>Tab</kbd> / <kbd>Entrée</kbd> — Depuis un montant : ligne suivante (saut du crédit si débit saisi)</li>
        <li><kbd>Esc</kbd> — Fermer la modale ouverte</li>
      </ul>
    </details>

    <app-template-picker-modal
      [visible]="showTemplatePicker()"
      (close)="closeTemplatePicker()"
      (templateSelected)="onTemplateSelected($event)" />

    <app-save-template-modal
      [visible]="showSaveTemplate()"
      [defaultName]="store.entryLabel()"
      [journalCode]="store.journalCode()"
      [saving]="savingTemplate()"
      (close)="closeSaveTemplate()"
      (save)="onSaveAsTemplate($event)" />
  `,
  styles: `
    .entry-main-tabs { margin-bottom:var(--spacing-4); }
    .entry-layout { display:grid; grid-template-columns:minmax(0,1fr); gap:var(--spacing-4); }
    .entry-layout__main { min-width:0; }
    .entry-layout__footer { display:grid; grid-template-columns:repeat(auto-fit, minmax(min(100%, 20rem), 1fr)); gap:var(--spacing-3); align-items:start; }
    .me-error { margin:var(--spacing-3) 0; }
    .text-danger { color:var(--color-error-600); }
    .text-success { color:var(--color-success-600); }
    .me-period-warning { color:var(--color-error-700); font-size:var(--font-size-sm); font-weight:var(--font-weight-medium); margin:var(--spacing-3) 0; }
    .me-vat-fallback-banner, .me-warning-banner { margin:var(--spacing-3) 0; padding:var(--spacing-2) var(--spacing-3); background:var(--color-warning-50); color:var(--color-warning-800); border-radius:var(--radius-md); font-size:var(--font-size-sm); border:1px solid var(--color-warning-200); }
    .me-warning-banner { border-left:3px solid var(--color-warning-500, #f59e0b); }
    .me-source-banner { margin:var(--spacing-3) 0; padding:var(--spacing-2) var(--spacing-3); background:var(--color-info-50, #eff6ff); color:var(--color-info-800, #1e40af); border-radius:var(--radius-md); font-size:var(--font-size-sm); border:1px solid var(--color-info-200, #bfdbfe); }
    .me-shortcuts { margin-top:var(--spacing-4); padding-top:var(--spacing-3); border-top:1px dashed var(--color-border-subtle); font-size:var(--font-size-xs); color:var(--color-text-tertiary); }
    .me-shortcuts summary { cursor:pointer; font-weight:var(--font-weight-semibold); }
    .me-shortcuts-list { display:grid; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); gap:var(--spacing-1) var(--spacing-4); list-style:none; padding:var(--spacing-2) 0 0; margin:0; }
    .me-shortcuts kbd { display:inline-block; padding:0 var(--spacing-1); font-family:monospace; font-size:0.75em; background:var(--color-background-subtle); border:1px solid var(--color-border-default); border-radius:var(--radius-sm); }
  `
})
export class ManualEntryComponent implements OnInit {
  private readonly errors = inject(ErrorHandlerService);
  readonly store = inject(EntryFormStore);
  readonly refs = inject(EntryReferenceStore);
  private readonly submitService = inject(EntrySubmitService);
  private readonly api = inject(AccountingService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly toast = inject(ToastService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly draftStore = inject(ManualEntryDraftService);
  private readonly confirmationService = inject(ConfirmationService);

  readonly pendingDraft = signal<ManualEntryDraft | null>(null);
  readonly showTemplatePicker = signal(false);
  readonly showSaveTemplate = signal(false);
  readonly savingTemplate = signal(false);
  readonly pendingFiles = signal<File[]>([]);
  readonly tabIndex = signal(0);
  readonly documentImportVisible = signal(false);

  private draftInitialized = signal(false);
  private readonly returnFrom = signal<string | null>(null);
  private readonly returnTo = signal<string | null>(null);
  private readonly returnJournal = signal<string | null>(null);

  readonly pageTitle = computed(() => {
    if (!this.store.editingLocked()) {
      return 'Saisie des écritures comptables';
    }
    const n = this.store.editingEntryNumber();
    const journal = this.store.journalCode();
    return n != null
      ? `Modification de l'écriture ${journal} n° ${n} — Brouillon`
      : 'Modification de l\'écriture — Brouillon';
  });

  readonly pageSubtitle = computed(() =>
    this.store.editingLocked()
      ? 'Corrigez les lignes puis enregistrez. La validation se fait ensuite depuis le journal.'
      : 'Écriture de journal multi-lignes avec équilibrage automatique'
  );

  readonly sourceLabel = computed(() => sourceEntityLabel(this.store.sourceEntityType()));

  private readonly tabIds: EntryTabId[] = ['standard', 'guided', 'template', 'recurring'];

  readonly buildManualEntryAnalyzePayload = (): unknown =>
    wrapLegacyAnalyzePayload(
      'accounting-manual-entry',
      {
        screen: 'accounting-manual-entry',
        entry: {
          journalCode: this.store.journalCode() || null,
          entryDate: this.store.entryDate() || null,
          label: this.store.entryLabel() || null,
          isBalanced: this.store.isBalanced(),
          totalDebit: this.store.totals().debit,
          totalCredit: this.store.totals().credit
        },
        lines: this.store.lines().map(l => ({
          accountNumber: l.accountNumber || null,
          label: l.lineLabel || null,
          debit: l.debit,
          credit: l.credit
        }))
      } as Record<string, unknown>,
      { rowsKey: 'lines' }
    );

  constructor() {
    let saveTimer: ReturnType<typeof setTimeout> | null = null;
    effect(() => {
      this.store.toDraftPayload();
      if (!this.draftInitialized()) return;
      if (this.store.editingLocked()) return;
      if (saveTimer) clearTimeout(saveTimer);
      saveTimer = setTimeout(() => {
        if (!this.store.hasUserInput()) {
          this.draftStore.clear();
          return;
        }
        this.draftStore.save(this.store.toDraftPayload());
      }, 800);
    });

    effect(() => {
      this.store.setAccounts(this.refs.accounts());
      this.store.setPeriods(this.refs.periods());
      const opts = this.refs.journalOptions();
      if (opts.length > 0) this.store.setJournalOptions(opts);
    });
  }

  ngOnInit(): void {
    this.refs.loadAll();

    const qp = this.route.snapshot.queryParamMap;
    this.returnFrom.set(qp.get('returnFrom'));
    this.returnTo.set(qp.get('returnTo'));
    this.returnJournal.set(qp.get('returnJournal'));
    const entryId = qp.get('entryId');
    if (entryId) {
      this.loadExistingEntry(entryId);
      return;
    }

    const draft = this.draftStore.load();
    if (draft && this.draftStore.isMeaningful(draft)) {
      this.pendingDraft.set(draft);
    } else {
      this.draftStore.clear();
      this.draftInitialized.set(true);
    }
  }

  onTabChange(index: string | number): void {
    const tabIndex = typeof index === 'number' ? index : Number(index);
    this.tabIndex.set(tabIndex);
    this.store.activeTab.set(this.tabIds[tabIndex] ?? 'standard');
  }

  submit(afterSuccess: 'navigate' | 'reset' | 'duplicate' = 'navigate'): void {
    if (this.store.editingLocked()) {
      afterSuccess = 'navigate';
    }
    const letteredCodes = this.store.letteredGroupCodes();
    if (letteredCodes.length > 0) {
      this.confirmationService.confirm({
        message:
          `Enregistrer délettrera le(s) groupe(s) ${letteredCodes.join(', ')} : toutes leurs lignes ` +
          'redeviendront lettrables, y compris celles d\'autres écritures. Continuer ?',
        header: 'Écriture lettrée',
        acceptLabel: 'Délettrer et enregistrer',
        rejectLabel: 'Annuler',
        accept: () => this.confirmWorkNotesThenSubmit(afterSuccess)
      });
      return;
    }
    this.confirmWorkNotesThenSubmit(afterSuccess);
  }

  private confirmWorkNotesThenSubmit(afterSuccess: 'navigate' | 'reset' | 'duplicate'): void {
    if (this.store.workNotes().trim() && afterSuccess !== 'duplicate') {
      this.confirmationService.confirm({
        message: 'La note de travail ne sera pas enregistrée en comptabilité. Continuer ?',
        header: 'Confirmation',
        acceptLabel: 'Continuer',
        rejectLabel: 'Annuler',
        accept: () => this.executeSubmit(afterSuccess)
      });
      return;
    }

    this.executeSubmit(afterSuccess);
  }

  private executeSubmit(afterSuccess: 'navigate' | 'reset' | 'duplicate'): void {
    this.submitService
      .submit(this.store, this.pendingFiles(), afterSuccess)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(result => {
        if (result.success) {
          this.pendingFiles.set([]);
          this.store.letteredGroupCodes.set([]);
          this.submitService.handleSubmitSuccess(
            this.store,
            result,
            afterSuccess,
            (jc, dt) => this.navigateToJournal(jc, dt),
            () => this.draftStore.clear()
          );
        }
      });
  }

  openDocumentImport(): void {
    if (this.store.editingLocked()) return;
    this.documentImportVisible.set(true);
  }

  /**
   * Applique une proposition d'écriture importée : lignes + en-tête dans le formulaire, et le
   * fichier source part comme pièce jointe (même mécanique que les pièces ajoutées à la main).
   */
  onDocumentProposalApplied(event: { proposal: JournalEntryProposal; file: File }): void {
    this.store.applyDocumentProposal(event.proposal);
    this.pendingFiles.update(files => [...files, event.file]);
    this.tabIndex.set(0);
    this.store.activeTab.set('standard');
    const lineCount = event.proposal.lines.filter(
      l => l.debit > 0 || l.credit > 0
    ).length;
    this.toast.add({
      severity: 'success',
      summary: 'Proposition appliquée',
      detail: `${lineCount} ligne(s) posée(s). Vérifiez avant d'enregistrer.`
    });
  }

  private navigateToJournal(journalCode: string, date: string): void {
    const from = this.returnFrom() || date;
    const to = this.returnTo() || date;
    const jc = this.returnJournal() || journalCode;
    this.router.navigate(['/accounting/journal'], {
      queryParams: { journalCode: jc || undefined, from, to }
    });
  }

  cancelEdit(): void {
    this.navigateToJournal(this.store.journalCode(), this.store.entryDate());
  }

  private loadExistingEntry(entryId: string): void {
    this.store.loading.set(true);
    this.api.getJournalEntry(entryId)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: res => {
          this.store.loading.set(false);
          if (!res.success || !res.data) {
            this.leaveEditWithError(res.error ?? "Impossible de charger l'écriture.");
            return;
          }
          const entry = res.data;
          if (!entry.isDraft) {
            this.leaveEditWithError("Seule une écriture en brouillon peut être modifiée.");
            return;
          }
          this.store.loadFromEntry(entry);
          this.draftInitialized.set(true);
        },
        error: err => {
          this.store.loading.set(false);
          this.leaveEditWithError(this.errors.extractErrorMessage(err, "Erreur réseau lors du chargement de l'écriture."));
        }
      });
  }

  private leaveEditWithError(message: string): void {
    this.toast.add({ severity: 'error', summary: 'Modification impossible', detail: message, life: 6000 });
    this.router.navigate(['/accounting/journal'], {
      queryParams: {
        journalCode: this.returnJournal() || undefined,
        from: this.returnFrom() || undefined,
        to: this.returnTo() || undefined
      }
    });
  }

  restoreDraft(): void {
    const draft = this.pendingDraft();
    if (!draft) return;
    this.store.restoreFromDraft(draft);
    if (draft.activeTab) {
      const idx = this.tabIds.indexOf(draft.activeTab);
      if (idx >= 0) this.tabIndex.set(idx);
    }
    this.pendingDraft.set(null);
    this.draftInitialized.set(true);
    this.toast.add({
      severity: 'info',
      summary: 'Brouillon restauré',
      detail: 'Votre saisie a été restaurée. Vérifiez les montants avant d\'enregistrer.',
      life: 4000
    });
  }

  discardDraft(): void {
    this.draftStore.clear();
    this.pendingDraft.set(null);
    this.draftInitialized.set(true);
  }

  resetWithConfirm(): void {
    if (this.store.editingLocked()) {
      const id = this.store.editingEntryId();
      if (id) this.loadExistingEntry(id);
      return;
    }
    if (!this.store.hasUserInput()) {
      this.store.resetForm();
      return;
    }
    this.confirmationService.confirm({
      message: 'Voulez-vous vraiment vider le formulaire ? Toutes les saisies en cours seront perdues.',
      header: 'Confirmation',
      acceptLabel: 'Vider',
      rejectLabel: 'Annuler',
      accept: () => {
        this.store.resetForm();
        this.pendingFiles.set([]);
      }
    });
  }

  openTemplatePicker(): void {
    if (this.store.editingLocked()) return;
    this.showTemplatePicker.set(true);
  }
  closeTemplatePicker(): void { this.showTemplatePicker.set(false); }

  onTemplateSelected(template: JournalEntryTemplateDto): void {
    if (this.store.hasUserInput()) {
      this.confirmationService.confirm({
        message: `Charger le modèle « ${template.name} » va remplacer la saisie en cours. Voulez-vous continuer ?`,
        header: 'Confirmation',
        acceptLabel: 'Continuer',
        rejectLabel: 'Annuler',
        accept: () => this.applySelectedTemplate(template)
      });
      return;
    }
    this.applySelectedTemplate(template);
  }

  private applySelectedTemplate(template: JournalEntryTemplateDto): void {
    this.applyTemplate(template);
    this.tabIndex.set(0);
    this.closeTemplatePicker();
  }

  private applyTemplate(template: JournalEntryTemplateDto): void {
    this.store.applyHeaderFromTemplate(template.journalCode, template.labelTemplate ?? null);
    this.store.applyLinesFromTemplate(
      template.lines
        .slice()
        .sort((a, b) => a.lineNumber - b.lineNumber)
        .map(l => ({
          accountNumber: l.accountNumber,
          lineLabel: l.lineLabelTemplate ?? '',
          debit: l.fixedDebit ?? null,
          credit: l.fixedCredit ?? null
        }))
    );
    this.toast.add({
      severity: 'info',
      summary: 'Modèle chargé',
      detail: `Le modèle « ${template.name} » a été chargé.`,
      life: 4000
    });
  }

  openSaveTemplate(): void {
    if (!this.store.canSaveAsTemplate()) {
      this.toast.add({
        severity: 'warn',
        summary: 'Sauvegarde impossible',
        detail: 'Veuillez saisir au moins 2 lignes avec un numéro de compte.',
        life: 5000
      });
      return;
    }
    this.showSaveTemplate.set(true);
  }

  closeSaveTemplate(): void { this.showSaveTemplate.set(false); }

  onSaveAsTemplate(payload: SaveTemplatePayload): void {
    const linesWithAccount = this.store.lines().filter(l => l.accountNumber.trim().length > 0);
    if (linesWithAccount.length < 2) return;

    const request: CreateJournalEntryTemplateRequest = {
      name: payload.name,
      description: payload.description || null,
      journalCode: payload.journalCode,
      labelTemplate: payload.labelTemplate || null,
      lines: linesWithAccount.map((l, idx) => ({
        lineNumber: idx + 1,
        accountNumber: l.accountNumber.trim(),
        lineLabelTemplate: l.lineLabel.trim() || null,
        fixedDebit: payload.keepAmounts ? (l.debit ?? null) : null,
        fixedCredit: payload.keepAmounts ? (l.credit ?? null) : null
      }))
    };

    this.savingTemplate.set(true);
    this.api.createJournalTemplate(request)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: res => {
          this.savingTemplate.set(false);
          if (res.success) {
            this.closeSaveTemplate();
            this.toast.add({ severity: 'success', summary: 'Modèle sauvegardé', detail: `Le modèle « ${payload.name} » est disponible.`, life: 5000 });
          } else {
            this.toast.add({ severity: 'error', summary: 'Échec', detail: res.error ?? 'Erreur', life: 6000 });
          }
        },
        error: err => {
          this.savingTemplate.set(false);
          this.toast.add({ severity: 'error', summary: 'Impossible de sauvegarder.', detail: this.errors.extractErrorMessage(err, 'Erreur réseau'), life: 6000 });
        }
      });
  }

  @HostListener('document:keydown', ['$event'])
  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      if (this.showTemplatePicker()) { this.closeTemplatePicker(); event.preventDefault(); return; }
      if (this.showSaveTemplate()) { this.closeSaveTemplate(); event.preventDefault(); return; }
      return;
    }
    // La modale d'import est un p-dialog : il gère Échap lui-même. En revanche les raccourcis
    // d'édition ne doivent pas traverser la modale — Ctrl+S enregistrerait l'écriture en cours
    // pendant l'analyse d'une facture.
    if (this.showTemplatePicker() || this.showSaveTemplate() || this.documentImportVisible()) return;

    if ((event.ctrlKey || event.metaKey) && (event.key === 's' || event.key === 'S')) {
      event.preventDefault();
      if (!this.store.canSubmit()) return;
      this.submit(event.shiftKey && !this.store.editingLocked() ? 'reset' : 'navigate');
      return;
    }

    if (event.altKey && !event.ctrlKey && !event.metaKey) {
      switch (event.key.toLowerCase()) {
        case 'l': event.preventDefault(); this.store.addLine(); break;
        case 'b': event.preventDefault(); if (this.store.canAutoBalance()) this.store.autoBalance(); break;
        case 'm': event.preventDefault(); if (!this.store.editingLocked()) this.openTemplatePicker(); break;
        case 'n': event.preventDefault(); this.resetWithConfirm(); break;
      }
    }
  }
}

const SOURCE_ENTITY_LABELS: Record<string, string> = {
  Invoice: 'une facture de vente',
  InvoiceCreditNote: 'un avoir',
  Payment: 'un encaissement',
  SupplierInvoice: 'une facture fournisseur',
  SupplierPayment: 'un paiement fournisseur',
  CashOperation: 'une opération de caisse',
  BankDeposit: 'un versement banque',
  PayrollRun: 'un cycle de paie',
  PayrollPayment: 'un paiement de paie',
  FixedAssetAcquisition: 'une immobilisation',
  FixedAssetDepreciation: 'une dotation aux amortissements',
  FixedAssetDisposal: 'une cession d\'immobilisation',
  OpeningBalance: 'un à-nouveau',
  Manual: 'une saisie manuelle',
  BankReconciliation: 'un rapprochement bancaire'
};

function sourceEntityLabel(source: string | null): string {
  if (!source) return 'un document source';
  return SOURCE_ENTITY_LABELS[source] ?? 'un document source';
}
