using FactuTrust.Application.Common.Interfaces.Repositories;
using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Commands;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Enums;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Moq;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.Application;

/// <summary>
/// Édition unitaire d'un brouillon : lettrage bloqué, auto-généré JV autorisé,
/// EntryNumber / SourceEntityType inchangés.
/// </summary>
public sealed class UpdateDraftJournalEntryCommandHandlerTests
{
    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;
        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(databaseName: _databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private static IReadOnlyList<JournalLineInput> SaleLines(decimal amount = 100m) => new[]
    {
        new JournalLineInput("4111", "Client", amount, 0, null, ThirdPartyKind.None),
        new JournalLineInput("707", "Ventes", 0, amount, null, ThirdPartyKind.None)
    };

    private static AccountingPeriod SeedPeriod(TestTenantDbContextFactory factory)
    {
        var period = AccountingPeriod.Create(2026, 8, new DateTime(2026, 8, 1), new DateTime(2026, 8, 31));
        period.SetAuditInfo("test", false);
        using var ctx = factory.CreateContext();
        ctx.AccountingPeriods.Add(period);
        ctx.SaveChanges();
        return period;
    }

    private static Mock<IChartOfAccountRepository> ChartMock()
    {
        var chart = new Mock<IChartOfAccountRepository>();
        chart.Setup(x => x.GetByAccountNumberAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((string acc, CancellationToken _) =>
                ChartOfAccount.Create(acc, $"Compte {acc}", int.Parse(acc[..1]), null, AccountNatureType.Debit).Value);
        return chart;
    }

    private static UpdateDraftJournalEntryRequest BalancedRequest(decimal amount, string label) => new()
    {
        Label = label,
        Lines = new[]
        {
            new ManualJournalLineRequest { AccountNumber = "4111", LineLabel = "Client", Debit = amount, Credit = 0m },
            new ManualJournalLineRequest { AccountNumber = "706", LineLabel = "Prestations", Debit = 0m, Credit = amount }
        }
    };

    [Fact]
    public async Task Update_LetteredDraft_FailsAndLeavesLinesUnchanged()
    {
        var factory = new TestTenantDbContextFactory($"UpdateDraft_{Guid.NewGuid()}");
        var period = SeedPeriod(factory);
        var draft = JournalEntry.Create(3, "JV", new DateTime(2026, 8, 14), "Vente", period.Id,
            true, "Invoice", Guid.NewGuid(), SaleLines(100m),
            initialStatus: JournalEntryStatus.Brouillon).Value;
        draft.SetAuditInfo("test", false);
        draft.Lines.First().SetLetteringCode("AA");

        using (var seed = factory.CreateContext())
        {
            seed.JournalEntries.Add(draft);
            seed.SaveChanges();
        }

        var handler = new UpdateDraftJournalEntryCommandHandler(
            new JournalEntryRepository(factory), ChartMock().Object, new Mock<IAuditService>().Object);

        var result = await handler.Handle(
            new UpdateDraftJournalEntryCommand(draft.Id, BalancedRequest(200m, "Modifié")),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Contains("Délettrez", result.Error.Description);

        using var ctx = factory.CreateContext();
        var reloaded = await ctx.JournalEntries.Include(e => e.Lines).SingleAsync(e => e.Id == draft.Id);
        Assert.Equal("Vente", reloaded.Label);
        Assert.Equal(100m, reloaded.Lines.OrderBy(l => l.LineNumber).First().DebitAmount.Amount);
        Assert.Equal("AA", reloaded.Lines.First(l => l.LetteringCode == "AA").LetteringCode);
    }

    [Fact]
    public async Task Update_AutoGeneratedJvDraft_SucceedsWithoutChangingNumberOrSource()
    {
        var factory = new TestTenantDbContextFactory($"UpdateDraft_{Guid.NewGuid()}");
        var period = SeedPeriod(factory);
        var sourceId = Guid.NewGuid();
        var draft = JournalEntry.Create(19, "JV", new DateTime(2026, 8, 14), "Client — FAC-2026-000019", period.Id,
            true, "Invoice", sourceId, SaleLines(250m),
            initialStatus: JournalEntryStatus.Brouillon).Value;
        draft.SetAuditInfo("test", false);

        using (var seed = factory.CreateContext())
        {
            seed.JournalEntries.Add(draft);
            seed.SaveChanges();
        }

        var handler = new UpdateDraftJournalEntryCommandHandler(
            new JournalEntryRepository(factory), ChartMock().Object, new Mock<IAuditService>().Object);

        var result = await handler.Handle(
            new UpdateDraftJournalEntryCommand(draft.Id, BalancedRequest(250m, "Client — FAC-2026-000019 (reclassé)")),
            CancellationToken.None);

        Assert.True(result.IsSuccess);

        using var ctx = factory.CreateContext();
        var reloaded = await ctx.JournalEntries.Include(e => e.Lines).SingleAsync(e => e.Id == draft.Id);
        Assert.Equal(19, reloaded.EntryNumber);
        Assert.Equal("JV", reloaded.JournalCode);
        Assert.Equal("Invoice", reloaded.SourceEntityType);
        Assert.Equal(sourceId, reloaded.SourceEntityId);
        Assert.True(reloaded.IsAutoGenerated);
        Assert.Equal(JournalEntryStatus.Brouillon, reloaded.Status);
        Assert.Equal("Client — FAC-2026-000019 (reclassé)", reloaded.Label);
        Assert.Contains(reloaded.Lines, l => l.AccountNumber == "706");
    }
}
