import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { signal } from '@angular/core';
import { of } from 'rxjs';
import { EntryHeaderFormComponent } from './entry-header-form.component';
import { EntryFormStore } from '../services/entry-form.store';
import { EntryReferenceStore } from '../services/entry-reference.store';
import { AccountingService, CurrencyDto, JournalEntryDto } from '../../services/accounting.service';
import { AccountingFeatureFlagsService } from '../../shared/accounting-feature-flags.service';
import { AuthService } from '@core/services/auth.service';
import { PERMISSIONS } from '@core/config/permission-keys';

function currency(code: string, isFunctional = false): CurrencyDto {
  return {
    id: code,
    code,
    label: code,
    decimalPlaces: isFunctional ? 3 : 2,
    ratePeriodicity: 1,
    isActive: true,
    isFunctional,
    configuredRateCount: 12,
    expectedRateCount: 12
  };
}

const TND = currency('TND', true);
const EUR = currency('EUR');

/** Ecriture EUR deja comptabilisee au taux 3,29 — different du 3,3142 que renvoie la table. */
function eurEntry(): JournalEntryDto {
  return {
    id: 'e-1',
    entryNumber: 7,
    journalCode: 'JOD',
    entryDate: '2026-09-12T00:00:00',
    label: 'Ecriture EUR',
    isAutoGenerated: false,
    isReversed: false,
    status: 0,
    isDraft: true,
    attachmentCount: 0,
    currencyCode: 'EUR',
    exchangeRate: 3.29,
    exchangeRateOverridden: true,
    lines: [
      { id: 'l1', lineNumber: 1, accountNumber: '164', label: 'Emprunt', debit: 3290, credit: 0,
        currency: 'TND', debitInCurrency: 1000, creditInCurrency: 0 },
      { id: 'l2', lineNumber: 2, accountNumber: '452', label: 'Associes', debit: 0, credit: 3290,
        currency: 'TND', debitInCurrency: 0, creditInCurrency: 1000 }
    ]
  };
}

async function build(options: {
  flagEnabled: boolean;
  currencies: CurrencyDto[];
  permissions?: string[];
}): Promise<ComponentFixture<EntryHeaderFormComponent>> {
  const permissions = options.permissions ?? [];

  await TestBed.resetTestingModule();
  await TestBed.configureTestingModule({
    imports: [EntryHeaderFormComponent],
    providers: [
      provideNoopAnimations(),
      EntryFormStore,
      {
        provide: EntryReferenceStore,
        useValue: { currencies: signal(options.currencies), openPeriods: signal([]) }
      },
      {
        provide: AccountingService,
        useValue: {
          resolveExchangeRate: () =>
            of({ success: true, data: { currencyCode: 'EUR', rate: 3.3142, referenceRate: 3.3142, isOverridden: false, isFunctional: false } })
        }
      },
      {
        provide: AccountingFeatureFlagsService,
        useValue: { isEnabled: (key: string) => key === 'multiCurrencyEnabled' && options.flagEnabled }
      },
      {
        provide: AuthService,
        useValue: {
          hasPermission: (p: string) => permissions.includes(p),
          hasAllPermissions: (ps: string[]) => ps.every(p => permissions.includes(p)),
          user: signal(null)
        }
      }
    ]
  }).compileComponents();

  const fixture = TestBed.createComponent(EntryHeaderFormComponent);
  fixture.detectChanges();
  return fixture;
}

describe('EntryHeaderFormComponent — multi-devises', () => {
  describe('drapeau éteint', () => {
    it('n’expose pas le sélecteur de devise, même si le catalogue en contient plusieurs', async () => {
      const fixture = await build({ flagEnabled: false, currencies: [TND, EUR] });

      expect(fixture.componentInstance.showCurrency()).toBeFalse();
      expect((fixture.nativeElement as HTMLElement).querySelector('#eh-currency')).toBeNull();
      expect((fixture.nativeElement as HTMLElement).querySelector('#eh-rate')).toBeNull();
    });

    it('laisse le formulaire dans son état mono-devise', async () => {
      const fixture = await build({ flagEnabled: false, currencies: [TND, EUR] });

      // Les champs historiques restent présents et intacts.
      const el = fixture.nativeElement as HTMLElement;
      expect(el.querySelector('#eh-journal')).toBeTruthy();
      expect(el.querySelector('#eh-date')).toBeTruthy();
      expect(fixture.componentInstance.store.currency()).toBe('TND');
      expect(fixture.componentInstance.store.isForeignCurrency()).toBeFalse();
    });
  });

  describe('drapeau allumé', () => {
    it('n’expose rien tant qu’il n’existe pas d’alternative à la devise de tenue', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND] });

      expect(fixture.componentInstance.showCurrency()).toBeFalse();
    });

    it('expose le sélecteur dès qu’une seconde devise existe', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });

      expect(fixture.componentInstance.showCurrency()).toBeTrue();
      expect((fixture.nativeElement as HTMLElement).querySelector('#eh-currency')).toBeTruthy();
    });

    it('n’affiche le taux qu’une fois une devise étrangère choisie', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });
      const el = fixture.nativeElement as HTMLElement;

      expect(el.querySelector('#eh-rate')).toBeNull();

      fixture.componentInstance.onCurrencyChange('EUR');
      fixture.detectChanges();

      expect(el.querySelector('#eh-rate')).toBeTruthy();
    });

    it('reprend les décimales de la devise choisie', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });

      fixture.componentInstance.onCurrencyChange('EUR');
      // Les décimales suivent désormais la devise par un effet, et non plus par une affectation
      // dans le gestionnaire : c'est ce qui les aligne aussi sur une écriture rechargée. Il faut
      // donc laisser passer un cycle de détection — ce que fait le zone Angular à l'exécution.
      fixture.detectChanges();

      expect(fixture.componentInstance.store.currencyDecimals()).toBe(2);
    });
  });

  /**
   * La resolution serveur se declenche sur tout changement de devise ou de date. Rouvrir une
   * ecriture change les deux : sans garde, le taux de la table remplacerait celui avec lequel
   * l'ecriture a ete comptabilisee, et une simple reouverture du formulaire la revaloriserait.
   */
  describe('rechargement d’une écriture', () => {
    it('conserve le taux de l’écriture au lieu de celui de la table', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });
      const store = fixture.componentInstance.store;

      store.loadFromEntry(eurEntry());
      fixture.detectChanges();

      expect(store.currency()).toBe('EUR');
      expect(store.exchangeRate()).toBe(3.29);
    });

    it('reprend le taux de la table dès que la date change', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });
      const store = fixture.componentInstance.store;
      store.loadFromEntry(eurEntry());
      fixture.detectChanges();

      store.setEntryDate('2026-10-15');
      fixture.detectChanges();

      expect(store.exchangeRate()).toBe(3.3142);
    });

    it('reprend le taux de la table après un aller-retour sur le sélecteur', async () => {
      // Sans effacement de la marque, revenir sur EUR retrouverait une clé valide : la résolution
      // serait ignorée et le champ Taux resterait vide, sans moyen de le regarnir.
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });
      const cmp = fixture.componentInstance;
      cmp.store.loadFromEntry(eurEntry());
      fixture.detectChanges();

      cmp.onCurrencyChange('TND');
      fixture.detectChanges();
      cmp.onCurrencyChange('EUR');
      fixture.detectChanges();

      expect(cmp.store.exchangeRate()).toBe(3.3142);
    });

    it('aligne les décimales sur la devise de l’écriture rechargée', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });
      const store = fixture.componentInstance.store;

      store.loadFromEntry(eurEntry());
      fixture.detectChanges();

      expect(store.currencyDecimals()).toBe(2);
      expect(store.amountFormat()).toBe('1.2-2');
    });
  });

  describe('surcharge du taux', () => {
    it('verrouille le champ sans la permission dédiée', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });

      expect(fixture.componentInstance.canOverrideRate()).toBeFalse();

      fixture.componentInstance.onCurrencyChange('EUR');
      fixture.detectChanges();

      const rate = (fixture.nativeElement as HTMLElement).querySelector('#eh-rate') as HTMLInputElement;
      expect(rate.readOnly).toBeTrue();
    });

    it('déverrouille le champ avec la permission', async () => {
      const fixture = await build({
        flagEnabled: true,
        currencies: [TND, EUR],
        permissions: [PERMISSIONS.accounting.exchangeRateOverride]
      });

      expect(fixture.componentInstance.canOverrideRate()).toBeTrue();

      fixture.componentInstance.onCurrencyChange('EUR');
      fixture.detectChanges();

      const rate = (fixture.nativeElement as HTMLElement).querySelector('#eh-rate') as HTMLInputElement;
      expect(rate.readOnly).toBeFalse();
    });

    it('refuse un taux nul ou négatif', async () => {
      const fixture = await build({ flagEnabled: true, currencies: [TND, EUR] });
      const cmp = fixture.componentInstance;

      cmp.onRateChange(0);
      expect(cmp.store.exchangeRate()).toBeNull();

      cmp.onRateChange(-3.3);
      expect(cmp.store.exchangeRate()).toBeNull();

      cmp.onRateChange(3.3142);
      expect(cmp.store.exchangeRate()).toBe(3.3142);
    });
  });
});
