using FactuTrust.Application.Common.Interfaces;
using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.Configuration;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting;
using FactuTrust.Domain.Common;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.ValueObjects;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using AuditActions = FactuTrust.Domain.Entities.AuditActions;

namespace FactuTrust.Infrastructure.Services;

/// <summary>
/// Assistant d'écritures d'inventaire : crée l'écriture de régularisation (journal JOD) et, si
/// demandé, son extourne datée du 1er de la période suivante — dans un seul <c>SaveChanges</c>.
/// L'extourne est une contre-passation planifiée normale (source dédiée), jamais un
/// <c>MarkReversedBy</c> (réservé aux corrections).
/// </summary>
public sealed class AssistedInventoryEntryService : IAssistedInventoryEntryService
{
    public const string SourceInventoryEntry = "InventoryEntry";
    public const string SourceInventoryEntryReversal = "InventoryEntryReversal";
    private const string JournalCode = "JOD";

    private readonly ITenantDbContextFactory _contextFactory;
    private readonly ICurrentUser _currentUser;
    private readonly IAuditService _auditService;
    private readonly AccountingSettings _settings;

    public AssistedInventoryEntryService(
        ITenantDbContextFactory contextFactory,
        ICurrentUser currentUser,
        IAuditService auditService,
        IOptions<AccountingSettings> settings)
    {
        _contextFactory = contextFactory;
        _currentUser = currentUser;
        _auditService = auditService;
        _settings = settings.Value;
    }

    public async Task<Result<InventoryEntryResultDto>> CreateAsync(CreateInventoryEntryRequest request, CancellationToken cancellationToken = default)
    {
        if (!_settings.InventoryAssistantEnabled)
            return Result.Failure<InventoryEntryResultDto>(Error.Validation("Inventory", "L'assistant d'écritures d'inventaire n'est pas activé."));

        if (!Enum.IsDefined(typeof(InventoryEntryKind), request.Kind))
            return Result.Failure<InventoryEntryResultDto>(Error.Validation("Kind", "Type d'écriture d'inventaire inconnu."));
        if (request.Amount <= 0)
            return Result.Failure<InventoryEntryResultDto>(Error.Validation("Amount", "Le montant doit être strictement positif."));

        var debitAccount = request.DebitAccount?.Trim() ?? string.Empty;
        var creditAccount = request.CreditAccount?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(debitAccount) || string.IsNullOrEmpty(creditAccount))
            return Result.Failure<InventoryEntryResultDto>(Error.Validation("Account", "Les comptes de débit et de crédit sont obligatoires."));
        if (debitAccount == creditAccount)
            return Result.Failure<InventoryEntryResultDto>(Error.Validation("Account", "Les comptes de débit et de crédit doivent être différents."));

        var label = string.IsNullOrWhiteSpace(request.Label)
            ? (InventoryEntryDefaults.Find((InventoryEntryKind)request.Kind)?.Label ?? "Écriture d'inventaire")
            : request.Label.Trim();

        var entryDate = request.EntryDate.Date;
        var initialStatus = _settings.BrouillardEnabled ? JournalEntryStatus.Brouillon : JournalEntryStatus.Validee;
        var user = _currentUser.Email ?? "system";

        await using var ctx = _contextFactory.CreateContext();

        // Comptes actifs (même règle que la saisie manuelle).
        var accountCheck = await ValidateAccountsAsync(ctx, cancellationToken, debitAccount, creditAccount);
        if (accountCheck is not null)
            return Result.Failure<InventoryEntryResultDto>(accountCheck);

        // Période de l'écriture d'inventaire (créée au besoin, refusée si clôturée).
        var period = await EnsureOpenPeriodAsync(ctx, entryDate, cancellationToken);
        if (period is null)
            return Result.Failure<InventoryEntryResultDto>(Error.Validation("Period",
                $"La période {entryDate:MM/yyyy} est clôturée : impossible d'y enregistrer l'écriture d'inventaire."));

        var entryNumber = await NextNumberAsync(ctx, entryDate.Year, cancellationToken);
        var lines = new[]
        {
            new JournalLineInput(debitAccount, label, request.Amount, 0m, null, ThirdPartyKind.None),
            new JournalLineInput(creditAccount, label, 0m, request.Amount, null, ThirdPartyKind.None)
        };
        var create = JournalEntry.Create(entryNumber, JournalCode, entryDate, label, period.Id,
            isAutoGenerated: false, SourceInventoryEntry, sourceEntityId: null, lines,
            Money.DefaultCurrency, reversesEntryId: null, initialStatus: initialStatus);
        if (create.IsFailure)
            return Result.Failure<InventoryEntryResultDto>(create.Error);

        var entry = create.Value;
        entry.SetAuditInfo(user, false);
        ctx.JournalEntries.Add(entry);

        Guid? reversalId = null;
        if (request.AutoReverse)
        {
            // Contre-passation planifiée au 1er de la période suivante (repli date du jour si close).
            var reversalDate = FirstDayOfNextPeriod(entryDate);
            var reversalPeriod = await EnsureOpenPeriodAsync(ctx, reversalDate, cancellationToken);
            if (reversalPeriod is null)
            {
                reversalDate = DateTime.UtcNow.Date;
                reversalPeriod = await EnsureOpenPeriodAsync(ctx, reversalDate, cancellationToken);
            }
            if (reversalPeriod is null)
                return Result.Failure<InventoryEntryResultDto>(Error.Validation("Period",
                    "Aucune période ouverte pour générer l'extourne d'inventaire."));

            var reversalNumber = await NextNumberAsync(ctx, reversalDate.Year, cancellationToken);
            var reversalLabel = $"Extourne {label} — {entryDate:MM/yyyy}";
            if (reversalLabel.Length > 500) reversalLabel = reversalLabel[..500];
            var reversalLines = new[]
            {
                new JournalLineInput(creditAccount, reversalLabel, request.Amount, 0m, null, ThirdPartyKind.None),
                new JournalLineInput(debitAccount, reversalLabel, 0m, request.Amount, null, ThirdPartyKind.None)
            };
            var reversalCreate = JournalEntry.Create(reversalNumber, JournalCode, reversalDate, reversalLabel,
                reversalPeriod.Id, isAutoGenerated: true, SourceInventoryEntryReversal, sourceEntityId: entry.Id,
                reversalLines, Money.DefaultCurrency, reversesEntryId: null, initialStatus: initialStatus);
            if (reversalCreate.IsFailure)
                return Result.Failure<InventoryEntryResultDto>(reversalCreate.Error);

            var reversal = reversalCreate.Value;
            reversal.SetAuditInfo(user, false);
            ctx.JournalEntries.Add(reversal);
            reversalId = reversal.Id;
        }

        await ctx.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync(
            AuditActions.Accounting.InventoryEntryCreated,
            "JournalEntry",
            entry.Id,
            newValues: new { Kind = request.Kind, entryDate, debitAccount, creditAccount, request.Amount, AutoReverse = request.AutoReverse, ReversalId = reversalId },
            cancellationToken: cancellationToken);

        return Result.Success(new InventoryEntryResultDto { EntryId = entry.Id, ReversalEntryId = reversalId });
    }

    private static async Task<Error?> ValidateAccountsAsync(TenantDbContext ctx, CancellationToken ct, params string[] accounts)
    {
        foreach (var acc in accounts.Distinct(StringComparer.Ordinal))
        {
            var account = await ctx.ChartOfAccounts.AsNoTracking().FirstOrDefaultAsync(c => c.AccountNumber == acc, ct);
            if (account is null)
                return Error.Validation("AccountNumber", $"Le compte {acc} n'existe pas dans le plan comptable.");
            if (!account.IsActive)
                return Error.Validation("AccountNumber", $"Le compte {acc} est désactivé.");
        }
        return null;
    }

    private static async Task<AccountingPeriod?> EnsureOpenPeriodAsync(TenantDbContext ctx, DateTime date, CancellationToken ct)
    {
        var period = await ctx.AccountingPeriods.FirstOrDefaultAsync(p => p.FiscalYear == date.Year && p.Month == date.Month, ct);
        if (period is null)
        {
            var start = new DateTime(date.Year, date.Month, 1, 0, 0, 0, DateTimeKind.Utc);
            var end = new DateTime(date.Year, date.Month, DateTime.DaysInMonth(date.Year, date.Month), 0, 0, 0, DateTimeKind.Utc);
            period = AccountingPeriod.Create(date.Year, date.Month, start, end);
            period.SetAuditInfo("system", false);
            ctx.AccountingPeriods.Add(period);
        }
        return period.IsClosed ? null : period;
    }

    private static async Task<int> NextNumberAsync(TenantDbContext ctx, int year, CancellationToken ct)
    {
        var seq = await ctx.JournalEntrySequences.FirstOrDefaultAsync(s => s.JournalCode == JournalCode && s.FiscalYear == year, ct);
        if (seq is null)
        {
            seq = JournalEntrySequence.Create(JournalCode, year);
            seq.SetAuditInfo("system", false);
            ctx.JournalEntrySequences.Add(seq);
        }
        return seq.Next();
    }

    private static DateTime FirstDayOfNextPeriod(DateTime entryDate)
    {
        // Extourne au 1er du mois suivant (ou 01/01/N+1 si l'écriture est datée de décembre).
        var next = entryDate.AddMonths(1);
        return new DateTime(next.Year, next.Month, 1);
    }
}
