/**
 * Mapping FontAwesome / PrimeIcons → attribut sélecteur Lucide.
 *
 * À utiliser pour la migration progressive des icônes : chaque template qui
 * accepte une icône en `string` peut consulter ce mapping pour produire la
 * version Lucide équivalente.
 *
 * NB : les valeurs sont l'**attribut sélecteur Lucide** (ex: `lucideFileText`),
 * pas le nom du composant (`LucideFileText`). Cela permet un usage direct dans
 * un template : `<svg [attr.lucide-icon-name]="iconMap[faClass]"></svg>`
 * ou avec un wrapper de composant.
 */

/** Mapping FontAwesome (sans préfixe `fa-solid` / `fa-regular`) → Lucide. */
export const FA_TO_LUCIDE: Readonly<Record<string, string>> = {
  // Navigation
  'fa-gauge-high': 'lucideLayoutDashboard',
  'fa-house': 'lucideHome',
  'fa-file-invoice': 'lucideFileText',
  'fa-file-invoice-dollar': 'lucideReceipt',
  'fa-file-lines': 'lucideFileText',
  'fa-file-signature': 'lucideFileSignature',
  'fa-chart-line': 'lucideTrendingUp',
  'fa-chart-bar': 'lucideBarChart3',
  'fa-chart-pie': 'lucideBarChart3',
  'fa-boxes-stacked': 'lucidePackageOpen',
  'fa-box': 'lucideBox',
  'fa-warehouse': 'lucideBoxes',
  'fa-tags': 'lucideTags',
  'fa-tag': 'lucideTag',
  'fa-users': 'lucideUsers',
  'fa-user': 'lucideUser',
  'fa-wallet': 'lucideWallet',
  'fa-money-bill': 'lucideWallet',
  'fa-credit-card': 'lucideCreditCard',
  'fa-truck': 'lucideTruck',
  'fa-truck-ramp-box': 'lucideTruck',
  'fa-building': 'lucideBuilding2',
  'fa-briefcase': 'lucideBriefcase',
  'fa-gear': 'lucideSettings',
  'fa-cog': 'lucideSettings',
  'fa-sliders': 'lucideSettings',
  'fa-bell': 'lucideBell',
  'fa-magnifying-glass': 'lucideSearch',
  'fa-search': 'lucideSearch',
  'fa-plus': 'lucidePlus',
  'fa-minus': 'lucideMinus',
  'fa-angles-left': 'lucideChevronsLeft',
  'fa-angles-right': 'lucideChevronsRight',
  'fa-chevron-down': 'lucideChevronDown',
  'fa-chevron-up': 'lucideChevronUp',
  'fa-chevron-right': 'lucideChevronRight',
  'fa-chevron-left': 'lucideChevronLeft',
  'fa-sparkles': 'lucideSparkles',
  'fa-wand-magic-sparkles': 'lucideSparkles',
  'fa-robot': 'lucideBot',
  'fa-message': 'lucideMessageCircle',
  'fa-comment': 'lucideMessageCircle',
  'fa-bolt': 'lucideZap',
  'fa-star': 'lucideStar',
  'fa-award': 'lucideAward',
  // Statuts
  'fa-circle-check': 'lucideCircleCheck',
  'fa-check': 'lucideCheck',
  'fa-xmark': 'lucideX',
  'fa-times': 'lucideX',
  'fa-ban': 'lucideBan',
  'fa-circle-exclamation': 'lucideCircleAlert',
  'fa-triangle-exclamation': 'lucideTriangleAlert',
  'fa-clock': 'lucideClock',
  'fa-history': 'lucideHistory',
  'fa-paper-plane': 'lucideSend',
  'fa-pencil': 'lucidePencil',
  'fa-pen': 'lucidePencil',
  'fa-arrow-up': 'lucideArrowUp',
  'fa-arrow-down': 'lucideArrowDown',
  'fa-arrow-left': 'lucideArrowLeft',
  'fa-arrow-right': 'lucideArrowRight',
  'fa-arrow-trend-up': 'lucideArrowUpRight',
  'fa-arrow-trend-down': 'lucideArrowDownRight',
  // Actions
  'fa-eye': 'lucideEye',
  'fa-eye-slash': 'lucideEyeOff',
  'fa-trash': 'lucideTrash2',
  'fa-trash-can': 'lucideTrash2',
  'fa-edit': 'lucideEdit',
  'fa-print': 'lucidePrinter',
  'fa-download': 'lucideDownload',
  'fa-upload': 'lucideUpload',
  'fa-filter': 'lucideFilter',
  'fa-rotate': 'lucideRefreshCw',
  'fa-rotate-right': 'lucideRefreshCw',
  'fa-arrows-rotate': 'lucideRefreshCw',
  'fa-ellipsis': 'lucideMoreHorizontal',
  'fa-ellipsis-vertical': 'lucideMoreVertical',
  'fa-bars': 'lucideMenu',
  // Misc
  'fa-calendar': 'lucideCalendar',
  'fa-calendar-days': 'lucideCalendarDays',
  'fa-map-pin': 'lucideMapPin',
  'fa-location-dot': 'lucideMapPin',
  'fa-phone': 'lucidePhone',
  'fa-envelope': 'lucideMail',
  'fa-right-from-bracket': 'lucideLogOut',
  'fa-shield': 'lucideShield',
  'fa-shield-halved': 'lucideShieldCheck',
  'fa-key': 'lucideKey',
  'fa-lock': 'lucideLock',
  'fa-unlock': 'lucideUnlock',
  'fa-info': 'lucideInfo',
  'fa-circle-info': 'lucideInfo',
  'fa-circle-question': 'lucideHelpCircle',
  'fa-up-right-from-square': 'lucideExternalLink',
};

/** Mapping PrimeIcons (sans préfixe `pi pi-`) → Lucide. */
export const PI_TO_LUCIDE: Readonly<Record<string, string>> = {
  // Navigation & data
  'pi-th-large': 'lucideLayoutDashboard',
  'pi-home': 'lucideHome',
  'pi-file': 'lucideFileText',
  'pi-file-edit': 'lucidePencil',
  'pi-receipt': 'lucideReceipt',
  'pi-shopping-cart': 'lucideShoppingCart',
  'pi-dollar': 'lucideWallet',
  'pi-credit-card': 'lucideCreditCard',
  'pi-wallet': 'lucideWallet',
  'pi-chart-line': 'lucideTrendingUp',
  'pi-chart-bar': 'lucideBarChart3',
  'pi-chart-pie': 'lucideBarChart3',
  'pi-box': 'lucideBox',
  'pi-briefcase': 'lucideBriefcase',
  'pi-building': 'lucideBuilding2',
  'pi-users': 'lucideUsers',
  'pi-user': 'lucideUser',
  'pi-tag': 'lucideTag',
  'pi-tags': 'lucideTags',
  'pi-cog': 'lucideSettings',
  'pi-sliders-h': 'lucideSettings',
  'pi-bell': 'lucideBell',
  'pi-search': 'lucideSearch',
  'pi-plus': 'lucidePlus',
  'pi-minus': 'lucideMinus',
  'pi-times': 'lucideX',
  'pi-check': 'lucideCheck',
  'pi-check-circle': 'lucideCircleCheck',
  'pi-times-circle': 'lucideX',
  'pi-exclamation-triangle': 'lucideTriangleAlert',
  'pi-info-circle': 'lucideInfo',
  'pi-question-circle': 'lucideHelpCircle',
  'pi-clock': 'lucideClock',
  'pi-history': 'lucideHistory',
  'pi-send': 'lucideSend',
  'pi-pencil': 'lucidePencil',
  'pi-ban': 'lucideBan',
  'pi-verified': 'lucideShieldCheck',
  'pi-calendar': 'lucideCalendar',
  'pi-calendar-times': 'lucideCalendarDays',
  'pi-refresh': 'lucideRefreshCw',
  'pi-arrow-up': 'lucideArrowUp',
  'pi-arrow-down': 'lucideArrowDown',
  'pi-arrow-left': 'lucideArrowLeft',
  'pi-arrow-right': 'lucideArrowRight',
  'pi-chevron-down': 'lucideChevronDown',
  'pi-chevron-up': 'lucideChevronUp',
  'pi-chevron-right': 'lucideChevronRight',
  'pi-chevron-left': 'lucideChevronLeft',
  'pi-eye': 'lucideEye',
  'pi-trash': 'lucideTrash2',
  'pi-print': 'lucidePrinter',
  'pi-download': 'lucideDownload',
  'pi-upload': 'lucideUpload',
  'pi-filter': 'lucideFilter',
  'pi-spinner': 'lucideLoaderCircle',
  'pi-ellipsis-v': 'lucideMoreVertical',
  'pi-ellipsis-h': 'lucideMoreHorizontal',
  'pi-bars': 'lucideMenu',
  'pi-sign-out': 'lucideLogOut',
  'pi-shield': 'lucideShield',
  'pi-lock': 'lucideLock',
  'pi-envelope': 'lucideMail',
  'pi-phone': 'lucidePhone',
  'pi-file-import': 'lucideFileInput',
  'pi-file-export': 'lucideFileOutput',
  'pi-microchip-ai': 'lucideSparkles',
  'pi-bolt': 'lucideZap',
  'pi-star': 'lucideStar',
};

/** Helper: convertit n'importe quelle classe FA/PI en sélecteur Lucide. */
export function toLucideAttr(faOrPiClass: string): string | undefined {
  const normalized = faOrPiClass.replace(/^fa-solid\s+|^fa-regular\s+|^fa-brands\s+|^pi\s+/, '').trim();
  return FA_TO_LUCIDE[normalized] ?? PI_TO_LUCIDE[normalized];
}
