/**
 * Lucide icon bundle for InstaFact Web.
 *
 * Pattern d'usage (composants standalone Angular 17) :
 *
 *   import { LUCIDE_ICONS } from '@app/shared/icons/lucide-icons';
 *
 *   @Component({
 *     imports: [...LUCIDE_ICONS],
 *     template: `<svg lucideLayoutDashboard [size]="22"></svg>`
 *   })
 *
 * On peut aussi importer une icône précise :
 *   import { LucideLayoutDashboard } from '@lucide/angular';
 *
 * NB : on ne touche PAS aux icônes FontAwesome / PrimeIcons existantes — Lucide
 * coexiste pendant la migration progressive.
 */
import {
  LucideLayoutDashboard,
  LucideFileText,
  LucideTrendingUp,
  LucideTrendingDown,
  LucidePackageOpen,
  LucidePackage,
  LucideTags,
  LucideTag,
  LucideUsers,
  LucideUser,
  LucideWallet,
  LucideTruck,
  LucideBuilding2,
  LucideSettings,
  LucideBell,
  LucideSearch,
  LucidePlus,
  LucideMinus,
  LucideChevronsLeft,
  LucideChevronsRight,
  LucideChevronDown,
  LucideChevronUp,
  LucideChevronRight,
  LucideChevronLeft,
  LucideX,
  LucideCheck,
  LucideCircleCheck,
  LucideCircleAlert,
  LucideTriangleAlert,
  LucideClock,
  LucideSend,
  LucidePencil,
  LucideBan,
  LucideSparkles,
  LucideArrowUp,
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowRight,
  LucideArrowUpRight,
  LucideArrowDownRight,
  LucideReceipt,
  LucideShoppingCart,
  LucideCreditCard,
  LucideBarChart3,
  LucideBriefcase,
  LucideFileSignature,
  LucideFilePlus,
  LucideFileInput,
  LucideFileOutput,
  LucideEye,
  LucideEyeOff,
  LucideTrash2,
  LucideEdit,
  LucidePrinter,
  LucideDownload,
  LucideUpload,
  LucideFilter,
  LucideRefreshCw,
  LucideMoreHorizontal,
  LucideMoreVertical,
  LucideMenu,
  LucideHome,
  LucideHistory,
  LucideCalendar,
  LucideCalendarDays,
  LucideMapPin,
  LucidePhone,
  LucideMail,
  LucideLogOut,
  LucideShield,
  LucideShieldCheck,
  LucideKey,
  LucideLock,
  LucideUnlock,
  LucideInfo,
  LucideHelpCircle,
  LucideExternalLink,
  LucideBot,
  LucideMessageCircle,
  LucideZap,
  LucideStar,
  LucideAward,
  LucideBox,
  LucideBoxes,
  LucideArchive,
  LucideClipboardList,
  LucideClipboardCheck,
  LucideLoaderCircle,
} from '@lucide/angular';

/**
 * Liste globale d'icônes Lucide utilisées dans l'app.
 * À spreader dans le tableau `imports` d'un composant standalone :
 *
 *   imports: [..., ...LUCIDE_ICONS]
 *
 * NB : tree-shake reste actif — seules les icônes effectivement référencées
 * dans les templates seront incluses dans le bundle final (Angular standalone +
 * Vite/esbuild). Conservez ce tableau pour servir de catalogue partagé.
 */
export const LUCIDE_ICONS = [
  LucideLayoutDashboard,
  LucideFileText,
  LucideTrendingUp,
  LucideTrendingDown,
  LucidePackageOpen,
  LucidePackage,
  LucideTags,
  LucideTag,
  LucideUsers,
  LucideUser,
  LucideWallet,
  LucideTruck,
  LucideBuilding2,
  LucideSettings,
  LucideBell,
  LucideSearch,
  LucidePlus,
  LucideMinus,
  LucideChevronsLeft,
  LucideChevronsRight,
  LucideChevronDown,
  LucideChevronUp,
  LucideChevronRight,
  LucideChevronLeft,
  LucideX,
  LucideCheck,
  LucideCircleCheck,
  LucideCircleAlert,
  LucideTriangleAlert,
  LucideClock,
  LucideSend,
  LucidePencil,
  LucideBan,
  LucideSparkles,
  LucideArrowUp,
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowRight,
  LucideArrowUpRight,
  LucideArrowDownRight,
  LucideReceipt,
  LucideShoppingCart,
  LucideCreditCard,
  LucideBarChart3,
  LucideBriefcase,
  LucideFileSignature,
  LucideFilePlus,
  LucideFileInput,
  LucideFileOutput,
  LucideEye,
  LucideEyeOff,
  LucideTrash2,
  LucideEdit,
  LucidePrinter,
  LucideDownload,
  LucideUpload,
  LucideFilter,
  LucideRefreshCw,
  LucideMoreHorizontal,
  LucideMoreVertical,
  LucideMenu,
  LucideHome,
  LucideHistory,
  LucideCalendar,
  LucideCalendarDays,
  LucideMapPin,
  LucidePhone,
  LucideMail,
  LucideLogOut,
  LucideShield,
  LucideShieldCheck,
  LucideKey,
  LucideLock,
  LucideUnlock,
  LucideInfo,
  LucideHelpCircle,
  LucideExternalLink,
  LucideBot,
  LucideMessageCircle,
  LucideZap,
  LucideStar,
  LucideAward,
  LucideBox,
  LucideBoxes,
  LucideArchive,
  LucideClipboardList,
  LucideClipboardCheck,
  LucideLoaderCircle,
] as const;

/**
 * Subset minimal pour les composants ne consommant que quelques icônes
 * (évite de gonfler les imports d'un composant qui n'a besoin que de 2-3 glyphes).
 */
export const LUCIDE_ICONS_CORE = [
  LucideLayoutDashboard,
  LucideFileText,
  LucideX,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
] as const;
