using FactuTrust.Application.Common.Interfaces.Repositories;
using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.Configuration;
using FactuTrust.Domain.Common;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Enums;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Services;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Moq;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.Services;

/// <summary>
/// T13/C6 — garde « écriture active » dans <see cref="AccountingService"/> : une écriture extournée
/// ne bloque plus la (re)comptabilisation d'une dotation ; une écriture active reste bloquante
/// (idempotence). Modèle : <see cref="FixedAssetDepreciationEntryTests"/> (helper BuildService).
/// </summary>
public sealed class AccountingServiceReversalGuardTests
{
    private static readonly Guid CategoryId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0013");

    private static ChartOfAccount Acc(string number) =>
        ChartOfAccount.Create(number, $"Compte {number}", int.Parse(number[..1].ToString()), null, AccountNatureType.Debit).Value;

    /// <summary>
    /// Construit un <see cref="AccountingService"/> dont la garde « écriture active »
    /// (<see cref="IJournalEntryRepository.GetActiveBySourceAsync"/>) renvoie
    /// <paramref name="activeBySource"/> pour la source de dotation.
    /// </summary>
    private static (AccountingService service, List<JournalEntry> captured) BuildService(
        JournalEntry? activeBySource = null)
    {
        var chart = new Mock<IChartOfAccountRepository>();
        chart.Setup(x => x.CountAsync(It.IsAny<CancellationToken>())).ReturnsAsync(50);
        chart.Setup(x => x.GetByAccountNumberAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((string n, CancellationToken _) => Acc(n));

        var periodService = new Mock<IAccountingPeriodService>();
        periodService.Setup(x => x.EnsureOpenPeriodAsync(It.IsAny<DateTime>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((DateTime d, CancellationToken _) =>
                Result.Success(AccountingPeriod.Create(d.Year, d.Month, new DateTime(d.Year, d.Month, 1), new DateTime(d.Year, d.Month, 1).AddMonths(1).AddDays(-1))));

        var journals = new Mock<IJournalEntryRepository>();
        // T13/C6 : le service interroge désormais la garde « écriture active » (filtre !IsReversed).
        journals.Setup(x => x.GetActiveBySourceAsync(AccountingService.SourceFixedAssetDepreciation, It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(activeBySource);
        journals.Setup(x => x.ReserveNextEntryNumberAsync(It.IsAny<string>(), It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);
        var captured = new List<JournalEntry>();
        journals.Setup(x => x.AddAsync(It.IsAny<JournalEntry>(), It.IsAny<CancellationToken>()))
            .Callback<JournalEntry, CancellationToken>((e, _) => captured.Add(e))
            .ReturnsAsync((JournalEntry e, CancellationToken _) => e);

        var withholding = new Mock<IWithholdingTaxRepository>();
        var categories = new Mock<IDepreciationRateCategoryRepository>();
        var ctxFactory = new Mock<ITenantDbContextFactory>();
        var settings = Options.Create(new AccountingSettings { BrouillardEnabled = false });

        var service = new AccountingService(
            chart.Object, periodService.Object, journals.Object, withholding.Object, categories.Object,
            ctxFactory.Object, NullLogger<AccountingService>.Instance, settings);

        return (service, captured);
    }

    private static FixedAsset CreateInServiceAsset()
    {
        var asset = FixedAsset.Create(
            "IMMO-2026-0013", "Actif T13", CategoryId, 20m, 5m,
            "2244", "2824", "68112", 40_000m, 0m, 0m, new DateTime(2026, 1, 15)).Value;
        asset.PutInService(new DateTime(2026, 1, 15), "404");
        return asset;
    }

    private static DepreciationScheduleLine CreateUnpostedLine(Guid assetId, int fiscalYear, decimal amount) =>
        DepreciationScheduleLine.Create(assetId, fiscalYear, null, 40_000m, amount, 0m, amount, amount, 40_000m - amount).Value;

    /// <summary>Une écriture de dotation liée à la ligne, marquée extournée.</summary>
    private static JournalEntry CreateReversedDepreciationEntry(Guid lineId)
    {
        var lines = new[]
        {
            new JournalLineInput("68112", "Dotation", 8_000m, 0, null, ThirdPartyKind.None),
            new JournalLineInput("2824", "Amort.", 0, 8_000m, null, ThirdPartyKind.None)
        };
        var entry = JournalEntry.Create(
            10, "JO", new DateTime(2026, 12, 31), "Dotation extournée", Guid.NewGuid(),
            isAutoGenerated: true, sourceEntityType: AccountingService.SourceFixedAssetDepreciation,
            sourceEntityId: lineId, lineInputs: lines).Value;
        entry.MarkReversedBy(Guid.NewGuid());
        return entry;
    }

    /// <summary>Une écriture de dotation active (non extournée) liée à la ligne.</summary>
    private static JournalEntry CreateActiveDepreciationEntry(Guid lineId)
    {
        var lines = new[]
        {
            new JournalLineInput("68112", "Dotation", 8_000m, 0, null, ThirdPartyKind.None),
            new JournalLineInput("2824", "Amort.", 0, 8_000m, null, ThirdPartyKind.None)
        };
        return JournalEntry.Create(
            5, "JO", new DateTime(2026, 12, 31), "Dotation active", Guid.NewGuid(),
            isAutoGenerated: true, sourceEntityType: AccountingService.SourceFixedAssetDepreciation,
            sourceEntityId: lineId, lineInputs: lines).Value;
    }

    // ------------------------------------------------------------------
    // Écriture extournée → génération d'une NOUVELLE écriture (recomptabilisation)
    // ------------------------------------------------------------------

    [Fact]
    public async Task ReversedEntryOnSource_GeneratesNewEntryAndRelinksLine()
    {
        var asset = CreateInServiceAsset();
        var line = CreateUnpostedLine(asset.Id, 2026, 8_000m);
        // Ligne dé-postée après extourne : IsPosted=false, JournalEntryId pointe vers l'écriture
        // extournée (lien d'audit conservé — T13 étape 1).
        var reversedEntry = CreateReversedDepreciationEntry(line.Id);
        line.MarkPosted(reversedEntry.Id, Guid.NewGuid());
        line.Unpost(); // conserve JournalEntryId (= reversedEntry.Id)
        line.JournalEntryId.Should().Be(reversedEntry.Id);

        // La garde « écriture active » ne voit pas l'écriture extournée → null → autorise.
        var (service, captured) = BuildService(activeBySource: null);

        var result = await service.GenerateFixedAssetDepreciationEntryAsync(asset, line, cancellationToken: CancellationToken.None);

        result.IsSuccess.Should().BeTrue(result.Error?.Description);
        var newEntry = Assert.Single(captured);
        newEntry.IsReversed.Should().BeFalse("la nouvelle écriture est active");
        newEntry.SourceEntityId.Should().Be(line.Id, "même source = même ligne (identité préservée)");
        // MarkPosted a re-lié la ligne vers la nouvelle écriture active.
        line.IsPosted.Should().BeTrue();
        line.JournalEntryId.Should().Be(newEntry.Id, "le re-lien écrase le JournalEntryId de l'écriture extournée");
    }

    // ------------------------------------------------------------------
    // Écriture active → no-op (idempotence conservée)
    // ------------------------------------------------------------------

    [Fact]
    public async Task ActiveEntryOnSource_NoOp_IdempotencePreserved()
    {
        var asset = CreateInServiceAsset();
        var line = CreateUnpostedLine(asset.Id, 2026, 8_000m);
        var activeEntry = CreateActiveDepreciationEntry(line.Id);

        // La garde « écriture active » voit l'écriture active → no-op.
        var (service, captured) = BuildService(activeBySource: activeEntry);

        var result = await service.GenerateFixedAssetDepreciationEntryAsync(asset, line, cancellationToken: CancellationToken.None);

        result.IsSuccess.Should().BeTrue();
        captured.Should().BeEmpty("aucune nouvelle écriture ne doit être créée (idempotence)");
        line.IsPosted.Should().BeFalse("la ligne n'est pas re-postée par un no-op");
    }

    // ------------------------------------------------------------------
    // Deux écritures sur la même source (extournée + active) → l'active est retenue → no-op
    // ------------------------------------------------------------------

    [Fact]
    public async Task TwoEntriesOnSameSource_ReversedPlusActive_ActiveRetainedNoOp()
    {
        var asset = CreateInServiceAsset();
        var line = CreateUnpostedLine(asset.Id, 2026, 8_000m);
        var reversedEntry = CreateReversedDepreciationEntry(line.Id);
        var activeEntry = CreateActiveDepreciationEntry(line.Id);

        // GetActiveBySourceAsync filtre !IsReversed + OrderByDescending(CreatedAt) → rend l'active.
        // On simule ce comportement en ne renvoyant que l'écriture active.
        var (service, captured) = BuildService(activeBySource: activeEntry);

        var result = await service.GenerateFixedAssetDepreciationEntryAsync(asset, line, cancellationToken: CancellationToken.None);

        result.IsSuccess.Should().BeTrue();
        captured.Should().BeEmpty("l'écriture active étant présente, aucune nouvelle écriture n'est créée");
        // L'écriture extournée reste intacte et rattachée à la même source (piste d'audit complète).
        reversedEntry.IsReversed.Should().BeTrue();
    }
}
