using System.Text;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Enums;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.Services;

/// <summary>
/// C1 : le FEC est une sortie légale — il ne doit contenir que les écritures définitives
/// (validées ou clôturées), jamais les brouillons.
/// </summary>
public sealed class FecExportServiceTests
{
    private readonly string _dbName = $"FecTestDb_{Guid.NewGuid()}";
    private readonly TestTenantDbContextFactory _factory;

    public FecExportServiceTests()
    {
        _factory = new TestTenantDbContextFactory(_dbName);
    }

    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;
        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(databaseName: _databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private static JournalEntry MakeEntry(int number, string label, JournalEntryStatus status)
    {
        var lines = new[]
        {
            new JournalLineInput("4111", label, 100m, 0m, null, ThirdPartyKind.None),
            new JournalLineInput("707", label, 0m, 100m, null, ThirdPartyKind.None)
        };
        var entry = JournalEntry.Create(
            number, "JV", new DateTime(2026, 3, 15), label,
            Guid.NewGuid(), isAutoGenerated: false, sourceEntityType: "Manual", sourceEntityId: null,
            lines, initialStatus: status).Value;
        entry.SetAuditInfo("test", false);
        return entry;
    }

    private void Seed(params JournalEntry[] entries)
    {
        using var ctx = _factory.CreateContext();
        ctx.JournalEntries.AddRange(entries);
        ctx.SaveChanges();
    }

    private async Task<string> ExportAsync(int fiscalYear)
    {
        var service = new FecExportService(_factory);
        var result = await service.ExportFecAsync(fiscalYear, CancellationToken.None);
        Assert.True(result.IsSuccess);
        return Encoding.UTF8.GetString(result.Value);
    }

    [Fact]
    public async Task Export_ExcludesDraftEntries()
    {
        Seed(
            MakeEntry(1, "Vente validée", JournalEntryStatus.Validee),
            MakeEntry(2, "Vente en brouillon", JournalEntryStatus.Brouillon));

        var fec = await ExportAsync(2026);

        Assert.Contains("Vente validée", fec);
        Assert.DoesNotContain("Vente en brouillon", fec);
        // 1 en-tête + 2 lignes de l'écriture validée uniquement.
        var rows = fec.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        Assert.Equal(3, rows.Length);
    }

    [Fact]
    public async Task Export_IncludesClosedPeriodEntries()
    {
        // Après clôture de période, les écritures passent en Cloturee : elles restent légales.
        Seed(MakeEntry(1, "Vente clôturée", JournalEntryStatus.Cloturee));

        var fec = await ExportAsync(2026);

        Assert.Contains("Vente clôturée", fec);
    }

    [Fact]
    public async Task Export_UsesExternalPieceInfo_WithFallback()
    {
        // Lot B : PieceRef/PieceDate FEC = pièce externe quand renseignée, sinon n° et date d'écriture.
        // Le FEC exporte le libellé de LIGNE : on le rend distinctif pour retrouver les lignes.
        var withPiece = JournalEntry.Create(
            1, "JV", new DateTime(2026, 3, 15), "Vente avec pièce",
            Guid.NewGuid(), false, "Manual", null,
            new[]
            {
                new JournalLineInput("4111", "Vente avec pièce", 100m, 0m, null, ThirdPartyKind.None),
                new JournalLineInput("707", "Vente avec pièce", 0m, 100m, null, ThirdPartyKind.None)
            },
            pieceRef: "FACT-042", pieceDate: new DateTime(2026, 3, 10)).Value;
        withPiece.SetAuditInfo("test", false);
        Seed(withPiece, MakeEntry(2, "Vente sans pièce", JournalEntryStatus.Validee));

        var fec = await ExportAsync(2026);

        var rows = fec.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        var withPieceRow = rows.First(r => r.Contains("Vente avec pièce")).Split('\t');
        Assert.Equal("FACT-042", withPieceRow[8]);   // PieceRef
        Assert.Equal("20260310", withPieceRow[9]);   // PieceDate
        var fallbackRow = rows.First(r => r.Contains("Vente sans pièce")).Split('\t');
        Assert.Equal("2", fallbackRow[8]);           // repli : n° d'écriture
        Assert.Equal("20260315", fallbackRow[9]);    // repli : date comptable
    }

    [Fact]
    public async Task Export_AllValidated_IsUnchanged_NonRegression()
    {
        // BrouillardEnabled=false : tout naît Validee — le filtre est un no-op.
        Seed(
            MakeEntry(1, "Vente A", JournalEntryStatus.Validee),
            MakeEntry(2, "Vente B", JournalEntryStatus.Validee));

        var fec = await ExportAsync(2026);

        var rows = fec.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        Assert.Equal(5, rows.Length); // en-tête + 2 écritures × 2 lignes
        Assert.Contains("Vente A", fec);
        Assert.Contains("Vente B", fec);
    }
}
