using FactuTrust.Application.Configuration;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Enums;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Xunit;

namespace FactuTrust.Infrastructure.Tests.Services;

/// <summary>
/// GET unitaire d'une écriture : succès avec lignes + ReversesEntryId, 404 si absente.
/// Indépendant de IncludeBrouillardInReports (l'écran d'édition doit pouvoir charger un brouillon).
/// </summary>
public sealed class GetJournalEntryByIdTests
{
    private readonly string _dbName = $"GetByIdDb_{Guid.NewGuid()}";
    private readonly TestTenantDbContextFactory _factory;

    public GetJournalEntryByIdTests()
    {
        _factory = new TestTenantDbContextFactory(_dbName);
    }

    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;
        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(databaseName: _databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    private static IReadOnlyList<JournalLineInput> SaleLines(decimal amount = 100m) => new[]
    {
        new JournalLineInput("4111", "Client", amount, 0, null, ThirdPartyKind.None),
        new JournalLineInput("707", "Ventes", 0, amount, null, ThirdPartyKind.None)
    };

    private static IReadOnlyList<JournalLineInput> MirrorLines(decimal amount = 100m) => new[]
    {
        new JournalLineInput("4111", "Client", 0, amount, null, ThirdPartyKind.None),
        new JournalLineInput("707", "Ventes", amount, 0, null, ThirdPartyKind.None)
    };

    private AccountingReportingService BuildService()
        => new(_factory, Options.Create(new AccountingSettings { IncludeBrouillardInReports = false }));

    [Fact]
    public async Task GetById_Missing_ReturnsNotFound()
    {
        var result = await BuildService().GetJournalEntryByIdAsync(Guid.NewGuid());

        Assert.True(result.IsFailure);
        Assert.Contains("NotFound", result.Error.Code);
    }

    [Fact]
    public async Task GetById_Draft_ReturnsLinesEvenWhenReportsExcludeDrafts()
    {
        var draft = JournalEntry.Create(6, "JV", new DateTime(2026, 8, 14), "Client — FAC-2026-000019",
            Guid.NewGuid(), true, "Invoice", Guid.NewGuid(), SaleLines(250m),
            initialStatus: JournalEntryStatus.Brouillon).Value;
        draft.SetAuditInfo("test", false);
        using (var ctx = _factory.CreateContext())
        {
            ctx.JournalEntries.Add(draft);
            ctx.SaveChanges();
        }

        var result = await BuildService().GetJournalEntryByIdAsync(draft.Id);

        Assert.True(result.IsSuccess);
        Assert.Equal(draft.Id, result.Value.Id);
        Assert.Equal(6, result.Value.EntryNumber);
        Assert.Equal("JV", result.Value.JournalCode);
        Assert.True(result.Value.IsDraft);
        Assert.True(result.Value.IsAutoGenerated);
        Assert.Equal("Invoice", result.Value.SourceEntityType);
        Assert.Null(result.Value.ReversesEntryId);
        Assert.Equal(2, result.Value.Lines.Count);
        Assert.Equal("4111", result.Value.Lines[0].AccountNumber);
        Assert.Equal(250m, result.Value.Lines[0].Debit);
    }

    [Fact]
    public async Task GetById_Reversal_ExposesReversesEntryId()
    {
        var original = JournalEntry.Create(1, "JV", new DateTime(2026, 8, 10), "Vente",
            Guid.NewGuid(), false, "Manual", null, SaleLines(),
            initialStatus: JournalEntryStatus.Validee).Value;
        original.SetAuditInfo("test", false);

        var reversal = JournalEntry.Create(2, "JV", new DateTime(2026, 8, 10), "Extourne JV-1",
            original.AccountingPeriodId, false, "ManualReversal", original.Id, MirrorLines(),
            reversesEntryId: original.Id, initialStatus: JournalEntryStatus.Brouillon).Value;
        reversal.SetAuditInfo("test", false);

        using (var ctx = _factory.CreateContext())
        {
            ctx.JournalEntries.AddRange(original, reversal);
            ctx.SaveChanges();
        }

        var result = await BuildService().GetJournalEntryByIdAsync(reversal.Id);

        Assert.True(result.IsSuccess);
        Assert.Equal(original.Id, result.Value.ReversesEntryId);
        Assert.True(result.Value.IsDraft);
    }
}
