// <auto-generated />
using FactuTrust.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System.Reflection;

#nullable disable

namespace FactuTrust.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260409134141_AddChannelIngressSupport_Tenant")]
    partial class AddChannelIngressSupport_Tenant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var migration = new AddCashOperationOriginTracking();
            var buildTargetModel = typeof(AddCashOperationOriginTracking).GetMethod(
                "BuildTargetModel",
                BindingFlags.Instance | BindingFlags.NonPublic);
            buildTargetModel?.Invoke(migration, new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
