using FactuTrust.Domain.Common;
using FactuTrust.Domain.Enums;

namespace FactuTrust.Domain.Entities.Payroll;

/// <summary>
/// Prime ou indemnité variable saisie pour un salarié sur un mois de paie (hors contrat récurrent).
/// </summary>
public sealed class PayrollVariableAllowanceLine : AggregateRoot
{
    public Guid EmployeeId { get; private set; }
    public int Year { get; private set; }
    public int Month { get; private set; }
    public string Label { get; private set; } = null!;
    public decimal Amount { get; private set; }
    public bool Taxable { get; private set; }
    public bool SubjectToCnss { get; private set; }
    public VariableAllowanceSource Source { get; private set; }
    /// <summary>Règle de prime annuelle à l'origine de la ligne auto-générée.</summary>
    public Guid? AnnualBonusRuleId { get; private set; }

    private PayrollVariableAllowanceLine() { }

    public static Result<PayrollVariableAllowanceLine> Create(
        Guid employeeId,
        int year,
        int month,
        string label,
        decimal amount,
        bool taxable,
        bool subjectToCnss,
        VariableAllowanceSource source = VariableAllowanceSource.Manual,
        Guid? annualBonusRuleId = null)
    {
        if (employeeId == Guid.Empty)
            return Result.Failure<PayrollVariableAllowanceLine>(Error.Validation("EmployeeId", "Le salarié est obligatoire."));
        if (year < 2000 || year > 2100)
            return Result.Failure<PayrollVariableAllowanceLine>(Error.Validation("Year", "Année invalide."));
        if (month is < 1 or > 12)
            return Result.Failure<PayrollVariableAllowanceLine>(Error.Validation("Month", "Mois invalide."));
        if (string.IsNullOrWhiteSpace(label))
            return Result.Failure<PayrollVariableAllowanceLine>(Error.Validation("Label", "Le libellé de la prime est obligatoire."));
        if (amount <= 0)
            return Result.Failure<PayrollVariableAllowanceLine>(Error.Validation("Amount", "Le montant de la prime doit être strictement positif."));

        return Result.Success(new PayrollVariableAllowanceLine
        {
            EmployeeId = employeeId,
            Year = year,
            Month = month,
            Label = label.Trim(),
            Amount = Math.Round(amount, 3, MidpointRounding.AwayFromZero),
            Taxable = taxable,
            SubjectToCnss = subjectToCnss,
            Source = source,
            AnnualBonusRuleId = annualBonusRuleId
        });
    }

    public Result Update(string label, decimal amount, bool taxable, bool subjectToCnss)
    {
        if (string.IsNullOrWhiteSpace(label))
            return Result.Failure(Error.Validation("Label", "Le libellé de la prime est obligatoire."));
        if (Source == VariableAllowanceSource.AutoAnnualBonus)
            return Result.Failure(Error.Validation("Source", "Les primes annuelles auto-générées se modifient via les paramètres ou le recalcul de paie."));

        if (amount <= 0)
            return Result.Failure(Error.Validation("Amount", "Le montant de la prime doit être strictement positif."));

        Label = label.Trim();
        Amount = Math.Round(amount, 3, MidpointRounding.AwayFromZero);
        Taxable = taxable;
        SubjectToCnss = subjectToCnss;
        IncrementVersion();
        return Result.Success();
    }

    /// <summary>Met à jour une ligne auto-générée (recalcul de paie idempotent).</summary>
    public Result RefreshAutoGenerated(decimal amount, bool taxable, bool subjectToCnss, string label)
    {
        if (amount <= 0)
            return Result.Failure(Error.Validation("Amount", "Le montant de la prime doit être strictement positif."));

        Label = label.Trim();
        Amount = Math.Round(amount, 3, MidpointRounding.AwayFromZero);
        Taxable = taxable;
        SubjectToCnss = subjectToCnss;
        IncrementVersion();
        return Result.Success();
    }
}
