using FactuTrust.Application.Common.Interfaces.Repositories;
using FactuTrust.Application.Configuration;
using FactuTrust.Domain.Entities.Payroll;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.Services.Payroll;
using Microsoft.Extensions.Options;

namespace FactuTrust.Application.Features.Payroll.AnnualBonuses;

/// <summary>
/// Synchronise les lignes de primes variables auto-générées avant le calcul de paie (idempotent).
/// </summary>
public sealed class AnnualBonusSyncService
{
    private readonly IAnnualBonusRuleRepository _rules;
    private readonly IEmployeeAnnualBonusRuleRepository _assignments;
    private readonly IEmployeeRepository _employees;
    private readonly IPayrollVariableAllowanceRepository _variableAllowances;
    private readonly IPayrollRunRepository _runs;
    private readonly AccountingSettings _settings;

    public AnnualBonusSyncService(
        IAnnualBonusRuleRepository rules,
        IEmployeeAnnualBonusRuleRepository assignments,
        IEmployeeRepository employees,
        IPayrollVariableAllowanceRepository variableAllowances,
        IPayrollRunRepository runs,
        IOptions<AccountingSettings> settings)
    {
        _rules = rules;
        _assignments = assignments;
        _employees = employees;
        _variableAllowances = variableAllowances;
        _runs = runs;
        _settings = settings.Value;
    }

    public async Task SyncForMonthAsync(int year, int month, CancellationToken cancellationToken = default)
    {
        if (!_settings.PayrollAnnualBonusesEnabled)
            return;

        if (await _runs.HasValidatedOrClosedRunForMonthAsync(year, month, cancellationToken))
            return;

        var rules = await _rules.ListAsync(year, cancellationToken);
        var assignments = await _assignments.ListActiveAsync(cancellationToken);
        var employees = await _employees.GetActiveWithContractsAsync(cancellationToken);

        var resolved = AnnualBonusResolver.ResolveForMonth(year, month, rules, assignments, employees);
        var existingAuto = await _variableAllowances.ListAutoAnnualBonusForMonthAsync(year, month, cancellationToken);
        var existingByKey = existingAuto.ToDictionary(l => (l.EmployeeId, l.AnnualBonusRuleId!.Value));

        var added = new List<PayrollVariableAllowanceLine>();
        var updated = new List<PayrollVariableAllowanceLine>();

        foreach (var line in resolved)
        {
            if (existingByKey.TryGetValue((line.EmployeeId, line.RuleId), out var existing))
            {
                existing.RefreshAutoGenerated(line.Amount, line.Taxable, line.SubjectToCnss, line.Label);
                updated.Add(existing);
                existingByKey.Remove((line.EmployeeId, line.RuleId));
            }
            else
            {
                var create = PayrollVariableAllowanceLine.Create(
                    line.EmployeeId, year, month, line.Label, line.Amount,
                    line.Taxable, line.SubjectToCnss, VariableAllowanceSource.AutoAnnualBonus, line.RuleId);
                if (create.IsSuccess)
                    added.Add(create.Value);
            }
        }

        if (added.Count > 0 || updated.Count > 0)
            await _variableAllowances.SaveBatchAsync(added, updated, cancellationToken);
    }
}
