using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Audit;
using FactuTrust.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace FactuTrust.Infrastructure.Services.AccountingAudit.Rules;

/// <summary>Écritures validées sans pièce jointe (GED).</summary>
public sealed class MissingAttachmentsAuditRule : AccountingAuditRuleBase
{
    public override string Code => "entry-missing-attachment";
    public override string ModuleCode => "documents";
    public override int Category => (int)AnomalyCategory.Documents;
    public override int DefaultSeverity => (int)PreClosingSeverity.Blocking;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var entriesWithAttachments = await c.Db.JournalEntryAttachments.AsNoTracking()
            .Select(a => a.JournalEntryId)
            .Distinct()
            .ToListAsync(cancellationToken);
        var attachmentSet = new HashSet<Guid>(entriesWithAttachments);

        var entries = await c.Db.JournalEntries.AsNoTracking()
            .Where(e => e.EntryDate.Year == ctx.FiscalYear
                        && e.Status != JournalEntryStatus.Brouillon
                        && !e.IsAutoGenerated)
            .Select(e => new { e.Id, e.EntryDate, e.JournalCode, e.EntryNumber, e.Label })
            .ToListAsync(cancellationToken);

        var missing = entries.Where(e => !attachmentSet.Contains(e.Id)).Take(500).ToList();
        if (missing.Count == 0) return Array.Empty<AnomalyCandidate>();

        var total = entries.Count(e => !attachmentSet.Contains(e.Id));
        return
        [
            SingleGroup(Code, ModuleCode, Category, DefaultSeverity,
                "Écritures sans justificatif",
                $"{total} écriture(s) manuelle(s) sans pièce jointe.",
                "Risque de non-conformité en cas de contrôle fiscal.",
                null, 0, null, null,
                missing.Select(e => new AnomalyLineCandidate(
                    e.Id, null, e.EntryDate, null, e.Label, 0, 0, $"{e.JournalCode}-{e.EntryNumber}", "Absente")).ToList(),
                ["Joindre les pièces justificatives.", "Compléter les libellés."],
                "/accounting/journal")
        ];
    }
}

/// <summary>TVA déductible sur lignes sans justificatif associé à l'écriture.</summary>
public sealed class VatDeductibleNoProofAuditRule : AccountingAuditRuleBase
{
    public override string Code => "vat-deductible-no-proof";
    public override string ModuleCode => "vat";
    public override int Category => (int)AnomalyCategory.Tva;
    public override int DefaultSeverity => (int)PreClosingSeverity.Warning;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var entriesWithAttachments = await c.Db.JournalEntryAttachments.AsNoTracking()
            .Select(a => a.JournalEntryId)
            .Distinct()
            .ToListAsync(cancellationToken);
        var attachmentSet = new HashSet<Guid>(entriesWithAttachments);

        var vatLines = await c.Db.JournalEntryLines.AsNoTracking()
            .Include(l => l.JournalEntry)
            .Where(l => (l.AccountNumber.StartsWith("43662") || l.AccountNumber.StartsWith("43663"))
                        && l.JournalEntry.EntryDate.Year == ctx.FiscalYear
                        && l.JournalEntry.Status != JournalEntryStatus.Brouillon
                        && l.DebitAmount.Amount > 0)
            .Select(l => new
            {
                l.Id,
                l.JournalEntryId,
                l.JournalEntry.EntryDate,
                l.AccountNumber,
                l.Label,
                Debit = l.DebitAmount.Amount
            })
            .ToListAsync(cancellationToken);

        var missing = vatLines.Where(l => !attachmentSet.Contains(l.JournalEntryId)).ToList();
        if (missing.Count == 0) return Array.Empty<AnomalyCandidate>();

        return
        [
            SingleGroup(Code, ModuleCode, Category, DefaultSeverity,
                "TVA déductible sans justificatif",
                $"{missing.Count} ligne(s) de TVA déductible sans pièce jointe.",
                "Risque de rejet de la déduction TVA.",
                "4366", missing.Sum(l => l.Debit), null, null,
                missing.Select(l => new AnomalyLineCandidate(
                    l.JournalEntryId, l.Id, l.EntryDate, l.AccountNumber, l.Label, l.Debit, 0, null, "Absente")).ToList(),
                ["Joindre la facture fournisseur.", "Vérifier le montant de TVA déductible."],
                "/accounting/vat-declaration")
        ];
    }
}

/// <summary>Lignes de relevé bancaire non rapprochées en fin de période.</summary>
public sealed class BankReconciliationIncompleteAuditRule : AccountingAuditRuleBase
{
    public override string Code => "recon-bank-incomplete";
    public override string ModuleCode => "bank";
    public override int Category => (int)AnomalyCategory.Rapprochement;
    public override int DefaultSeverity => (int)PreClosingSeverity.Warning;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var unmatched = await c.Db.BankStatementLines.AsNoTracking()
            .Include(l => l.BankStatement)
            .Where(l => l.TransactionDate.Year == ctx.FiscalYear
                        && !l.IsReconciled)
            .Select(l => new
            {
                l.Id,
                l.TransactionDate,
                Label = l.Description,
                Amount = l.Amount.Amount,
                l.Reference
            })
            .Take(500)
            .ToListAsync(cancellationToken);
        if (unmatched.Count == 0) return Array.Empty<AnomalyCandidate>();

        var total = await c.Db.BankStatementLines.AsNoTracking()
            .CountAsync(l => l.TransactionDate.Year == ctx.FiscalYear && !l.IsReconciled, cancellationToken);

        return
        [
            SingleGroup(Code, ModuleCode, Category, DefaultSeverity,
                "Rapprochement bancaire incomplet",
                $"{total} ligne(s) de relevé non rapprochée(s).",
                "Écart de trésorerie non expliqué.",
                "512", unmatched.Sum(l => Math.Abs(l.Amount)), null, null,
                unmatched.Select(l => new AnomalyLineCandidate(
                    null, null, l.TransactionDate, "512", l.Label, l.Amount > 0 ? l.Amount : 0, l.Amount < 0 ? -l.Amount : 0, l.Reference, null)).ToList(),
                ["Rapprocher les lignes de relevé.", "Créer les écritures manquantes."],
                "/accounting/bank-reconciliation")
        ];
    }
}
