using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Audit;
using FactuTrust.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace FactuTrust.Infrastructure.Services.AccountingAudit.Rules;

/// <summary>
/// Compte auxiliaire salarié mal formé.
/// </summary>
/// <remarks>
/// <para>Les sous-comptes de 425 tiennent la dette de salaire d'un salarié donné. Deux défauts les
/// rendent inexploitables comme comptes de tiers, sans pour autant fausser un état financier — d'où
/// la nécessité de les signaler, faute de quoi ils passent inaperçus.</para>
/// <para><b>Non typés</b> : sans <c>IsAuxiliary</c> ni compte d'affectation, ils sont des comptes
/// généraux de fait — le plan tiers ne les reconnaît pas et le FEC n'a pas de code auxiliaire à
/// exporter.</para>
/// <para><b>Libellé auto-généré</b> : un libellé portant encore une longue séquence de chiffres est
/// le vestige de l'auto-création (« Personnel et comptes rattachés — 421 — 4218744456 ») ; il
/// n'identifie aucun salarié, et cite même un numéro de compte périmé quand il précède le remap
/// NCT 01, qui a réécrit les numéros sans toucher aux libellés.</para>
/// <para>Correction : <c>docs/runbooks/sql/RequalifyPayrollAuxiliaryAccounts.idempotent.sql</c>.</para>
/// </remarks>
public sealed class PayrollAuxiliaryAccountShapeAuditRule : AccountingAuditRuleBase
{
    /// <summary>Compte collectif « Personnel - rémunérations dues » (NCT 01).</summary>
    private const string CollectiveAccount = "425";

    /// <summary>
    /// Longueur d'une suite de chiffres trahissant un libellé auto-généré. Sept, pour ne pas
    /// signaler un libellé métier légitime qui citerait un matricule court.
    /// </summary>
    private const int AutoLabelDigitRun = 7;

    public override string Code => "health-payroll-auxiliary-shape";
    public override string ModuleCode => "integrity";
    public override int Category => (int)AnomalyCategory.Comptes;
    public override int DefaultSeverity => (int)PreClosingSeverity.Warning;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();

        var candidates = await c.Db.ChartOfAccounts.AsNoTracking()
            .Where(a => !a.IsSystem
                        && a.AccountNumber.StartsWith(CollectiveAccount)
                        && a.AccountNumber != CollectiveAccount)
            .Select(a => new
            {
                a.AccountNumber,
                a.Label,
                a.IsAuxiliary,
                a.AffectationAccountNumber
            })
            .ToListAsync(cancellationToken);

        var findings = new List<(string Account, string Label, string Reason)>();

        foreach (var account in candidates)
        {
            var reasons = new List<string>();

            if (!account.IsAuxiliary
                || !string.Equals(account.AffectationAccountNumber, CollectiveAccount, StringComparison.Ordinal))
            {
                reasons.Add($"non rattaché au collectif {CollectiveAccount}");
            }

            if (HasAutoGeneratedLabel(account.Label))
                reasons.Add("libellé auto-généré (aucun nom de salarié)");

            if (reasons.Count > 0)
                findings.Add((account.AccountNumber, account.Label, string.Join(", ", reasons)));
        }

        if (findings.Count == 0) return Array.Empty<AnomalyCandidate>();

        return
        [
            SingleGroup(Code, ModuleCode, Category, DefaultSeverity,
                "Comptes auxiliaires salariés mal formés",
                $"{findings.Count} sous-compte(s) de {CollectiveAccount} ne sont pas exploitables comme "
                + "comptes de tiers.",
                "Plan tiers, balance auxiliaire et FEC ne peuvent pas rattacher ces comptes à un salarié.",
                accountRef: CollectiveAccount,
                amount: findings.Count,
                periodFrom: null,
                periodTo: null,
                lines: findings.Select(f => new AnomalyLineCandidate(
                    null, null, null, f.Account, $"{f.Label} — {f.Reason}", 0, 0, null, null)).ToList(),
                recommendations:
                [
                    "Exécuter docs/runbooks/sql/RequalifyPayrollAuxiliaryAccounts.idempotent.sql.",
                    "À défaut, renommer le compte du nom du salarié et le marquer auxiliaire de 425."
                ],
                deepLinkRoute: "/accounting/chart")
        ];
    }

    /// <summary>Vrai si le libellé porte une suite d'au moins sept chiffres.</summary>
    private static bool HasAutoGeneratedLabel(string? label)
    {
        if (string.IsNullOrWhiteSpace(label)) return true;

        var run = 0;
        foreach (var ch in label)
        {
            run = char.IsAsciiDigit(ch) ? run + 1 : 0;
            if (run >= AutoLabelDigitRun) return true;
        }

        return false;
    }
}

public sealed class OrphanAccountsAuditRule : AccountingAuditRuleBase
{
    public override string Code => "health-orphan-accounts";
    public override string ModuleCode => "integrity";
    public override int Category => (int)AnomalyCategory.Comptes;
    public override int DefaultSeverity => (int)PreClosingSeverity.Blocking;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var usedAccounts = await c.Db.JournalEntryLines.AsNoTracking()
            .Include(l => l.JournalEntry)
            .Where(l => l.JournalEntry.EntryDate.Year == ctx.FiscalYear)
            .Select(l => l.AccountNumber)
            .Distinct()
            .ToListAsync(cancellationToken);
        var chartAccounts = await c.Db.ChartOfAccounts.AsNoTracking()
            .Select(a => a.AccountNumber)
            .ToListAsync(cancellationToken);
        var chartSet = new HashSet<string>(chartAccounts, StringComparer.Ordinal);
        var orphans = usedAccounts.Where(a => !chartSet.Contains(a)).ToList();
        if (orphans.Count == 0) return Array.Empty<AnomalyCandidate>();

        return orphans.Select(account => SingleGroup(
            Code, ModuleCode, Category, DefaultSeverity,
            "Compte hors plan comptable",
            $"Le compte {account} est mouvementé mais absent du plan comptable.",
            "Risque d'erreur sur les états et non-conformité.",
            account, 0, null, null,
            [new AnomalyLineCandidate(null, null, null, account, "Compte orphelin", 0, 0, null, null)],
            ["Créer le compte dans le plan comptable.", "Remplacer le compte sur les écritures."],
            "/accounting/chart")).ToList();
    }
}

public sealed class OutOfPeriodAuditRule : AccountingAuditRuleBase
{
    public override string Code => "health-out-of-period";
    public override string ModuleCode => "integrity";
    public override int Category => (int)AnomalyCategory.Ecritures;
    public override int DefaultSeverity => (int)PreClosingSeverity.Warning;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var periods = await c.Db.AccountingPeriods.AsNoTracking()
            .Select(p => new { p.StartDate, p.EndDate })
            .ToListAsync(cancellationToken);
        var entries = await c.Db.JournalEntries.AsNoTracking()
            .Where(e => e.EntryDate.Year == ctx.FiscalYear)
            .Select(e => new { e.Id, e.EntryDate, e.JournalCode, e.EntryNumber, e.Label })
            .ToListAsync(cancellationToken);
        var outOfPeriod = entries
            .Where(e => !periods.Any(p => p.StartDate <= e.EntryDate && e.EntryDate <= p.EndDate))
            .ToList();
        if (outOfPeriod.Count == 0) return Array.Empty<AnomalyCandidate>();

        return
        [
            SingleGroup(Code, ModuleCode, Category, DefaultSeverity,
                "Écritures hors période",
                $"{outOfPeriod.Count} écriture(s) hors période comptable.",
                "Les écritures doivent être rattachées à une période ouverte ou clôturée.",
                null, 0, null, null,
                outOfPeriod.Select(e => new AnomalyLineCandidate(
                    e.Id, null, e.EntryDate, null, e.Label, 0, 0, $"{e.JournalCode}-{e.EntryNumber}", null)).ToList(),
                ["Créer la période comptable manquante.", "Corriger la date de l'écriture."],
                "/accounting/closing")
        ];
    }
}

public sealed class PieceDuplicatesAuditRule : AccountingAuditRuleBase
{
    public override string Code => "health-piece-duplicates";
    public override string ModuleCode => "integrity";
    public override int Category => (int)AnomalyCategory.Ecritures;
    public override int DefaultSeverity => (int)PreClosingSeverity.Warning;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var duplicates = await c.Db.JournalEntries.AsNoTracking()
            .Where(e => e.EntryDate.Year == ctx.FiscalYear)
            .GroupBy(e => new { e.JournalCode, e.EntryNumber })
            .Where(g => g.Count() > 1)
            .Select(g => new { g.Key.JournalCode, g.Key.EntryNumber, Count = g.Count() })
            .ToListAsync(cancellationToken);
        if (duplicates.Count == 0) return Array.Empty<AnomalyCandidate>();

        var results = new List<AnomalyCandidate>();
        foreach (var d in duplicates)
        {
            var entries = await c.Db.JournalEntries.AsNoTracking()
                .Include(e => e.Lines)
                .Where(e => e.EntryDate.Year == ctx.FiscalYear
                            && e.JournalCode == d.JournalCode
                            && e.EntryNumber == d.EntryNumber)
                .ToListAsync(cancellationToken);

            var lines = entries.Select(e =>
            {
                var debit = e.Lines.Sum(l => l.DebitAmount.Amount);
                var credit = e.Lines.Sum(l => l.CreditAmount.Amount);
                return new AnomalyLineCandidate(
                    e.Id, null, e.EntryDate, null, e.Label, debit, credit,
                    $"{e.JournalCode}-{e.EntryNumber}", null);
            }).ToList();

            results.Add(SingleGroup(
                Code, ModuleCode, Category, DefaultSeverity,
                "Doublon de numéro de pièce",
                $"Journal {d.JournalCode} — pièce {d.EntryNumber} en {d.Count} exemplaires.",
                "Risque de confusion et d'audit défavorable.",
                null, entries.Sum(e => e.Lines.Sum(l => l.DebitAmount.Amount + l.CreditAmount.Amount)), null, null,
                lines,
                ["Identifier la pièce correcte.", "Renommer ou supprimer le doublon."],
                "/accounting/entry-search"));
        }

        return results;
    }
}

public sealed class ThirdPartyMislinkAuditRule : AccountingAuditRuleBase
{
    public override string Code => "health-thirdparty-mislink";
    public override string ModuleCode => "integrity";
    public override int Category => (int)AnomalyCategory.Comptes;
    public override int DefaultSeverity => (int)PreClosingSeverity.Info;

    public override async Task<IReadOnlyList<AnomalyCandidate>> EvaluateAsync(
        IAuditEvaluationContext ctx, CancellationToken cancellationToken)
    {
        var c = ctx.Ctx();
        var lines = await c.Db.JournalEntryLines.AsNoTracking()
            .Include(l => l.JournalEntry)
            .Where(l => l.JournalEntry.EntryDate.Year == ctx.FiscalYear
                        && l.ThirdPartyId != null
                        && !l.AccountNumber.StartsWith("41")
                        && !l.AccountNumber.StartsWith("40"))
            .Select(l => new { l.Id, l.JournalEntryId, l.JournalEntry.EntryDate, l.AccountNumber, l.Label, Debit = l.DebitAmount.Amount, Credit = l.CreditAmount.Amount })
            .Take(200)
            .ToListAsync(cancellationToken);
        if (lines.Count == 0) return Array.Empty<AnomalyCandidate>();

        var total = await c.Db.JournalEntryLines.AsNoTracking()
            .Include(l => l.JournalEntry)
            .CountAsync(l => l.JournalEntry.EntryDate.Year == ctx.FiscalYear
                             && l.ThirdPartyId != null
                             && !l.AccountNumber.StartsWith("41")
                             && !l.AccountNumber.StartsWith("40"), cancellationToken);

        return
        [
            SingleGroup(Code, ModuleCode, Category, DefaultSeverity,
                "Tiers sur compte non auxiliarisable",
                $"{total} ligne(s) avec tiers sur compte hors 40/41.",
                "Les tiers doivent être sur des comptes clients/fournisseurs.",
                null, lines.Sum(l => l.Debit + l.Credit), null, null,
                lines.Select(l => new AnomalyLineCandidate(l.JournalEntryId, l.Id, l.EntryDate, l.AccountNumber, l.Label, l.Debit, l.Credit, null, null)).ToList(),
                ["Corriger le compte ou retirer le tiers.", "Utiliser le plan tiers."],
                "/accounting/entry-search")
        ];
    }
}
