# -*- coding: utf-8 -*-
"""Build NCT 01 catalog + remap JSON from the official nomenclature (PDF + corrections + overlay)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "accounting"
RES = ROOT / "src" / "Backend" / "FactuTrust.Infrastructure" / "Resources" / "Accounting"

# (number, label) — NCT 01 tree (PDF) with label corrections.
NCT_ACCOUNTS: list[tuple[str, str]] = [
    # Classe 1
    ("10", "Capital"),
    ("101", "Capital social"),
    ("1011", "Capital souscrit - non appelé"),
    ("1012", "Capital souscrit - appelé, non versé"),
    ("1013", "Capital souscrit - appelé, versé"),
    ("10131", "Capital non amorti"),
    ("10132", "Capital amorti"),
    ("1018", "Capital souscrit soumis à une réglementation particulière"),
    ("105", "Fonds de dotation"),
    ("108", "Compte de l'exploitant"),
    ("109", "Actionnaires, capital souscrit - non appelé"),
    ("11", "Réserves et primes liées au capital"),
    ("111", "Réserve légale"),
    ("112", "Réserves statutaires"),
    ("117", "Primes liées au capital"),
    ("1171", "Primes d'émission"),
    ("1172", "Primes de fusion"),
    ("1173", "Primes d'apport"),
    ("1174", "Primes de conversion d'obligation"),
    ("1178", "Autres compléments d'apport"),
    ("118", "Autres réserves"),
    ("1181", "Réserves pour fonds social"),
    ("119", "Actions propres"),
    ("12", "Résultats reportés"),
    ("121", "Résultats reportés"),
    ("128", "Modifications comptables affectant les résultats reportés"),
    ("13", "Résultat de l'exercice"),
    ("131", "Résultat bénéficiaire"),
    ("135", "Résultat déficitaire"),
    ("14", "Autres capitaux propres"),
    ("141", "Titres soumis à des réglementations particulières"),
    ("142", "Réserves réglementées & réserves soumises à un régime fiscal particulier"),
    ("1421", "Réserves indisponibles"),
    ("143", "Amortissements dérogatoires"),
    ("144", "Réserve spéciale de réévaluation"),
    ("145", "Subventions d'investissement"),
    ("1451", "Subventions d'investissement"),
    ("1458", "Autres subventions d'investissement"),
    ("1459", "Subventions d'investissement inscrites aux comptes de résultat"),
    ("147", "Compte du concédant"),
    ("15", "Provisions pour risques & charges"),
    ("151", "Provisions pour risques"),
    ("1511", "Provisions pour litiges"),
    ("1512", "Provisions pour garanties données aux clients"),
    ("1513", "Provisions pour pertes sur marchés à achèvement futur"),
    ("1514", "Provisions pour amendes & pénalités"),
    ("1515", "Provisions pour pertes de change"),
    ("1518", "Autres provisions pour risques"),
    ("152", "Provisions pour charges à répartir sur plusieurs exercices"),
    ("1522", "Provisions pour grosses réparations"),
    ("153", "Provisions pour retraites et obligations similaires"),
    ("154", "Provisions d'origine réglementaire"),
    ("155", "Provisions pour impôts"),
    ("156", "Provisions pour renouvellement des immobilisations"),
    ("157", "Provisions pour amortissement"),
    ("158", "Autres provisions pour charges"),
    ("16", "Emprunts & dettes assimilées"),
    ("161", "Emprunts obligataires (assorties de sûretés)"),
    ("1611", "Emprunts obligataires convertibles en actions"),
    ("1618", "Autres emprunts obligataires"),
    ("162", "Emprunts auprès des établissements financiers (assorties de sûretés)"),
    ("1621", "Emprunts bancaires"),
    ("1626", "Refinancements acquis"),
    ("163", "Emprunts auprès d'autres établissements financiers (assorties de sûretés)"),
    ("164", "Emprunts et dettes assorties de conditions particulières"),
    ("1641", "Avances bloquées pour augmentation du capital"),
    ("1642", "Avances reçues et comptes courants des associés bloqués"),
    ("1644", "Avances conditionnées de l'Etat & organismes internationaux"),
    ("165", "Emprunts non assorties de sûretés"),
    ("166", "Dettes rattachées à des participations"),
    ("1661", "Dettes rattachées à des participations (groupe)"),
    ("1662", "Dettes rattachées à des participations (hors groupe)"),
    ("1663", "Dettes rattachées à des sociétés en participation"),
    ("167", "Dépôts & cautionnements reçus"),
    ("168", "Autres emprunts et dettes"),
    ("1681", "Autres emprunts"),
    ("1685", "Crédit fournisseurs d'immobilisations"),
    ("1687", "Dettes de crédit-bail et assimilées"),
    ("1688", "Autres dettes non courantes"),
    ("17", "Comptes de liaison des établissements & succursales"),
    ("171", "Comptes de liaison des établissements"),
    ("176", "Biens & prestations de services échangés entre établissements (charges)"),
    ("177", "Biens & prestations de services échangés entre établissements (produits)"),
    ("18", "Autres passifs non courants"),
    ("185", "Écarts de conversion"),
    ("188", "Autres"),
    # Classe 2
    ("21", "Immobilisations incorporelles"),
    ("211", "Investissements de recherche & de développement"),
    ("212", "Concessions de marques, brevets, licences, procédés & valeurs similaires"),
    ("213", "Logiciels"),
    ("214", "Fonds commercial"),
    ("216", "Droit au bail"),
    ("218", "Autres immobilisations incorporelles"),
    ("22", "Immobilisations corporelles"),
    ("221", "Terrains"),
    ("2213", "Terrains nus"),
    ("2214", "Terrains aménagés"),
    ("2215", "Terrains bâtis"),
    ("2216", "Agencements & aménagements des terrains"),
    ("222", "Constructions"),
    ("2221", "Bâtiments"),
    ("2225", "Installations générales, agencements & aménagements des constructions"),
    ("2226", "Ouvrages d'infrastructure"),
    ("2227", "Constructions sur sol d'autrui"),
    ("223", "Installations techniques, matériel et outillage industriels"),
    ("2231", "Installations techniques"),
    ("2234", "Matériel industriel"),
    ("2235", "Outillage industriel"),
    ("2237", "Agencements & aménagements du matériel & outillage industriels"),
    ("224", "Matériel de transport"),
    ("2241", "Matériel de transport de biens"),
    ("2244", "Matériel de transport de personnes"),
    ("228", "Autres immobilisations corporelles"),
    ("2281", "Installations générales, agencements et aménagements divers"),
    ("2282", "Équipement de bureau"),
    ("2286", "Emballages récupérables identifiables"),
    ("23", "Immobilisations en cours"),
    ("231", "Immobilisations incorporelles en cours"),
    ("232", "Immobilisations corporelles en cours"),
    ("237", "Avances & acomptes versés sur immobilisations incorporelles"),
    ("238", "Avances & acomptes versés sur commandes d'immobilisations corporelles"),
    ("24", "Immobilisations à statut juridique particulier"),
    ("25", "Participations & créances liées à des participations"),
    ("251", "Titres de participation"),
    ("2511", "Actions"),
    ("2518", "Autres titres"),
    ("256", "Autres formes de participation"),
    ("257", "Créances rattachées à des participations"),
    ("2571", "Créances rattachées à des participations (groupe)"),
    ("2574", "Créances rattachées à des participations (hors groupe)"),
    ("2575", "Versements représentatifs d'apports non capitalisés (appel de fonds)"),
    ("2576", "Avances consolidables"),
    ("2577", "Autres créances rattachées à des participations"),
    ("258", "Créances rattachées à des sociétés en participation"),
    ("259", "Versements restant à effectuer sur titres de participation non libérés"),
    ("26", "Autres immobilisations financières"),
    ("261", "Titres immobilisés (droit de propriété)"),
    ("2611", "Actions"),
    ("2618", "Autres titres"),
    ("262", "Titres immobilisés (droit de créance)"),
    ("2621", "Obligations"),
    ("2622", "Bons"),
    ("264", "Prêts"),
    ("2641", "Prêts participatifs"),
    ("2642", "Prêts aux associés"),
    ("2643", "Prêts au personnel"),
    ("2645", "Prêts assortis de sûretés"),
    ("2648", "Autres prêts"),
    ("265", "Dépôts et cautionnements versés"),
    ("2651", "Dépôts"),
    ("2655", "Cautionnements"),
    ("2656", "Dépôts bancaires non courants"),
    ("2658", "Autres"),
    ("266", "Autres créances immobilisées"),
    ("2661", "Créances immobilisées"),
    ("2667", "Créances diverses"),
    ("2668", "Autres créances non courantes"),
    ("269", "Versements restant à effectuer sur titres immobilisés non libérés"),
    ("27", "Autres actifs non courants"),
    ("271", "Frais préliminaires"),
    ("272", "Charges à répartir"),
    ("273", "Frais d'émission et primes de remboursement des emprunts"),
    ("275", "Écarts de conversion"),
    ("278", "Autres"),
    ("28", "Amortissements des immobilisations"),
    ("281", "Amortissements des immobilisations incorporelles"),
    ("282", "Amortissements des immobilisations corporelles"),
    ("2821", "Amortissements des terrains"),
    ("2822", "Amortissements des constructions"),
    ("2823", "Amortissements des installations techniques"),
    ("2828", "Amortissements des autres immobilisations corporelles"),
    ("284", "Amortissements des immobilisations à statut juridique particulier"),
    ("29", "Provisions pour dépréciation des immobilisations"),
    ("291", "Provisions pour dépréciation des immobilisations incorporelles"),
    ("292", "Provisions pour dépréciation des immobilisations corporelles"),
    ("293", "Provisions pour dépréciation des immobilisations en cours"),
    ("294", "Provisions pour dépréciation des immobilisations à statut juridique particulier"),
    ("295", "Provisions pour dépréciation des participations et des créances liées à des participations"),
    ("296", "Provisions pour dépréciation des autres immobilisations financières"),
    # Classe 3
    ("31", "Matières premières & fournitures liées"),
    ("311", "Matières premières"),
    ("313", "Fournitures"),
    ("317", "Autres"),
    ("32", "Autres approvisionnements"),
    ("321", "Matières consommables"),
    ("322", "Fournitures consommables"),
    ("326", "Emballages"),
    ("327", "Autres"),
    ("33", "En-cours de production de biens"),
    ("331", "Produits en cours"),
    ("335", "Travaux en cours"),
    ("34", "En-cours de production de services"),
    ("341", "Études en cours"),
    ("345", "Prestations de services en cours"),
    ("35", "Stocks de produits"),
    ("351", "Produits intermédiaires"),
    ("355", "Produits finis"),
    ("357", "Produits résiduels"),
    ("37", "Stocks de marchandises"),
    ("39", "Provisions pour dépréciation des stocks"),
    # Classe 4
    ("40", "Fournisseurs & comptes rattachés"),
    ("401", "Fournisseurs d'exploitation"),
    ("4011", "Fournisseurs - achats de biens ou de prestations de services"),
    ("4017", "Fournisseurs - retenues de garantie"),
    ("403", "Fournisseurs d'exploitation - effets à payer"),
    ("404", "Fournisseurs d'immobilisations"),
    ("4041", "Fournisseurs - achats d'immobilisations"),
    ("4047", "Fournisseurs d'immobilisations - retenues de garantie"),
    ("405", "Fournisseurs d'immobilisations - effets à payer"),
    ("408", "Fournisseurs - factures non parvenues"),
    ("4081", "Fournisseurs d'exploitation"),
    ("4084", "Fournisseurs d'immobilisations"),
    ("4088", "Fournisseurs - intérêts courus"),
    ("409", "Fournisseurs débiteurs"),
    ("4091", "Fournisseurs - avances et acomptes versés sur commandes"),
    ("4096", "Fournisseurs - créances pour emballages et matériel à rendre"),
    ("4097", "Fournisseurs - autres avoirs"),
    ("40971", "Fournisseurs d'exploitation"),
    ("40974", "Fournisseurs d'immobilisations"),
    ("4098", "Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus"),
    ("41", "Clients & comptes rattachés"),
    ("411", "Clients"),
    ("4111", "Clients - ventes de biens ou de prestations de services"),
    ("4117", "Clients - retenues de garantie"),
    ("413", "Clients - effets à recevoir"),
    ("416", "Clients douteux ou litigieux"),
    ("417", "Créances sur travaux non encore facturables"),
    ("418", "Clients - produits non encore facturés (produits à recevoir)"),
    ("4181", "Factures à établir"),
    ("4188", "Intérêts courus"),
    ("419", "Clients créditeurs"),
    ("4191", "Clients - avances et acomptes reçus sur commandes"),
    ("4196", "Clients - dettes pour emballages et matériel consignés"),
    ("4197", "Clients - autres avoirs"),
    ("4198", "Rabais, remises, ristournes à accorder et autres avoirs à établir"),
    ("42", "Personnel et comptes rattachés"),
    ("421", "Personnel - avances et acomptes"),
    ("422", "Comités d'entreprises et autres organes représentatifs du personnel"),
    ("423", "Personnel, œuvres sociales"),
    ("425", "Personnel - rémunérations dues"),
    ("426", "Personnel - dépôts"),
    ("427", "Personnel - oppositions"),
    ("428", "Personnel - charges à payer & produits à recevoir"),
    ("4282", "Dettes provisionnées pour congés à payer"),
    ("4286", "Autres charges à payer"),
    ("4287", "Produits à recevoir"),
    ("43", "Etat et collectivités publiques"),
    ("431", "Etat - subventions à recevoir"),
    ("432", "Etat, impôts et taxes retenus à la source"),
    ("433", "Opérations particulières avec l'Etat, les collectivités publiques, les organismes internationaux"),
    ("434", "Etat - impôts sur les bénéfices"),
    ("4341", "Retenue à la source"),
    ("4342", "Acomptes provisionnels"),
    ("4343", "Impôt à liquider"),
    ("4349", "Impôts différés"),
    ("435", "Obligations cautionnées"),
    ("436", "Etat - taxes sur le chiffre d'affaires"),
    ("4365", "Taxes sur le chiffre d'affaires à décaisser"),
    ("43651", "TVA à payer"),
    ("43658", "Autres taxes sur le chiffre d'affaires"),
    ("4366", "Taxes sur le chiffre d'affaires déductibles"),
    ("43662", "TVA sur immobilisations"),
    ("43663", "TVA transférée par d'autres entreprises"),
    ("43666", "TVA sur autres biens et services"),
    ("43667", "Crédit de TVA à reporter"),
    ("43668", "Autres taxes sur le chiffre d'affaires"),
    ("4367", "Taxes sur le chiffre d'affaires collectées par l'entreprise"),
    ("43671", "TVA collectée"),
    ("436711", "TVA collectée sur les débits"),
    ("436712", "TVA collectée sur les encaissements"),
    ("43678", "Autres taxes sur le chiffre d'affaires"),
    ("4368", "Taxes sur le chiffre d'affaires à régulariser ou en attente"),
    ("437", "Autres impôts, taxes et versements assimilés"),
    ("438", "Etat - charges à payer et produits à recevoir"),
    ("4382", "Charges fiscales sur congés à payer"),
    ("4386", "Autres charges à payer"),
    ("4387", "Produits à recevoir"),
    ("44", "Sociétés du groupe & associés"),
    ("441", "Groupe"),
    ("4411", "Créances et intérêts courus"),
    ("4412", "Dettes et intérêts à payer"),
    ("442", "Associés - comptes courants"),
    ("4421", "Principal"),
    ("4428", "Intérêts courus"),
    ("446", "Associés - opérations sur le capital"),
    ("447", "Associés - dividendes à payer"),
    ("448", "Associés - opérations faites en commun"),
    ("4481", "Opérations courantes"),
    ("4488", "Intérêts courus"),
    ("45", "Débiteurs divers et Créditeurs divers"),
    ("452", "Créances sur cessions d'immobilisations"),
    ("453", "Sécurité sociale et autres organismes sociaux"),
    ("4531", "Organismes sociaux"),
    ("45311", "CNSS"),
    ("45318", "Autres"),
    ("4538", "Organismes sociaux - charges à payer et produits à recevoir"),
    ("45382", "Charges sociales sur congés à payer"),
    ("45386", "Autres charges à payer"),
    ("45387", "Produits à recevoir"),
    ("454", "Dettes sur acquisitions de valeurs mobilières de placement"),
    ("455", "Créances sur cessions de valeurs mobilières de placement"),
    ("457", "Autres comptes débiteurs ou créditeurs"),
    ("458", "Diverses charges à payer et produits à recevoir"),
    ("4586", "Charges à payer"),
    ("4587", "Produits à recevoir"),
    ("46", "Comptes transitoires ou d'attente"),
    ("461", "Compte d'attente"),
    ("465", "Différence de conversion sur éléments courants"),
    ("4651", "Différences de conversion actif"),
    ("4652", "Différences de conversion passif"),
    ("468", "Autres comptes transitoires"),
    ("47", "Comptes de régularisation"),
    ("471", "Charges constatées d'avance"),
    ("472", "Produits constatés d'avance"),
    ("478", "Comptes de répartition périodique de charges et produits"),
    ("4786", "Charges"),
    ("4787", "Produits"),
    ("48", "Provisions courantes pour risques et charges"),
    ("49", "Provisions pour dépréciation des comptes de tiers"),
    ("491", "Provisions pour dépréciation des comptes clients"),
    ("494", "Provisions pour dépréciation des comptes de groupe et associés"),
    ("4941", "Comptes du groupe"),
    ("4942", "Comptes courants des associés"),
    ("4948", "Opérations faites en commun"),
    ("495", "Provisions pour dépréciation des comptes de débiteurs divers"),
    ("4952", "Créances sur cession d'immobilisation"),
    ("4955", "Créances sur cession des valeurs mobilières de placement"),
    ("4957", "Autres comptes débiteurs"),
    # Classe 5
    ("50", "Emprunts et autres dettes financières courants"),
    ("501", "Emprunts courants liés au cycle d'exploitation"),
    ("505", "Échéances à moins d'un an sur emprunts non courants"),
    ("506", "Concours bancaires courants"),
    ("5061", "Crédit de mobilisation de créances commerciales"),
    ("5063", "Mobilisation de créances nées à l'étranger"),
    ("5067", "Autres concours bancaires"),
    ("507", "Emprunts échus et impayés"),
    ("508", "Intérêts courus"),
    ("51", "Prêts et autres créances financières courants"),
    ("511", "Prêts courants liés au cycle d'exploitation"),
    ("516", "Échéances à moins d'un an sur prêts non courants"),
    ("517", "Échéances à moins d'un an sur autres créances financières"),
    ("518", "Intérêts courus"),
    ("52", "Placements courants"),
    ("523", "Actions"),
    ("5231", "Titres cotés"),
    ("5235", "Titres non cotés"),
    ("524", "Autres titres conférant un droit de propriété"),
    ("525", "Obligations et bons émis par la société et rachetés par elle"),
    ("526", "Obligations"),
    ("5261", "Titres cotés"),
    ("5265", "Titres non cotés"),
    ("5266", "Échéances à moins d'un an sur les obligations immobilisées"),
    ("527", "Bons du trésor et bons de caisse à court terme"),
    ("528", "Autres placements courants et créances assimilées"),
    ("5281", "Autres valeurs mobilières"),
    ("5288", "Intérêts courus sur obligations, bons et valeurs assimilées"),
    ("529", "Versements restant à effectuer sur valeurs mobilières de placement non libérées"),
    ("53", "Banques, établissements financiers et assimilés"),
    ("531", "Valeurs à l'encaissement"),
    ("5311", "Coupons échus à l'encaissement"),
    ("5312", "Chèques à encaisser"),
    ("5313", "Effets à l'encaissement"),
    ("5314", "Effets à l'escompte"),
    ("532", "Banques"),
    ("5321", "Comptes en dinars"),
    ("5324", "Comptes en devises"),
    ("534", "C.C.P."),
    ("535", "Comptes au trésor"),
    ("537", "Autres organismes financiers"),
    ("54", "Caisse"),
    ("541", "Caisse siège social"),
    ("5411", "Caisse en dinars"),
    ("5414", "Caisse en devises"),
    ("542", "Caisses succursales"),
    ("55", "Régies d'avances et accréditifs"),
    ("58", "Virements internes"),
    ("59", "Provisions pour dépréciation des comptes financiers"),
    # Classe 6
    ("60", "Achats"),
    ("601", "Achats stockés - Matières premières et fournitures liées"),
    ("602", "Achats stockés - Autres approvisionnements"),
    ("6021", "Matières consommables"),
    ("6022", "Fournitures consommables"),
    ("6026", "Emballages"),
    ("603", "Variation des stocks (approvisionnements et marchandises)"),
    ("6031", "Variation des stocks de matières premières et fournitures"),
    ("6032", "Variation des stocks des autres approvisionnements"),
    ("6037", "Variation des stocks de marchandises"),
    ("604", "Achats d'études et de prestations de services"),
    ("605", "Achats de matériel, équipements et travaux"),
    ("606", "Achats non stockés de matières et fournitures"),
    ("607", "Achats de marchandises"),
    ("608", "Achats liés à une modification comptable ou à une activité abandonnée"),
    ("609", "Rabais, remises et ristournes obtenus sur achats"),
    ("6098", "Liés à une modification comptable ou à une activité abandonnée"),
    ("61", "Services extérieurs"),
    ("611", "Sous-traitance générale"),
    ("612", "Redevances pour utilisation d'immobilisations concédées"),
    ("613", "Locations"),
    ("614", "Charges locatives et de copropriété"),
    ("615", "Entretien et réparations"),
    ("616", "Primes d'assurances"),
    ("617", "Études, recherches et divers services extérieurs"),
    ("618", "Autres charges liées à une modification comptable ou à une activité abandonnée"),
    ("619", "Rabais, remises et ristournes obtenus sur services extérieurs"),
    ("62", "Autres services extérieurs"),
    ("621", "Personnel extérieur à l'entreprise"),
    ("622", "Rémunération d'intermédiaires et honoraires"),
    ("623", "Publicité, publications, relations publiques"),
    ("624", "Transports de biens et transports collectifs du personnel"),
    ("6241", "Transports sur achats"),
    ("6242", "Transports sur ventes"),
    ("6244", "Transports administratifs"),
    ("6247", "Transports collectifs du personnel"),
    ("6248", "Divers"),
    ("625", "Déplacements, missions et réceptions"),
    ("6251", "Voyages et déplacements"),
    ("6255", "Frais de déménagement"),
    ("6256", "Missions"),
    ("6257", "Réceptions"),
    ("626", "Frais postaux et frais de télécommunications"),
    ("627", "Services bancaires et assimilés"),
    ("6271", "Frais sur titres"),
    ("6272", "Commissions et frais sur émission d'emprunts"),
    ("6275", "Frais sur effets"),
    ("6276", "Location de coffres"),
    ("6278", "Autres frais et commissions sur prestations de services"),
    ("628", "Autres services extérieurs liés à une modification comptable ou à une activité abandonnée"),
    ("629", "Rabais, remises et ristournes obtenus sur autres services extérieurs"),
    ("63", "Charges diverses ordinaires"),
    ("631", "Redevances pour concessions de marques, brevets, licences, procédés, droits et valeurs similaires"),
    ("633", "Jetons de présence"),
    ("634", "Pertes sur créances irrécouvrables"),
    ("6341", "Créances de l'exercice"),
    ("6344", "Créances des exercices antérieurs"),
    ("635", "Quotes-parts de résultat sur opérations faites en commun"),
    ("6351", "Quote-part de bénéfice transférée"),
    ("6355", "Quote-part de perte supportée"),
    ("636", "Charges nettes sur cessions d'immobilisations et autres pertes sur éléments non récurrents"),
    ("637", "Réduction de valeur"),
    ("638", "Charges diverses ordinaires liées à une modification comptable ou à une activité abandonnée"),
    ("64", "Charges de personnel"),
    ("640", "Salaires et compléments de salaires"),
    ("6400", "Salaires"),
    ("6401", "Heures supplémentaires"),
    ("6402", "Primes"),
    ("6403", "Gratifications"),
    ("6404", "Avantages en nature"),
    ("6409", "Autres compléments de salaires"),
    ("642", "Appointements et compléments d'appointements"),
    ("6420", "Appointements"),
    ("6421", "Heures supplémentaires"),
    ("6422", "Primes"),
    ("6423", "Gratifications"),
    ("6424", "Avantages en nature"),
    ("6429", "Autres compléments d'appointements"),
    ("643", "Indemnités représentatives de frais"),
    ("644", "Commissions au personnel"),
    ("6440", "Commissions sur achats"),
    ("6441", "Commissions sur ventes"),
    ("645", "Rémunérations des administrateurs, gérants et associés"),
    ("646", "Charges connexes aux salaires, appointements, commissions et rémunérations"),
    ("6460", "Charges connexes aux salaires"),
    ("64600", "Congés payés"),
    ("64602", "Indemnités de préavis et de licenciements"),
    ("64604", "Supplément familial"),
    ("6462", "Charges connexes aux appointements"),
    ("64620", "Congés payés"),
    ("64622", "Indemnités de préavis et de licenciement"),
    ("64624", "Supplément familial"),
    ("6464", "Charges connexes aux commissions"),
    ("64640", "Congés payés"),
    ("64642", "Indemnités de préavis et de licenciement"),
    ("64644", "Supplément familial"),
    ("6465", "Charges connexes aux rémunérations des administrateurs et gérants"),
    ("64650", "Congés payés"),
    ("64652", "Indemnités de préavis et de licenciement"),
    ("64654", "Supplément familial"),
    ("647", "Charges sociales légales"),
    ("6470", "Cotisations de sécurité sociale sur salaires"),
    ("6472", "Cotisations de sécurité sociale sur appointements"),
    ("6474", "Cotisations de sécurité sociale sur commissions"),
    ("6475", "Cotisations de sécurité sociale sur rémunérations des administrateurs et gérants"),
    ("6476", "Prestations directes"),
    ("648", "Charges de personnel liées à une modification comptable ou à une activité abandonnée"),
    ("649", "Autres charges de personnel et autres charges sociales"),
    ("6490", "Autres charges de personnel"),
    ("6495", "Autres charges sociales"),
    ("65", "Charges financières"),
    ("651", "Charges d'intérêts"),
    ("6511", "Intérêts des emprunts et dettes"),
    ("65116", "Des emprunts et dettes assimilées"),
    ("65117", "Des dettes rattachées à des participations"),
    ("6515", "Intérêts des comptes courants et des dépôts créditeurs"),
    ("6516", "Intérêts bancaires et sur opérations de financement"),
    ("6517", "Intérêts des obligations cautionnées"),
    ("6518", "Intérêts des autres dettes"),
    ("653", "Pertes sur créances liées à des participations"),
    ("654", "Escomptes accordés"),
    ("655", "Pertes de change"),
    ("656", "Charges nettes sur cessions de valeurs mobilières"),
    ("657", "Autres charges financières"),
    ("658", "Charges financières liées à une modification comptable ou à une activité abandonnée"),
    ("66", "Impôts, taxes et versements assimilés"),
    ("661", "Impôts, taxes et versements assimilés sur rémunérations"),
    ("6611", "TFP"),
    ("6612", "FOPROLOS"),
    ("6618", "Autres"),
    ("665", "Autres impôts, taxes et versements assimilés"),
    ("6651", "Impôts et taxes divers (sauf impôts sur les bénéfices)"),
    ("6652", "Taxes sur le chiffre d'affaires non récupérables"),
    ("6654", "Droits d'enregistrement et de timbre"),
    ("6655", "Taxes sur les véhicules"),
    ("6658", "Autres droits"),
    ("668", "Impôts et taxes liés à une modification comptable ou à une activité abandonnée"),
    ("67", "Pertes extraordinaires"),
    ("68", "Dotations aux amortissements et aux provisions"),
    ("681", "Dotations aux amortissements et aux provisions - charges ordinaires"),
    ("6811", "Dotations aux amortissements des immobilisations incorporelles et corporelles"),
    ("68111", "Immobilisations incorporelles"),
    ("68112", "Immobilisations corporelles"),
    ("6812", "Dotations aux résorptions des charges reportées"),
    ("6815", "Dotations aux provisions pour risques et charges d'exploitation"),
    ("6816", "Dotations aux provisions pour dépréciation des immobilisations incorporelles et corporelles"),
    ("68161", "Immobilisations incorporelles"),
    ("68162", "Immobilisations corporelles"),
    ("6817", "Dotations aux provisions pour dépréciation des actifs courants"),
    ("68173", "Stocks et en-cours"),
    ("68174", "Créances"),
    ("6818", "Dotations liées à une modification comptable ou à une activité abandonnée"),
    ("686", "Dotations aux amortissements et aux provisions - charges financières"),
    ("6861", "Dotations aux amortissements des primes de remboursement des obligations"),
    ("6865", "Dotations aux provisions pour risques et charges financières"),
    ("6866", "Dotations aux provisions pour dépréciation des éléments financiers"),
    ("68662", "Immobilisations financières"),
    ("68665", "Placements et prêts courants"),
    ("6868", "Dotations financières liées à une modification comptable ou à une activité abandonnée"),
    ("69", "Impôts sur les bénéfices"),
    ("691", "Impôts sur les bénéfices calculés sur le résultat des activités ordinaires"),
    ("695", "Autres impôts sur les bénéfices (régimes particuliers)"),
    ("697", "Impôts sur les bénéfices calculés sur les éléments extraordinaires"),
    # Classe 7
    ("70", "Ventes de produits fabriqués, prestations de services, marchandises"),
    ("701", "Ventes de produits finis"),
    ("7011", "Produits finis achevés"),
    ("7012", "Produits finis non achevés (contrat de longue durée)"),
    ("702", "Ventes de produits intermédiaires"),
    ("703", "Ventes de produits résiduels"),
    ("704", "Travaux"),
    ("705", "Études et prestations de services"),
    ("706", "Produits des activités annexes"),
    ("707", "Ventes de marchandises"),
    ("708", "Ventes liées à une modification comptable ou à une activité abandonnée"),
    ("709", "Rabais, remises et ristournes accordés par l'entreprise"),
    ("7091", "Sur ventes de produits finis"),
    ("7092", "Sur ventes de produits intermédiaires"),
    ("7094", "Sur travaux"),
    ("7095", "Sur études et prestations de services"),
    ("7096", "Sur activités annexes"),
    ("7097", "Sur ventes de marchandises"),
    ("7098", "Sur ventes liées à une modification comptable ou à une activité abandonnée"),
    ("71", "Production stockée (ou destockage)"),
    ("713", "Variation des stocks (en-cours de production, produits)"),
    ("7133", "Variations des en-cours de production de biens"),
    ("7134", "Variation des en-cours de production de services"),
    ("7135", "Variation des stocks de produits"),
    ("72", "Production immobilisée"),
    ("721", "Immobilisations incorporelles"),
    ("722", "Immobilisations corporelles"),
    ("728", "Production immobilisée liée à une modification comptable ou à une activité abandonnée"),
    ("73", "Produits divers ordinaires"),
    ("731", "Redevances pour concessions, brevets, licences, marques, procédés, droits et valeurs similaires"),
    ("732", "Revenus des immeubles non affectés aux activités professionnelles"),
    ("733", "Jetons de présence et rémunérations d'administrateurs, gérants"),
    ("734", "Ristournes perçues des coopératives"),
    ("735", "Quotes-parts de résultat sur opérations faites en commun"),
    ("736", "Produits nets sur cessions d'immobilisations et autres gains sur éléments non récurrents"),
    ("738", "Produits divers ordinaires liés à une modification comptable ou à une activité abandonnée"),
    ("739", "Quotes-parts des subventions d'investissement inscrites au résultat de l'exercice"),
    ("74", "Subventions d'exploitation et d'équilibre"),
    ("741", "Subventions d'exploitation"),
    ("745", "Subventions d'équilibre"),
    ("748", "Subventions liées à une modification comptable ou à une activité abandonnée"),
    ("75", "Produits financiers"),
    ("751", "Produits des participations"),
    ("752", "Produits des autres immobilisations financières"),
    ("753", "Revenus des autres créances"),
    ("754", "Revenus des valeurs mobilières de placement"),
    ("755", "Escomptes obtenus"),
    ("756", "Gains de change"),
    ("757", "Produits nets sur cessions de valeurs mobilières"),
    ("758", "Produits financiers liés à une modification comptable ou à une activité abandonnée"),
    ("77", "Gains extraordinaires"),
    ("78", "Reprises sur amortissements et provisions"),
    ("781", "Reprises sur amortissements et provisions (produits ordinaires)"),
    ("7811", "Reprises sur amortissements des immobilisations incorporelles et corporelles"),
    ("78111", "Immobilisations incorporelles"),
    ("78112", "Immobilisations corporelles"),
    ("7815", "Reprises sur provisions pour risques et charges d'exploitation"),
    ("7816", "Reprises sur provisions pour dépréciation des immobilisations incorporelles et corporelles"),
    ("78161", "Immobilisations incorporelles"),
    ("78162", "Immobilisations corporelles"),
    ("7817", "Reprises sur provisions pour dépréciation des actifs courants"),
    ("78173", "Stocks et en-cours"),
    ("78174", "Créances"),
    ("7818", "Reprises sur provisions liées à une modification comptable ou à une activité abandonnée"),
    ("786", "Reprises sur provisions (produits financiers)"),
    ("7865", "Reprises sur provisions pour risques et charges financières"),
    ("7866", "Reprises sur provisions pour dépréciation des éléments financiers"),
    ("7868", "Reprises financières liées à une modification comptable ou à une activité abandonnée"),
    ("79", "Transferts de charges"),
]

OVERLAY: list[tuple[str, str]] = [
    ("43652", "FODEC à payer"),
    ("4371", "Timbre fiscal à payer"),
    ("4320", "Retenue à la source — divers"),
    ("4321", "Retenue RS1 (loyers)"),
    ("4322", "Retenue RS2 (honoraires)"),
    ("4323", "Retenue RS3 (revenus de capitaux)"),
    ("4324", "Retenue RS4 (dividendes)"),
    ("4325", "Retenue RS5 (plus-values)"),
    ("4326", "Retenue RS6 (immobilier foncier)"),
    ("4327", "Retenue RS7 (achats)"),
    ("641", "Indemnités de rupture et soldes de tout compte"),
    ("421.1", "Prêts au personnel - retenues en cours"),
    ("428.1", "Mutuelle / caisse complémentaire - part salariale"),
    ("428.2", "Tickets restaurant - part salariale"),
]


def account_class(num: str) -> int:
    return int(num[0])


def nature(num: str) -> int:
    """0 = Debit (actif / charge), 1 = Credit (passif / produit)."""
    cls = account_class(num)
    if num.startswith(("28", "29", "39", "49", "59")):
        return 1
    if num.startswith(("109", "259", "269", "529")):
        return 0
    if cls in (1, 7):
        return 1
    if cls in (2, 3, 6):
        return 0
    if num.startswith("409") or num.startswith("431") or num.startswith("4341") or num.startswith("4342"):
        return 0
    if num.startswith("4366"):
        return 0
    if num.startswith("419") or num.startswith("40") or num.startswith("42") or num.startswith("432"):
        return 1
    if num.startswith("4365") or num.startswith("4367") or num.startswith("4368") or num.startswith("437"):
        return 1
    if num.startswith("4343") or num.startswith("435"):
        return 1
    if num.startswith("41"):
        return 0
    if num.startswith("452") or num.startswith("455") or num.startswith("4411"):
        return 0
    if num.startswith("453") or num.startswith("447") or num.startswith("4412") or num.startswith("442"):
        return 1
    if num.startswith("50") or num.startswith("59"):
        return 1
    if cls == 5:
        return 0
    if cls == 4:
        return 1
    return 0


def parent_of(num: str, numbers: set[str]) -> str | None:
    # Dotted overlays: parent is the digit prefix before the dot.
    if "." in num:
        stem = num.split(".", 1)[0]
        if stem in numbers:
            return stem
    for i in range(len(num) - 1, 0, -1):
        cand = num[:i]
        if cand in numbers:
            return cand
    return None


def build_catalog() -> dict:
    seen: dict[str, str] = {}
    for n, lab in NCT_ACCOUNTS:
        seen[n] = lab
    overlay_nums = {n for n, _ in OVERLAY}
    for n, lab in OVERLAY:
        seen[n] = lab
    numbers = set(seen)
    accounts = []
    for n, lab in seen.items():
        par = parent_of(n, numbers - {n})
        accounts.append({
            "number": n,
            "label": lab,
            "accountClass": account_class(n),
            "parent": par,
            "natureType": nature(n),
            "level": len(n),
            "isSystem": True,
            "layer": "overlay" if n in overlay_nums else "nct01",
        })
    accounts.sort(key=lambda a: (a["accountClass"], a["number"]))
    return {
        "version": "nct01-v1",
        "source": "NCT 01 nomenclature (PDF) + NCT corrections 603/79/786x + overlay métier",
        "accounts": accounts,
    }


def m(frm: str, to: str | None, mode: str, reason: str, prefix: bool = True) -> dict:
    row = {"from": frm, "to": to, "mode": mode, "prefix": prefix, "reason": reason}
    return row


def build_remap() -> dict:
    entries = [
        m("102", "1012", "move", "Capital appelé non versé NCT 1012"),
        m("105", "117", "move", "Primes liées au capital NCT 117"),
        m("106", "144", "move", "Écarts de réévaluation NCT 144"),
        m("19", "15", "move", "Provisions pour risques NCT 15", prefix=False),
        m("17", "1687", "move", "Crédit-bail vers overlay NCT 1687", prefix=False),
        m("18", "17", "move", "Liaisons établissements NCT 17", prefix=False),
        # Classe 2 inversion — longest children first via prefix on 3-digit
        m("211", "221", "move", "Terrains NCT 221"),
        m("212", "222", "move", "Constructions NCT 222"),
        m("213", "223", "move", "Installations techniques NCT 223"),
        m("218", "228", "move", "Autres immobilisations corporelles NCT 228"),
        m("231", "232", "move", "Immo corporelles en cours NCT 232"),
        m("232", "231", "move", "Immo incorporelles en cours NCT 231"),
        m("22", "24", "move", "Concession FR 22 → NCT 24", prefix=False),
        m("20", "21", "move", "Incorporelles FR 20 → NCT 21", prefix=False),
        m("21", "22", "move", "Corporelles FR 21 → NCT 22", prefix=False),
        m("24", "26", "move", "Financières FR 24 → NCT 26", prefix=False),
        m("25", "261", "move", "Titres immobilisés FR 25 → NCT 261"),
        m("26", "25", "move", "Participations FR 26 → NCT 25", prefix=False),
        m("280", "281", "move", "Amort. incorporelles NCT 281"),
        m("2811", "2821", "move", "Amort. terrains"),
        m("2812", "2822", "move", "Amort. constructions"),
        m("2813", "2823", "move", "Amort. installations"),
        m("2818", "2828", "move", "Amort. autres corporelles"),
        m("281", "282", "move", "Amort. corporelles NCT 282", prefix=False),
        m("312", "321", "move", "Matières consommables NCT 321"),
        m("36", None, "deactivate", "Compte PCG 36 absent NCT"),
        m("38", "39", "move", "Dépréciation stocks NCT 39", prefix=False),
        # Classe 4
        m("413", "4197", "move", "Libérer 413 pour effets NCT", prefix=False),
        m("412", "413", "move", "Effets à recevoir NCT 413"),
        m("414", "416", "move", "Clients douteux NCT 416"),
        m("405", "4011", "merge-into", "Fournisseurs biens/services déjà en 4011", prefix=False),
        m("406", "408", "move", "Factures non parvenues NCT 408", prefix=False),
        m("407", "4097", "move", "Autres avoirs fournisseurs NCT 4097"),
        m("43", "453", "move", "Social FR 43 → NCT 453", prefix=False),
        m("431", "4531", "move", "Sécurité sociale NCT 4531"),
        # 432 kept (payroll state withholding) — relabel only
        m("433", "45318", "move", "Autres organismes sociaux"),
        m("435", "4538", "move", "Charges sociales à payer"),
        m("437", "45318", "merge-into", "Autres charges sociales FR"),
        m("438", "4538", "merge-into", "Organismes sociaux autres FR"),
        m("441", "431", "move", "Subventions à recevoir NCT 431", prefix=False),
        m("442", "4366", "merge-into", "Impôts recouvrables FR", prefix=False),
        m("443", "43651", "merge-into", "TVA due FR", prefix=False),
        m("444", "437", "move", "Autres impôts État FR", prefix=False),
        m("44560", "4320", "move", "RS divers"),
        m("44561", "4321", "move", "RS1"),
        m("44562", "4322", "move", "RS2"),
        m("44563", "4323", "move", "RS3"),
        m("44564", "4327", "move", "RS7"),
        m("44565", "4324", "move", "RS4"),
        m("44566", "4325", "move", "RS5"),
        m("44567", "4326", "move", "RS6"),
        m("445", None, "deactivate", "Racine RS PCG 445"),
        m("4477", "43652", "move", "FODEC à payer NCT 43652"),
        m("4478", "4371", "move", "Timbre fiscal vente NCT 4371"),
        m("447", "437", "move", "État autres comptes FR → 437", prefix=False),
        m("448", "438", "move", "État charges à payer NCT 438", prefix=False),
        m("44", "43", "move", "État FR 44 → NCT 43", prefix=False),
        m("451", "441", "move", "Groupe NCT 441", prefix=False),
        m("452", "442", "move", "Associés comptes courants NCT 442", prefix=False),
        m("455", "448", "move", "Associés opérations courantes NCT 448", prefix=False),
        m("456", "447", "move", "Dividendes NCT 447", prefix=False),
        m("45", "44", "move", "Groupe FR 45 → NCT 44", prefix=False),
        m("421", "425", "move", "Rémunérations dues NCT 425"),
        m("425.1", "421.1", "move", "Prêts personnel sous avances NCT 421"),
        m("425", "421", "move", "Avances personnel NCT 421", prefix=False),
        # Classe 5
        m("512", "523", "move", "Titres CT PCG 512 → NCT 523", prefix=False),
        m("511", "523", "merge-into", "Portefeuille placement"),
        m("51", "52", "move", "VMP FR 51 → NCT 52", prefix=False),
        m("531", "541", "move", "Caisse mal parentée FR 531", prefix=False),
        m("533", "542", "move", "Caisses succursales NCT 542"),
        m("534", "55", "move", "Régies NCT 55", prefix=False),
        m("535", "58", "move", "Virements internes NCT 58", prefix=False),
        m("536", "534", "move", "CCP NCT 534"),
        # Classe 6
        m("63", "66", "move", "Impôts FR 63 → NCT 66", prefix=False),
        m("651", "631", "move", "Redevances FR 651 → NCT 631"),
        m("652", "633", "move", "Jetons FR 652 → NCT 633"),
        m("653", "622", "move", "Honoraires FR 653 → NCT 622"),
        m("654", "634", "move", "Pertes sur créances FR 654 → NCT 634"),
        m("658", "638", "move", "Charges diverses FR 658 → NCT 638"),
        m("659", "67", "move", "Charges exceptionnelles FR 659 → NCT 67", prefix=False),
        m("6613", "655", "move", "Pertes de change NCT 655"),
        m("6614", "654", "move", "Escomptes accordés NCT 654"),
        m("6615", "657", "move", "Charges assimilées"),
        m("661", "651", "move", "Intérêts FR 661 → NCT 651", prefix=False),
        m("6651", "67", "merge-into", "Pénalités FR"),
        m("6652", "638", "merge-into", "Divers exceptionnel FR"),
        m("6653", "638", "merge-into", "Charges gestion FR"),
        m("665", "67", "move", "Exceptionnel financier FR → 67", prefix=False),
        m("6371", "6654", "merge-into", "Timbre achat NCT 6654"),
        m("675", "636", "move", "VNC cédée NCT 636"),
        m("6811", "68112", "move", "Dotations corporelles NCT 68112", prefix=False),
        m("6812", "68112", "merge-into", "Dotations constructions → 68112"),
        m("6813", "68112", "merge-into", "Dotations installations → 68112"),
        m("6818", "68112", "merge-into", "Dotations autres corporelles → 68112"),
        # Relabel-only roots (catalog upsert)
        m("10", "10", "relabel", "Capital NCT"),
        m("11", "11", "relabel", "Réserves NCT"),
        m("12", "12", "relabel", "Résultats reportés NCT"),
        m("13", "13", "relabel", "Résultat de l'exercice NCT"),
        m("14", "14", "relabel", "Autres capitaux propres NCT"),
        m("15", "15", "relabel", "Provisions risques NCT"),
        m("16", "16", "relabel", "Emprunts NCT"),
        m("101", "101", "relabel", "Capital social"),
        m("108", "108", "relabel", "Compte de l'exploitant"),
        m("109", "109", "relabel", "Actionnaires capital non appelé"),
        m("131", "131", "relabel", "Résultat bénéficiaire"),
        m("135", "135", "relabel", "Résultat déficitaire"),
        m("432", "432", "relabel", "État retenues à la source NCT"),
        m("6611", "6611", "relabel", "TFP"),
        m("6612", "6612", "relabel", "FOPROLOS"),
    ]
    return {
        "version": "nct01-v1",
        "protectedPrefixes": [
            "43651", "43662", "43666", "43667", "43671", "436711", "436712", "4368",
            "4011", "4111", "705", "707", "607", "5321", "5324", "5411", "6611", "6612", "45311", "453",
        ],
        "entries": entries,
    }


def validate(catalog: dict, remap: dict) -> None:
    nums = [a["number"] for a in catalog["accounts"]]
    assert len(nums) == len(set(nums)), "duplicate catalog numbers"
    assert "603" in nums and "6031" in nums and "6037" in nums
    assert "79" in nums and "7865" in nums
    assert "43652" in nums and "4477" not in nums
    assert "4371" in nums
    for a in catalog["accounts"]:
        if a["parent"]:
            assert a["number"].startswith(a["parent"].replace(".", "")[:1]) or a["number"].startswith(a["parent"])
            # dotted: 421.1 startswith 421
            if "." not in a["number"]:
                assert a["number"].startswith(a["parent"]), (a["number"], a["parent"])
    moves = [e for e in remap["entries"] if e["mode"] in ("move", "merge-into") and e["to"]]
    froms = [e["from"] for e in moves]
    # cycles 231/232 and 421/425 must exist
    assert any(e["from"] == "231" and e["to"] == "232" for e in moves)
    assert any(e["from"] == "232" and e["to"] == "231" for e in moves)
    assert any(e["from"] == "421" and e["to"] == "425" for e in moves)
    assert any(e["from"] == "425" and e["to"] == "421" for e in moves)
    assert any(e["from"] == "4477" and e["to"] == "43652" for e in moves)
    for p in remap["protectedPrefixes"]:
        assert p not in froms or any(e["from"] == p and e["to"] == p for e in remap["entries"])


def main() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    RES.mkdir(parents=True, exist_ok=True)
    catalog = build_catalog()
    remap = build_remap()
    validate(catalog, remap)
    for dest in (DOCS, RES):
        (dest / "nct01-coa-catalog.json").write_text(
            json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        (dest / "coa-remap-v1.json").write_text(
            json.dumps(remap, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"catalog accounts={len(catalog['accounts'])} remap entries={len(remap['entries'])}")


if __name__ == "__main__":
    main()
