using FactuTrust.Application.Common.Interfaces;
using FactuTrust.Application.Common.Interfaces.Repositories;
using FactuTrust.Application.Common.Interfaces.Services;
using FactuTrust.Application.DTOs;
using FactuTrust.Application.Features.Accounting.Commands;
using FactuTrust.Domain.Common;
using FactuTrust.Domain.Entities;
using FactuTrust.Domain.Enums;
using FactuTrust.Domain.ValueObjects;
using FactuTrust.Infrastructure.MultiTenancy;
using FactuTrust.Infrastructure.Persistence;
using FactuTrust.Infrastructure.Repositories;
using FactuTrust.Infrastructure.Services;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Xunit;
using FactuTrust.Infrastructure.Tests.Fakes;

namespace FactuTrust.Infrastructure.Tests.Repositories;

/// <summary>
/// <see cref="JournalEntryRepository.GetPostedCashSaleVatByRateAsync"/> : la déclaration TVA
/// assise sur le journal (plan §6.7) — mouvements signés, un seul niveau d'extourne, Brouillon
/// inclus. Plus <see cref="JournalEntryRepository.ExistsActiveBySourceTypeAsync"/> (§9.7).
/// </summary>
public sealed class JournalEntryRepositoryCashVatTests : IDisposable
{
    private readonly string _databaseName;
    private readonly TestTenantDbContextFactory _contextFactory;
    private readonly JournalEntryRepository _repository;

    public JournalEntryRepositoryCashVatTests()
    {
        _databaseName = $"JournalEntryCashVatTestDb_{Guid.NewGuid()}";
        _contextFactory = new TestTenantDbContextFactory(_databaseName);
        _repository = new JournalEntryRepository(_contextFactory);
    }

    private sealed class TestTenantDbContextFactory : ITenantDbContextFactory
    {
        private readonly string _databaseName;
        public TestTenantDbContextFactory(string databaseName) => _databaseName = databaseName;

        public TenantDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<TenantDbContext>()
                .UseInMemoryDatabase(databaseName: _databaseName)
                .Options;
            return new TenantDbContext(options);
        }
    }

    // ── Fabriques ────────────────────────────────────────────────────────────

    private static CashOperation SeedCashSalesOperation(VatRate? vatRate, int sequence = 1, decimal amount = 119m)
    {
        var number = CashOperationNumber.Create(CashOperationNumber.CreditPrefix, 2026, sequence).Value;
        return CashOperation.Create(
            number,
            CashOperationType.Credit,
            new DateTime(2026, 3, 10),
            PaymentMethod.Cash,
            Money.Create(amount, "TND"),
            "Encaissement ventes au comptant",
            revenueCategory: CashRevenueCategory.CashSalesReceipt,
            vatRate: vatRate).Value;
    }

    /// <summary>
    /// Période comptable réelle, requise pour les tests qui font passer l'écriture par le handler
    /// d'édition cabinet : <c>GetByIdForUpdateAsync</c> fait un <c>Include(AccountingPeriod)</c> sur une
    /// relation requise — un <c>AccountingPeriodId</c> orphelin (aucune période correspondante en base)
    /// fait échouer la jointure sous le provider InMemory (à la différence d'un provider relationnel,
    /// où l'orphelinat est de toute façon impossible grâce à la FK réelle).
    /// </summary>
    private AccountingPeriod SeedPeriod()
    {
        var period = AccountingPeriod.Create(2026, 3, new DateTime(2026, 3, 1), new DateTime(2026, 4, 30));
        period.SetAuditInfo("test", false);
        using var ctx = _contextFactory.CreateContext();
        ctx.AccountingPeriods.Add(period);
        ctx.SaveChanges();
        return period;
    }

    /// <summary>Écriture caisse à 3 lignes (débit trésorerie TTC / crédit 707 HT / crédit 436711 TVA).</summary>
    private static JournalEntry CashSaleEntry(
        int entryNumber,
        DateTime date,
        decimal ht,
        decimal vat,
        Guid sourceOperationId,
        JournalEntryStatus status = JournalEntryStatus.Validee,
        Guid? accountingPeriodId = null)
    {
        var lines = new[]
        {
            new JournalLineInput("5411", "Caisse", ht + vat, 0, null, ThirdPartyKind.None),
            new JournalLineInput("707", "Ventes HT", 0, ht, null, ThirdPartyKind.None),
            new JournalLineInput("436711", "TVA collectée", 0, vat, null, ThirdPartyKind.None)
        };

        return JournalEntry.Create(
            entryNumber, "JC", date, "Encaissement ventes au comptant", accountingPeriodId ?? Guid.NewGuid(),
            isAutoGenerated: true, sourceEntityType: "CashOperation", sourceEntityId: sourceOperationId,
            lineInputs: lines, initialStatus: status).Value;
    }

    /// <summary>Écriture caisse à 2 lignes (pas de TVA — sans compte 436711).</summary>
    private static JournalEntry CashEntryWithoutVat(
        int entryNumber, DateTime date, decimal amount, Guid sourceOperationId)
    {
        var lines = new[]
        {
            new JournalLineInput("5411", "Caisse", amount, 0, null, ThirdPartyKind.None),
            new JournalLineInput("707", "Ventes", 0, amount, null, ThirdPartyKind.None)
        };

        return JournalEntry.Create(
            entryNumber, "JC", date, "Encaissement", Guid.NewGuid(),
            isAutoGenerated: true, sourceEntityType: "CashOperation", sourceEntityId: sourceOperationId,
            lineInputs: lines).Value;
    }

    /// <summary>Écriture non-caisse (facture) portant du 436711 : ne doit jamais être comptée ici.</summary>
    private static JournalEntry InvoiceVatEntry(int entryNumber, DateTime date, decimal ht, decimal vat)
    {
        var lines = new[]
        {
            new JournalLineInput("4111", "Client", ht + vat, 0, null, ThirdPartyKind.None),
            new JournalLineInput("707", "Ventes HT", 0, ht, null, ThirdPartyKind.None),
            new JournalLineInput("436711", "TVA collectée", 0, vat, null, ThirdPartyKind.None)
        };

        return JournalEntry.Create(
            entryNumber, "JV", date, "Facture", Guid.NewGuid(),
            isAutoGenerated: true, sourceEntityType: "Invoice", sourceEntityId: Guid.NewGuid(),
            lineInputs: lines).Value;
    }

    /// <summary>Extourne manuelle : lignes inversées (miroir exact) par rapport à l'écriture d'origine.</summary>
    private static JournalEntry ReversalOf(
        JournalEntry original, int entryNumber, DateTime date, JournalEntryStatus status = JournalEntryStatus.Validee,
        Guid? accountingPeriodId = null)
    {
        var mirrored = original.Lines
            .OrderBy(l => l.LineNumber)
            .Select(l => new JournalLineInput(
                l.AccountNumber, l.Label, l.CreditAmount.Amount, l.DebitAmount.Amount, l.ThirdPartyId, l.ThirdPartyKind))
            .ToList();

        return JournalEntry.Create(
            entryNumber, original.JournalCode, date, $"Extourne {original.JournalCode}-{original.EntryNumber}",
            accountingPeriodId ?? Guid.NewGuid(), isAutoGenerated: false, sourceEntityType: "ManualReversal", sourceEntityId: original.Id,
            lineInputs: mirrored, reversesEntryId: original.Id, initialStatus: status).Value;
    }

    private async Task SeedAsync(IEnumerable<CashOperation> operations, IEnumerable<JournalEntry> entries)
    {
        await using var context = _contextFactory.CreateContext();
        context.CashOperations.AddRange(operations);
        context.JournalEntries.AddRange(entries);
        await context.SaveChangesAsync();
    }

    // ── Édition cabinet (plan v3, tâche 6) ──────────────────────────────────

    /// <summary>Mock <see cref="ICurrentUser"/> minimal : seul <see cref="IsAccountingFirmDelegatedContext"/> est paramétrable.</summary>
    private sealed class FakeCurrentUser : ICurrentUser
    {
        public bool IsAccountingFirmDelegatedContext { get; set; }
        public Guid? UserId => null;
        public string? Email => "test@example.com";
        public Guid? TenantId => null;
        public UserRole? Role => null;
        public bool IsAuthenticated => true;
        public bool HasPermission(string permission) => true;
        public Guid? PortalClientId => null;
        public bool IsClientPortal => false;
        public string? IpAddress => null;
        public string? UserAgent => null;
    }

    /// <summary>Modèle : <c>ValidatePurchaseReceiptCommandHandlerTests.cs</c> — pas de transaction,
    /// l'atomicité réelle est prouvée par les tests SQL (tâche 5, hors périmètre ici).</summary>
    private sealed class PassthroughTenantUnitOfWork : ITenantUnitOfWork
    {
        public Task<Result> ExecuteAsync(
            Func<CancellationToken, Task<Result>> action,
            CancellationToken cancellationToken = default)
            => action(cancellationToken);

        public Task<Result<T>> ExecuteAsync<T>(
            Func<CancellationToken, Task<Result<T>>> action,
            CancellationToken cancellationToken = default)
            => action(cancellationToken);
    }

    /// <summary>Fabrique le handler d'édition cabinet, câblé sur la même factory InMemory.</summary>
    private UpdateDraftJournalEntryCommandHandler BuildUpdateHandler(bool isFirm = true)
    {
        var lettering = new LetteringService(_contextFactory, new TenantAmbientTransaction());
        var chart = new Mock<IChartOfAccountRepository>();
        chart.Setup(x => x.GetByAccountNumberAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((string acc, CancellationToken _) =>
                ChartOfAccount.Create(acc, $"Compte {acc}", int.Parse(acc[..1]), null, AccountNatureType.Debit).Value);
        return new UpdateDraftJournalEntryCommandHandler(
            _repository, chart.Object, new Mock<IAuditService>().Object,
            new FakeCurrentUser { IsAccountingFirmDelegatedContext = isFirm },
            lettering,
            new PassthroughTenantUnitOfWork(),
            new FakeExchangeRateResolver(),
            NullLogger<UpdateDraftJournalEntryCommandHandler>.Instance);
    }

    private static UpdateDraftJournalEntryRequest CashRequest(decimal ht, decimal vat, string label) => new()
    {
        Label = label,
        Lines = new[]
        {
            new ManualJournalLineRequest { AccountNumber = "5411", LineLabel = "Caisse", Debit = ht + vat, Credit = 0m },
            new ManualJournalLineRequest { AccountNumber = "707", LineLabel = "Ventes HT", Debit = 0m, Credit = ht },
            new ManualJournalLineRequest { AccountNumber = "436711", LineLabel = "TVA collectée", Debit = 0m, Credit = vat }
        }
    };

    [Fact]
    public async Task CashDraft_EditedByFirm_AmountsFollowEditedLines_BucketedAtSourceRate()
    {
        var period = SeedPeriod();
        var op = SeedCashSalesOperation(VatRate.Standard);
        var draft = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: op.Id,
            status: JournalEntryStatus.Brouillon, accountingPeriodId: period.Id);
        await SeedAsync([op], [draft]);

        var handler = BuildUpdateHandler();
        var editResult = await handler.Handle(
            new UpdateDraftJournalEntryCommand(draft.Id, CashRequest(200m, 38m, "Corrigé par le cabinet")),
            CancellationToken.None);
        Assert.True(editResult.IsSuccess, editResult.Error?.Description);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().ContainSingle();
        result[0].RatePercent.Should().Be(19);
        result[0].HtBase.Should().Be(200m);
        result[0].VatAmount.Should().Be(38m);
    }

    [Fact]
    public async Task CashDraft_EditedByFirm_VatLineRemoved_DropsFromCandidates()
    {
        var period = SeedPeriod();
        var op = SeedCashSalesOperation(VatRate.Standard);
        var draft = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: op.Id,
            status: JournalEntryStatus.Brouillon, accountingPeriodId: period.Id);
        await SeedAsync([op], [draft]);

        var handler = BuildUpdateHandler();
        var request = new UpdateDraftJournalEntryRequest
        {
            Label = "Corrigé sans TVA",
            Lines = new[]
            {
                new ManualJournalLineRequest { AccountNumber = "5411", LineLabel = "Caisse", Debit = 100m, Credit = 0m },
                new ManualJournalLineRequest { AccountNumber = "707", LineLabel = "Ventes", Debit = 0m, Credit = 100m }
            }
        };
        var editResult = await handler.Handle(
            new UpdateDraftJournalEntryCommand(draft.Id, request), CancellationToken.None);
        Assert.True(editResult.IsSuccess, editResult.Error?.Description);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    [Fact]
    public async Task ManualReversalDraft_EditedByFirm_SignedAmountsFollowEditedLines()
    {
        var period = SeedPeriod();
        var op = SeedCashSalesOperation(VatRate.Standard);
        var original = CashSaleEntry(1, new DateTime(2026, 3, 5), ht: 100m, vat: 19m, sourceOperationId: op.Id,
            accountingPeriodId: period.Id);
        var reversal = ReversalOf(original, 2, new DateTime(2026, 3, 20), status: JournalEntryStatus.Brouillon,
            accountingPeriodId: period.Id);
        original.MarkReversedBy(reversal.Id);
        await SeedAsync([op], [original, reversal]);

        var handler = BuildUpdateHandler();
        var editResult = await handler.Handle(
            new UpdateDraftJournalEntryCommand(reversal.Id, new UpdateDraftJournalEntryRequest
            {
                Label = "Extourne corrigée par le cabinet",
                Lines = new[]
                {
                    new ManualJournalLineRequest { AccountNumber = "5411", LineLabel = "Caisse", Debit = 0m, Credit = 150m + 28.5m },
                    new ManualJournalLineRequest { AccountNumber = "707", LineLabel = "Ventes HT", Debit = 150m, Credit = 0m },
                    new ManualJournalLineRequest { AccountNumber = "436711", LineLabel = "TVA collectée", Debit = 28.5m, Credit = 0m }
                }
            }),
            CancellationToken.None);
        Assert.True(editResult.IsSuccess, editResult.Error?.Description);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        // L'origine (mars) reste à +100/+19 ; l'extourne éditée porte désormais -150/-28.5 (taux
        // résolu depuis l'opération de caisse d'ORIGINE, pas depuis les lignes éditées — D2).
        result.Should().ContainSingle();
        result[0].RatePercent.Should().Be(19);
        result[0].HtBase.Should().Be(100m - 150m);
        result[0].VatAmount.Should().Be(19m - 28.5m);
    }

    // ── Cas simples ────────────────────────────────────────────────────────

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_SingleEntry_ReturnsExactPosting()
    {
        var op = SeedCashSalesOperation(VatRate.Standard);
        var entry = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: op.Id);
        await SeedAsync([op], [entry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().ContainSingle();
        result[0].RatePercent.Should().Be(19);
        result[0].HtBase.Should().Be(100m);
        result[0].VatAmount.Should().Be(19m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_SameRate_SumsAcrossEntries()
    {
        var op1 = SeedCashSalesOperation(VatRate.Standard, sequence: 1);
        var op2 = SeedCashSalesOperation(VatRate.Standard, sequence: 2);
        var entry1 = CashSaleEntry(1, new DateTime(2026, 3, 5), ht: 100m, vat: 19m, sourceOperationId: op1.Id);
        var entry2 = CashSaleEntry(2, new DateTime(2026, 3, 20), ht: 50m, vat: 9.5m, sourceOperationId: op2.Id);
        await SeedAsync([op1, op2], [entry1, entry2]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().ContainSingle();
        result[0].RatePercent.Should().Be(19);
        result[0].HtBase.Should().Be(150m);
        result[0].VatAmount.Should().Be(28.5m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_MixedRates_GroupsCorrectly()
    {
        var op19 = SeedCashSalesOperation(VatRate.Standard, sequence: 1);
        var op13 = SeedCashSalesOperation(VatRate.Intermediate, sequence: 2);
        var op7 = SeedCashSalesOperation(VatRate.Reduced, sequence: 3);
        var entry19 = CashSaleEntry(1, new DateTime(2026, 3, 5), ht: 100m, vat: 19m, sourceOperationId: op19.Id);
        var entry13 = CashSaleEntry(2, new DateTime(2026, 3, 6), ht: 10m, vat: 1.3m, sourceOperationId: op13.Id);
        var entry7 = CashSaleEntry(3, new DateTime(2026, 3, 7), ht: 10m, vat: 0.7m, sourceOperationId: op7.Id);
        await SeedAsync([op19, op13, op7], [entry19, entry13, entry7]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().HaveCount(3);
        result.Should().ContainSingle(p => p.RatePercent == 19 && p.HtBase == 100m && p.VatAmount == 19m);
        result.Should().ContainSingle(p => p.RatePercent == 13 && p.HtBase == 10m && p.VatAmount == 1.3m);
        result.Should().ContainSingle(p => p.RatePercent == 7 && p.HtBase == 10m && p.VatAmount == 0.7m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_OutOfPeriod_IsExcluded()
    {
        var op = SeedCashSalesOperation(VatRate.Standard);
        var entry = CashSaleEntry(1, new DateTime(2026, 2, 15), ht: 100m, vat: 19m, sourceOperationId: op.Id);
        await SeedAsync([op], [entry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_DraftStatus_IsIncluded()
    {
        var op = SeedCashSalesOperation(VatRate.Standard);
        var entry = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: op.Id,
            status: JournalEntryStatus.Brouillon);
        await SeedAsync([op], [entry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().ContainSingle();
        result[0].VatAmount.Should().Be(19m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_NonCashOperationEntryWithVatLine_IsExcluded()
    {
        var invoiceEntry = InvoiceVatEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m);
        await SeedAsync([], [invoiceEntry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_TwoLineCashEntryWithoutVat_IsExcluded()
    {
        var op = SeedCashSalesOperation(vatRate: null);
        var entry = CashEntryWithoutVat(1, new DateTime(2026, 3, 10), amount: 100m, sourceOperationId: op.Id);
        await SeedAsync([op], [entry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_SourceOperationWithoutVatRate_IsIgnored()
    {
        // Cas défensif : l'opération source existe mais son VatRate est null (ne devrait pas
        // produire de ligne 436711 en pratique — protège contre une incohérence de données).
        var op = SeedCashSalesOperation(vatRate: null);
        var entry = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: op.Id);
        await SeedAsync([op], [entry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_SourceOperationMissing_IsIgnored()
    {
        var missingOperationId = Guid.NewGuid();
        var entry = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: missingOperationId);
        await SeedAsync([], [entry]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    // ── Extournes (mouvements signés, v2.1) ─────────────────────────────────

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_CrossPeriodReversal_OriginPeriodUnchangedAndReversalPeriodNegative()
    {
        var op = SeedCashSalesOperation(VatRate.Standard);
        var original = CashSaleEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m, sourceOperationId: op.Id);
        var reversal = ReversalOf(original, 1, new DateTime(2026, 4, 5));
        original.MarkReversedBy(reversal.Id);

        await SeedAsync([op], [original, reversal]);

        var march = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));
        var april = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 4, 1), new DateTime(2026, 4, 30));

        // La période d'origine reste inchangée : positive malgré IsReversed=true sur l'origine.
        march.Should().ContainSingle();
        march[0].RatePercent.Should().Be(19);
        march[0].HtBase.Should().Be(100m);
        march[0].VatAmount.Should().Be(19m);

        // La période d'extourne porte un mouvement négatif.
        april.Should().ContainSingle();
        april[0].RatePercent.Should().Be(19);
        april[0].HtBase.Should().Be(-100m);
        april[0].VatAmount.Should().Be(-19m);

        (march[0].VatAmount + april[0].VatAmount).Should().Be(0m);
        (march[0].HtBase + april[0].HtBase).Should().Be(0m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_SamePeriodReversal_NetsToZero()
    {
        var op = SeedCashSalesOperation(VatRate.Standard);
        var original = CashSaleEntry(1, new DateTime(2026, 3, 5), ht: 100m, vat: 19m, sourceOperationId: op.Id);
        var reversal = ReversalOf(original, 2, new DateTime(2026, 3, 20));
        original.MarkReversedBy(reversal.Id);

        await SeedAsync([op], [original, reversal]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().ContainSingle();
        result[0].RatePercent.Should().Be(19);
        result[0].HtBase.Should().Be(0m);
        result[0].VatAmount.Should().Be(0m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_ReversalOfReversal_IsIgnored()
    {
        var op = SeedCashSalesOperation(VatRate.Standard);
        var original = CashSaleEntry(1, new DateTime(2026, 3, 5), ht: 100m, vat: 19m, sourceOperationId: op.Id);
        var reversal1 = ReversalOf(original, 2, new DateTime(2026, 3, 20));
        original.MarkReversedBy(reversal1.Id);
        var reversal2 = ReversalOf(reversal1, 3, new DateTime(2026, 3, 25));
        reversal1.MarkReversedBy(reversal2.Id);

        await SeedAsync([op], [original, reversal1, reversal2]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        // reversal2 (extourne de reversal1, elle-même une extourne) est ignorée : seules
        // original + reversal1 contribuent, soit un net nul pour le taux.
        result.Should().ContainSingle();
        result[0].VatAmount.Should().Be(0m);
        result[0].HtBase.Should().Be(0m);
    }

    [Fact]
    public async Task GetPostedCashSaleVatByRateAsync_ManualReversalOfNonCashEntry_IsExcluded()
    {
        var invoiceEntry = InvoiceVatEntry(1, new DateTime(2026, 3, 10), ht: 100m, vat: 19m);
        var reversal = ReversalOf(invoiceEntry, 2, new DateTime(2026, 3, 15));
        invoiceEntry.MarkReversedBy(reversal.Id);

        await SeedAsync([], [invoiceEntry, reversal]);

        var result = await _repository.GetPostedCashSaleVatByRateAsync(new DateTime(2026, 3, 1), new DateTime(2026, 3, 31));

        result.Should().BeEmpty();
    }

    // ── ExistsActiveBySourceTypeAsync (§9.7) ────────────────────────────────

    [Fact]
    public async Task ExistsActiveBySourceTypeAsync_ActiveEntryPresent_ReturnsTrue()
    {
        var entry = JournalEntry.Create(
            1, "OD", new DateTime(2026, 3, 1), "Cycle de paie", Guid.NewGuid(), true,
            "PayrollRun", Guid.NewGuid(),
            new[]
            {
                new JournalLineInput("640", "Salaires", 100m, 0, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0, 100m, null, ThirdPartyKind.None)
            }).Value;

        await SeedAsync([], [entry]);

        var exists = await _repository.ExistsActiveBySourceTypeAsync("PayrollRun");

        exists.Should().BeTrue();
    }

    [Fact]
    public async Task ExistsActiveBySourceTypeAsync_NoEntryForSourceType_ReturnsFalse()
    {
        var entry = JournalEntry.Create(
            1, "JC", new DateTime(2026, 3, 1), "Encaissement", Guid.NewGuid(), true,
            "CashOperation", Guid.NewGuid(),
            new[]
            {
                new JournalLineInput("5411", "Caisse", 100m, 0, null, ThirdPartyKind.None),
                new JournalLineInput("707", "Ventes", 0, 100m, null, ThirdPartyKind.None)
            }).Value;

        await SeedAsync([], [entry]);

        var exists = await _repository.ExistsActiveBySourceTypeAsync("PayrollRun");

        exists.Should().BeFalse();
    }

    [Fact]
    public async Task ExistsActiveBySourceTypeAsync_AllEntriesReversed_ReturnsFalse()
    {
        var entry = JournalEntry.Create(
            1, "OD", new DateTime(2026, 3, 1), "Cycle de paie", Guid.NewGuid(), true,
            "PayrollRun", Guid.NewGuid(),
            new[]
            {
                new JournalLineInput("640", "Salaires", 100m, 0, null, ThirdPartyKind.None),
                new JournalLineInput("5411", "Caisse", 0, 100m, null, ThirdPartyKind.None)
            }).Value;
        entry.MarkReversedBy(Guid.NewGuid());

        await SeedAsync([], [entry]);

        var exists = await _repository.ExistsActiveBySourceTypeAsync("PayrollRun");

        exists.Should().BeFalse();
    }

    public void Dispose()
    {
        using var context = _contextFactory.CreateContext();
        context.Database.EnsureDeleted();
    }
}
